updatecli/updatecli

README.md
cmd/root.go
pkg/docker/main.go
pkg/docker/main_test.go

This new source retrieve a docker image digest and can be configured as the following example
```
source:
kind: dockerDigest
spec:
image: "jenkinsciinfra/plugin-site"
url: "hub.docker.com"
tag: latest
```
Closes #16

Add new source dockerDigest

---

Makefile
README.md
cmd/root.go
pkg/config/main.go
pkg/docker/main.go
pkg/docker/main_test.go
pkg/engine/condition/main.go
pkg/engine/main.go
pkg/engine/source/main.go
pkg/engine/target/main.go
pkg/git/main.go
pkg/github/main.go
pkg/maven/main.go
pkg/maven/main_test.go
pkg/scm/main.go
pkg/yaml/main.go
updateCli.d/jenkins-wiki-exporter.yaml
updateCli.d/jenkins.yaml
updateCli.d/nginx.yaml
updateCli.d/pluginsite-api.yaml

* Improve error handling.
* Move source, condition, target to separated packages
* Refactor target schema, SCM is not anymore under YAML spec
```
appVersion:
name: "Chart appVersion"
kind: yaml
spec:
file: "charts/jenkins-wiki-exporter/Chart.yaml"
key: appVersion
-      message: "[updatecli][jenkins-wiki-exporter] Helm chart appVersion updated"
-      scm: "github"
-      repository:
+    scm:
+      github:
user: "updatecli"
email: "updatecli@olblak.com"
```
Closes: #11

Refactor engine workflow

---

pkg/engine/target/main.go
pkg/yaml/main.go

During target refactoring, I introduce a regression where target tries to commit changes even if nothing changed
Closes #34

Correctly skip target when nothing has to be done

---

pkg/yaml/main.go

* Remove 'Updating key...' as it hasn't be done yet and is redundant with the output that follow.
* Update the 'what has been done' message to be more explicit on what changed and where

Rework yaml package output

---

README.md
cmd/root.go
pkg/config/main.go
pkg/config/template.go
updateCli.d/jenkinsio.tpl

If a configuration file has an extension .tmpl or tpl, then it uses the go template engine to generate the finale configuration file, which allow more flexibility 
https://github.com/olblak/updatecli/issues/32 
Example
`./bin/updatecli --config updateCli.test.tpl --values values.yaml`

Add configuration option using go templates

---

Makefile
README.md
cmd/apply.go
cmd/diff.go
cmd/root.go
cmd/show.go
pkg/engine/main.go
pkg/engine/options.go
pkg/engine/target/main.go
pkg/engine/target/options.go

* Add parameters [--commit, --push, --clean], in order to not commit/push/clean if needed
* Add `diff` subcommand to show what would change
* Improve documentation

Add a diff sub command and more parameter

---

pkg/engine/target/main.go
pkg/git/main.go
pkg/github/main.go
pkg/scm/main.go
pkg/yaml/main.go

This works out great.
Here you got the updated commit message:
```
[updatecli] Update external-dns version to 2.20.4
Key 'versions.externalDns', from file 'system-services/helm/values.yaml', was updated to '2.20.4'
```
Not sure making name required is desired or not but for my use-case it works.
I was thinking of taking the name from source if none is supplied but it became cumbersome changeset.
for maven you would use `artifactId` and github release you would use `repository`
for docker you would use `imageName` and helm chart you would use chart `name`
WDYT?

make title and message pretty

---

README.md
pkg/engine/main.go
pkg/engine/source/main.go
pkg/engine/target/main.go

* Allow to also specify prefix/postfix per target instead of from source
* Remove useless variables
Resolve #61

Only use prefix/postfix when updating target

---

pkg/engine/condition/main.go
pkg/engine/target/main.go
pkg/scm/main.go
pkg/yaml/main.go
updateCli.d/grafana-loki.tpl
updateCli.d/jenkins-chart.tpl
updateCli.d/noYamlConditionScm.tpl

Resolve #59 
This PR refactors the way target and YAML works in order to
* Prepare the land for other targets than YAML like JSON or other formats
* Use YAML in condition as well
* Allow using YAML condition and target with or without scm definition, if no definition is specified then YAML file is read from the local path starting at the updatecli binary location.
YAML condition looks like 
```
######################
######################
SOURCE:
=======
...
CONDITIONS:
===========
✔ Key 'targets.imageTag.kind', from file 'updateCli.d/jenkins.yaml', is correctly set to yaml'
✗ Key 'targets.imageTag.kind', from file 'updateCli.d/jenkins.yaml', is incorrectly set to yaml and should be wrongValueTest'
✗ cannot find key 'targets.imageTag.kindkindkind' from file …
```

Use YAML in condition as well

---

pkg/helm/chart/main.go

Resolve #63 
```
SOURCE:
=======
✔ Helm Chart 'jenkins' version '2.3.0' is founded from repository https://kubernetes-charts.storage.googleapis.com
```

Add helm chart source message

---

pkg/github/main.go

Sometimes special characters are included in release name but not in the release tag name, as [here](https://api.github.com/repos/olblak/updatecli/releases/latest)

Github release return release tag_name instead name

---

examples/updateCli.d/docker-compose.yaml
pkg/engine/target/main.go

This pr now looks YAML file into multiple locations
if a directory is not defined in the yaml configuration then it checks if the specified file exists on the disk based on the path otherwise search locally from where we run the command
I used the command `updatecli diff --config config.yaml` on the following config.yaml file to validate
.config.yaml
```
source:
kind: dockerDigest
spec:
image: "olblak/polls"
tag: "latest"
targets:
imageTag:
name: "updatecli docker image tag"
kind: "yaml"
prefix: "olblak/polls@256:"
spec:
#path: "/tt"
#file: "/home/olblak/Project/Jenkins-infra/polls/docker-compose.yaml"
file: "../../Jenkins-infra/polls/docker-compose.yamli"
#file: "docker-compose.yamli"
key: "services.api.image"
```

Search yaml target file into multiple location

---

README.md
pkg/engine/source/main.go
pkg/engine/source/replacer.go
pkg/engine/source/replacer_test.go

Sometimes it happens that a source returns unwanted strings and we want to remove a sub part.
An example, the release tag from [https://github.com/Azure/azure-cli/releases](github.com/azure/azure-cli) prefix 'azure-cli-' to version name like `azure-cli-2.9.1` but the docker image tag doesn't contain that 'azure-cli-'
So to automated tag update, we need to be able to remove such strings

Add replace rules in source definition

---

go.mod
go.sum
pkg/github/main.go
pkg/github/pullrequest.go

Switching to the GitHub Graphql Api allows us to only query the fields that we need, more information [here](https://developer.github.com/v4/#why-github-is-using-graphql)
resolve #80 
resolve #52

Use Github Graphql api

---

examples/updateCli.d/jenkins-wiki-exporter.tpl
examples/updateCli.d/pluginsite-api.tpl
pkg/engine/main.go
pkg/engine/source/main.go
pkg/engine/target/main.go
pkg/github/main.go
pkg/github/pullrequest.go

Fix a regression where we didn't test if the latest github release was a draft release or not
Add github release changelog to PR when changes need to be applied

Retrieve and use source changelog when available

---

pkg/yaml/main.go

Fix #98 
We weren't updating the new value in the case of  an array list which looks like:
```
array:
- value0
- value1 
```

Correctly set version when updating yaml array list

---

doc/README.adoc

this removes the pinning in the docs. Not sure if you want to have comment there suggesting they can pin it.

use latest download link in github action

---

cmd/apply.go
cmd/diff.go
cmd/root.go
cmd/show.go
pkg/engine/condition/main.go
pkg/engine/target/main.go
pkg/git/main.go
pkg/github/main.go
pkg/tmp/main.go

Fix #105 
This PR improve several things:
* Add a clean parameter for the diff subcommand like `updatecli diff --clean=true`
* By default delete the temporary directory content at the end of a full run instead of per strategy run, so we only clone git repositories once
* Change --clean parameter to keep or delete the main working directory instead of per repository 
This PR drastically drastically improve performances, I tested on [jenkins-infra/charts](https://github.com/jenkins-infra/chart)
Before:
`updatecli apply --config updateCli/updateCli.d --values updateCli/values.yaml  39,12s user 6,91s system 43% cpu 1:45,92 total`
After:
`updatecli apply --config updateCli/updateCli.d  --values updateCli/values.yaml   30,29s user 3,60s system 66% cpu 51,092 total
`

Only clone git repository once

---

.github/workflows/publish-assets.yaml
utils/build.sh

Noted the last two releases did not come with all the assets, so created this to upload them all on publish.

upload assets on published release

---

.github/workflows/publish-docker-image.yaml

This github secret conflicts with another one used for testing

Use different DOCKERHUB_TOKEN for github action

---

pkg/plugins/docker/condition.go
pkg/plugins/docker/main.go
pkg/plugins/docker/main_test.go
pkg/plugins/docker/registry/dockerregistry/main.go
pkg/plugins/docker/registry/ghcr/main.go
pkg/plugins/docker/registry/ghcr/main_test.go
pkg/plugins/docker/source.go

Correctly retrieve docker image digest from ghcr.io.
This PR also removes the architecture setting. I can't find a reliable way to test if a docker image exists for a specific architecture so I prefer to remove this option to avoid any confusion.
Fix #124 

Correctly retrieve docker image digest from ghcr.io.

---

Dockerfile
Makefile

This PR correctly set variable that contains version information like
```
VERSION
Application:	v0.0.25-7-gb292cf8
Golang     :	1.15.5 linux/amd64
Build Time :	Sun, 22 Nov 2020 13:53:57 +0000
```
Instead of the current broken situation that return nothing like 
`docker run olblak/updatecli:v0.0.24 version` returns
```
VERSION
Application:	
Build Time :	
```

Correctly build updatecli from Dockerfile

---

pkg/plugins/yaml/main.go
pkg/plugins/yaml/main_test.go

Remove unneeded code which and add missing tests to catch this in the future
fix #129 

[yaml] Use the correct position when parsing sequence of map

---

pkg/core/engine/target/main.go
pkg/core/scm/main.go
pkg/plugins/git/generic/main.go
pkg/plugins/git/scm.go
pkg/plugins/github/main.go
pkg/plugins/github/scm.go

Because we didn't exit function , related to git, in case of errors, we had situations where a git push command would fail but then it would try to open a pr instead of just exiting. This should be handled now

Git function return errors instead of just displaying them

---

pkg/core/engine/main.go
pkg/core/engine/source/main.go
pkg/plugins/docker/main_test.go
pkg/plugins/docker/source.go
pkg/plugins/github/source.go
pkg/plugins/helm/chart/main_test.go
pkg/plugins/helm/chart/source.go
pkg/plugins/maven/main_test.go
pkg/plugins/maven/source.go
pkg/plugins/yaml/source.go

Add source "YAML".
This change needed some refactoring on the source interface in order to fetch files from a scm repository.
The source yaml can be configured as follow
```
source:
kind: yaml
spec:
file: examples/values.yaml
key: "github.user"
#scm:
```

Add source YAML

---

examples/updateCli.generic/file.tpl
pkg/core/engine/condition/main.go
pkg/core/engine/main.go
pkg/core/engine/source/main.go
pkg/core/engine/target/main.go
pkg/plugins/file/condition.go
pkg/plugins/file/helpers.go
pkg/plugins/file/main.go
pkg/plugins/file/source.go
pkg/plugins/file/target.go

This new resource allows manipulating files in various ways
parameters:
- file
- content
**Source**
A "source" file fetch content from a file then propagate it to later stages
**Condtion**
Test that a file content match
**Target**
Create or update a file content
The parameter file access different kind of information
. Any valid HTTP URL starting with `https://` or `http://`
. A file URL starting with file://
. A file path (absolute or relative)
This resource also work with scm 
This PR also include a configuration using file into different setups

Add resource file

---

cmd/docs.go
cmd/root.go

Add hidden command to generate markdown documentation targeting a coming updatecli doc website.
```
updatecli docs -d <HOME_DIR>/commands
```

Add hidden command to generate markdown documentation

---

pkg/core/engine/main.go
pkg/plugins/file/condition.go
pkg/plugins/file/helpers.go
pkg/plugins/file/source.go
pkg/plugins/file/target.go
pkg/plugins/yaml/condition.go
pkg/plugins/yaml/main.go
pkg/plugins/yaml/source.go
pkg/plugins/yaml/target.go

This PR refactor the file and yaml resource in order to use the same function to manipulate files.
Yaml now use the same approach than file resource by 
* Deprecating the parameter 'path', that parameter was a mistake since the beginning
* The parameter 'File' now accepted following URL 
** `https://url`, `http://`, `file://` `file://`

Yaml resource can read file from http url

---

pkg/plugins/docker/main.go

Docker image tag from docker.io registry couldn't be found

Add docker.io as an alias for dockerhub registry

---

pkg/plugins/github/changelog.go
pkg/plugins/github/main.go

Display a specific message when no changelog available from a Github Release

Display a specific message when no changelog available from a Github Release

---

.github/workflows/codeql-analysis.yml
.github/workflows/go.yaml
.github/workflows/release-drafter.yml
README.adoc
doc/README.adoc
doc/scenarios/docker-compose.adoc
examples/updateCli.d/dockerfile.tpl
examples/updateCli.d/jenkins.tpl
examples/updateCli.d/jenkins.yaml
examples/updateCli.d/nginx.yaml
examples/updateCli.d/updateCli.tpl
examples/updateCli.generic/dockerfile.tpl
examples/updateCli.generic/githubRelease.tpl
examples/updateCli.generic/helmRelease.tpl
examples/updateCli.generic/maven.yaml
examples/values.yaml

Closes #93 .
After renaming the principal branch to `main`, some elements have to be changed to fix documentation's links, example, CI process, etc.
This PR is split in 3 commits:
- MUST HAVE: Replacing occurrences of `master` by `main` in git context (to fix dead links, example and CI)
- NICE TO HAVE: Replacing occurrences of `master` by `controller` in Jenkins context
- NICE TO HAVE: My editor auto-removed some trailing blank characters

Remove occurences of 'master'

---

cmd/apply.go
cmd/diff.go
cmd/prepare.go
cmd/root.go
cmd/show.go
pkg/core/config/template.go
pkg/core/reports/main.go
pkg/plugins/git/generic/main.go

Now that better catch errors during run some of them prevent updatecli to finish a run.
This PR handle some of them
* Don't panic but return errors during config templating, we still want to apply valid update strategies
* Don't exist if something went wrong during the prepare stage but instead try to apply strategies that can be apply

Better Handle errors

---

pkg/core/engine/main.go

Fix a regression where running `updatecli show` would show nothing

Read configurations before showing them

---

examples/updateCli.generic/transformers/jenkins.tpl
pkg/core/engine/condition/main.go
pkg/core/engine/source/main.go
pkg/core/engine/source/replacer.go
pkg/core/engine/source/replacer_test.go
pkg/core/engine/target/main.go
pkg/core/transformer/main.go
pkg/core/transformer/main_test.go
pkg/core/transformer/replacer.go
pkg/core/transformer/replacer_test.go

Fix #160 
Fix #152 
Add the parameter `transformers` for every stage definitions, "source", "condition", and "target".
A "transformers" contains a list of transformer rule which are applied successively to the source value.
Each transformer applies a different rule
We also deprecated string manipulation like prefix/postfix/replacer defined outside a transformers definition
* `prefix`, add a prefix to the source value
* `suffix`, add a suffix to the source value
* `trimPrefix`, remove the source value prefix
* `trimSuffix`, remove the source value suffix
* `replacer`, replace a substring by another one in the source value
* `find`, return the first occurrence that matches the regex
```
source:
name: "Get latest jenkins weekly version"
kind: jenkins
transformers:
- prefix: "alpha-"
- …
```

Add transformer definition

---

pkg/plugins/git/generic/main.go

If a git repository contains local changes, then updatecli won't remove them.
This PR will ensure that behavior
```
✔ Helm Chart 'keycloak' is available on https://codecentric.github.io/helm-charts for version '9.9.0'
✗ worktree contains unstaged changes
```

Throw away local changes from git repository

---

examples/updateCli.generic/file/checksum.tpl
examples/updateCli.generic/file/file.tpl
pkg/plugins/file/condition.go
pkg/plugins/file/line.go
pkg/plugins/file/line_test.go
pkg/plugins/file/main.go
pkg/plugins/file/source.go
pkg/plugins/file/target.go

Add parameter "line" to identify a specific line.
It behaves differently depending on the stage
**source** 
Return the first list that contain the string
**condition**
Return true for the first line that match the string
**target**
Update file based on the first line returned from string

[File] add line matcher to File resource

---

pkg/plugins/github/pullrequest.go

Fix #184 
* Display changelog as code block in github pull request
* Use detail balise for changelog
Example: https://github.com/olblak/charts/pull/73

Update GitHub Pull Request Format

---

.github/workflows/publish-docker-image.yaml
Dockerfile
Makefile

The last release [`v0.1.0`](https://github.com/updatecli/updatecli/releases/tag/v0.1.0) failed to build the Docker image: https://github.com/updatecli/updatecli/runs/2014386430?check_suite_focus=true.
This PR aims at fixing these issues, following the work done in #188 .
It introduces the following changes:
* Introduce a build arg to the docker image to specify the make target to use in the "builder" image. It defaults to `build` on a PR, but should be `build.all` on a tagged build (need to be tested with a tag build)
* Build the Docker images even on Pull Requests to catch build errors earlier (the condition of "push image if not a pull request is already present)
* Disable the arm build which was failing the release: the goal would be to improve the build process in the future and …

Fix Docker Build/Push

---

pkg/core/config/main.go
pkg/core/config/main_test.go

Fix #192 
If we don't specify a pipelineID, then it generates one based on the pipeline configuration file using a checksum.
A problem occurred when that configuration contained templated values that would change over each pipeline execution which led to a different pipelineID. This prevented updatecli to identify the same pipeline run.
Instead of generating  configuration checksum, we generate the checksum based on the configuration file content before we inject templated values

config checksum should not consider templated values

---

examples/updateCli.d/sources/dockerfile_sources.tpl
pkg/core/config/main.go
pkg/core/config/template.go
pkg/core/engine/condition/main.go
pkg/core/engine/main.go
pkg/core/engine/target/main.go
pkg/core/reports/main.go
pkg/core/reports/report.go

This PR comes hand in hand with #181  to solve #158 
While keeping backward compatibility, I am switching from one source to a map of sources.
Now for each condition/target, we must specify the `sourceID` parameter to specify which source a condition/target depends on, 
it mainly used to get default values for those stages.  
An example of this change
```
---
title: Bump jenkinsciinfra/helmfile image
sources:
helm:
name: Get Latest helm release version
kind: githubRelease
spec:
owner: "helm"
repository: "helm"
token: {{ requiredEnv .github.token }}
username: olblak
version: latest
helm2:
name: Get Latest helm release version
kind: githubRelease
spec:
owner: "helm"
repository: "helm"
token: {{ requiredEnv .github.token }}
username: olblak
version: latest
conditions:
isENVSet:
```

Add multi sources support

---

examples/updateCli.generic/githubRelease.tpl
pkg/plugins/github/changelog.go
pkg/plugins/github/main.go
pkg/plugins/github/pageInfo.go
pkg/plugins/github/rateLimit.go
pkg/plugins/github/scm.go
pkg/plugins/github/source.go
pkg/plugins/github/source_test.go
pkg/plugins/helm/chart/source.go
pkg/plugins/version/main.go
pkg/plugins/version/main_test.go
pkg/plugins/version/semver/main.go
pkg/plugins/version/semver/main_test.go

Fix #175 
Fix #182 
Add a new parameter `versiontype` which allows defining the kind of version we are fetching.
this new parameter accepts one of the two following values "semver" or "text". Default is set to semver
The parameter github.version can handle version pattern as explained in the following example
*semver*
If semver is used then it means we are looking for a version following the semantic versioning rules. we can provide a version pattern in the Github `version` and any rule explained here [here](https://github.com/Masterminds/semver#checking-version-constraints) can be used.
It's important to notice that in the process we drop any character not compliant with the semantic versioning like if a version starts with v, so this value must be added using `transformers` like in the …

Add version pattern for Github Source and correctly handle github tags

---

pkg/core/engine/source/main.go

In the default behavior, updatecli tries to guess changelog information using the value returned from a source. 
There is a bigger chance that this initial value can be used to retrieve changelog information than once it has been transformed for later stages.
Thanks, @dduportal  for identifying this issue
Btw I still have some plan to define a changelog configuration to customize the way we retrieve changelog information as described in this issue #159 

First get changelog information before applying transformers to the source value

---

pkg/plugins/git/main.go
pkg/plugins/git/main_test.go
pkg/plugins/git/scm.go

- Fix git directory setting, even if we specified the value via the updatecli configuration it was always overridden by the default 
- Default git branch set to main
- Sanitize git directory name to remove cumbersome characters

Various Git cleanup

---

pkg/core/transformer/main.go
pkg/core/transformer/main_test.go

`semverImc` is a new transformer that increment following semantic versioning rules. 
It accepts comma separated list of ["major","minor","patch"]
```
transformers:
- semverInc: "major"
- semverImc: "major,minor,patch"
```

Add transformer semverInc

---

pkg/plugins/git/generic/main.go

Allow '-' in git branch name as it's a valid branch name character

Allow '-' in git branch name

---

pkg/plugins/helm/chart/main_test.go

It appears that tor-proxy has been totally removed, I am just how long this new test will work

Update helm chart test

---

pkg/core/engine/target/main.go
pkg/plugins/docker/dockerfile/target.go
pkg/plugins/file/target.go
pkg/plugins/git/commit/main.go
pkg/plugins/git/commit/main_test.go
pkg/plugins/git/main.go
pkg/plugins/git/scm.go
pkg/plugins/github/main.go
pkg/plugins/github/scm.go
pkg/plugins/helm/chart/main_test.go
pkg/plugins/yaml/target.go

Add Git conventional commit support to updatecli. 
It can now be used from the scm configuration within target definition as defined in the following example.
```
targets:
imageTag:
name: "jenkins/jenkins docker tag"
kind: yaml
spec:
file: "charts/jenkins/values.yaml"
key: "jenkins.controller.imageTag"
scm:
git:
url: "git@github.com:olblak/charts.git"
branch: master
user: olblak
email: me@olblak.com
directory: "/home/olblak/Project/Jenkins-infra/charts"
commitMessage:
type: fix
scope: deps
```
```
commitMessage:
type:       // Specify commit type, default set to chore
scope:    // Specify commit scope,  *Optional
footer:     // Specify commit footer message *Optional
title:        // Override default body message
hideCredit: // Remove "Made with ❤️️  by updatecli" from commit message …
```

Add git conventional commit

---

pkg/plugins/file/target.go

When updating a file from a git repository, we were writing the new content to the wrong location 
```
`go build -o bin/updatecli`
<from local updatecli>/bin/updatecli apply --config updatecli/updatecli.d --values updatecli/values.yaml  --push=false --debug --clean=false
```
/
/

Fix path when updating files from a git repository

---

examples/updateCli.generic/shell/condition.sh
examples/updateCli.generic/shell/shell.yaml
examples/updateCli.generic/shell/source.sh
examples/updateCli.generic/shell/target.sh
pkg/core/engine/condition/main.go
pkg/core/engine/source/main.go
pkg/core/engine/target/main.go
pkg/plugins/shell/command.go
pkg/plugins/shell/command_test.go
pkg/plugins/shell/condition.go
pkg/plugins/shell/condition_test.go
pkg/plugins/shell/errors.go
pkg/plugins/shell/main.go
pkg/plugins/shell/main_test.go
pkg/plugins/shell/source.go
pkg/plugins/shell/source_test.go
pkg/plugins/shell/target.go
pkg/plugins/shell/target_test.go

Closes #263 
It introduces a new resource of type `shell` to allow executing a custom command.
* For sources, this resource uses the stdout of the command to report the value to updatecli, if and only if the exit code is 0, otherwise it fails, and the stderr of the command is reported by updatecli to the end user.
* For conditions, this resource executes a command with the associated source appended as last argument. If the exit code is 0 then the condition succeed, otherwise it fails.
* For targets, this resource executes a command with the associated source appended as last argument. Then:
* If the exit code is zero AND the stdout reports a non empty string, then updatecli reports that there was a change, and the stdout reports what has changed.
* If the exit code is zero and stdout is …

Add a new resource of type "shell"

---

pkg/plugins/shell/errors.go

while writing the documentation for the new shell resource introduced in #264 in https://github.com/updatecli/website/pull/119, I caught this tiny bug (should only be a patch)
```
go test
```

bugfix: correct error report when using a shell resource (inverting stdout and stderr)

---

updatecli/updatecli.d/golang.yaml
updatecli/updatecli.d/gorelease.yaml

Fix wrong updatecli configuration introduced by https://github.com/updatecli/updatecli/pull/270

Fix golang version automated update

---

README.adoc

Click on the links and that opens a non-404 page :) 
You have to click to test the change.

Fixes links to adopter/contributing docs

---

.github/workflows/updatecli.yaml
updatecli/scripts/updateGomodGoversion.sh
updatecli/updatecli.d/golang.yaml

This should lead to a successful update of #273 once merged.
As explained in https://github.com/updatecli/updatecli/pull/273#issuecomment-932687710, there is an issue with the current `go.mod` update process:
- The go.mod file expects a version without the patch (only major and minor) as per ref. https://golang.org/ref/mod#go-mod-file-go
- Ideally, changing the go version should be done with 2 go mod <..> commands:
- go mod edit -go=<new version without patch>
- When the go version is changed in the go.mod file, then the command go mod tidy is needed because the internal format can change between minor version (this is the case here with 1.16 to 1.17). It might also update the go.sum.
This PR uses a shell resource as a "source", to update the go version of the go mod in a temp dir, and …

fix: correct updatecli golang manifest to update go.mod

---

.goreleaser.yml

Fix #154 (this PR is the last mile)
This PR enables distribution of updatecli through an [homebrew tam](https://docs.brew.sh/Taps).
It follows the [goreleaser's homebrew documentation](https://goreleaser.com/customization/homebrew/) and the official [homebrew tap maintainer documentation](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap).
The repository updatecli/hombrew-updatecli had been created (empty) to hosts the formula with the homebrew default convention naming.
We have to perform a release to end-2-end validate.
Once a release will be performed after merging this PR, then a macOS user will be able to install updatecli with:
```
brew install updatecli/updatecli
```

Feat: enable distribution with homebrew

---

.github/workflows/release-sandbox.yaml
.github/workflows/release.yaml
.goreleaser.yml

This PR aims at fixing the homebrew tap publication (ref. https://github.com/updatecli/updatecli/runs/3801471145?check_suite_focus=true#step:10:138) during its initial creation with the [v0.8.0 release](https://github.com/updatecli/updatecli/releases/tag/v0.8.0).
The failure was due to the token `GITHUB_TOKEN` provided to goreleaser by github actions. This token is able to publish release or packages to the repository `updatecli/updatecli`, but it does not have any authorization for the repository that should host the homebrew's tap (`updatecli/homebrew-updatecli`).
This PR defines a second token in goreleaser configuration, only for the homebrew publication.
I've created a PAT for this, and tested it for an initial "manual" release for v0.8.0 and it worked:
```
brew tap …
```

chore: fix homebrew publication

---

examples/updateCli.generic/file.yaml
pkg/plugins/file/condition.go
pkg/plugins/file/condition_test.go
pkg/plugins/file/source.go
pkg/plugins/file/source_test.go
pkg/plugins/file/target.go
pkg/plugins/file/target_test.go

While writing the documentation (https://github.com/updatecli/website/pull/161) for the new file features introduced in #313 , I caught missing error messages and an error in the "generic reference YAML example".
This PR aims to fix these.
```
go test
```
Please note that this PR should only result in a pacth version of `updatecli`/

fix(file) add missing validation messages + improve test coverage 

---

examples/updateCli.generic/shell/condition.sh
examples/updateCli.generic/shell/shell.yaml
examples/updateCli.generic/shell/target.sh
pkg/plugins/shell/command.go
pkg/plugins/shell/condition.go
pkg/plugins/shell/condition_test.go
pkg/plugins/shell/errors.go
pkg/plugins/shell/main.go
pkg/plugins/shell/source.go
pkg/plugins/shell/target.go
pkg/plugins/shell/target_test.go

- Fixes #325 by printing newlines:
```
changeGrepVersion
-----------------
The shell 🐚 command "./examples/updateCli.generic/shell/target.sh change GNU" ran successfully with the following output:
----
/usr/bin/grep
-rwxr-xr-x  1 root  wheel  173440 Oct 18 05:30 /usr/bin/grep
----
DEBUG: command stderr output was:
----
+ test -n change
+ [[ true == false ]]
+ log 'Variable DRY_RUN is different than false'
+ echo 'Variable DRY_RUN is different than false'
Variable DRY_RUN is different than false
+ [[ change == \c\h\a\n\g\e ]]
+ log 'Change but in dry run'
+ echo 'Change but in dry run'
Change but in dry run
+ command -v grep
++ command -v grep
+ ls -l /usr/bin/grep
----
```
- Centralized log method to avoid discrepancy between differents log output for shell
- Improves …

fix(shell) correct logging output

---

examples/updateCli.generic/yaml.yaml
pkg/plugins/yaml/condition.go
pkg/plugins/yaml/condition_test.go

Fix #358.
Depends on #360 
This PR ensures that a condition where the input source value is provided uses this value instead of failing.
```
go build -o ./dist/updatecli && ./dist/updatecli diff --config ./examples/updateCli.generic/yaml.yaml
```
- Added unit tests for yaml condition (coverage of 100% for this source file)
- Factorized code in yaml condition to ensure the same behavior between SCM and non SCM
- Ensure that logging is reusing the constants for the unicode emojis

fix(yaml) allow condition without a source input value 

---

examples/updateCli.generic/yaml.yaml
pkg/plugins/file/condition.go
pkg/plugins/file/target.go
pkg/plugins/yaml/condition.go
pkg/plugins/yaml/target.go
pkg/plugins/yaml/target_test.go

Fix #359 .
Depends on #360 and #362 
```
go build -o ./dist/updatecli && ./dist/updatecli diff --config ./examples/updateCli.generic/yaml.yaml
```
- Added unit tests for yaml target (not complete coverage: Yaml encoder mocking ain't easy)
- Factorized code in yaml target to ensure the same behavior between SCM and non SCM
- Ensure that logging is reusing the constants for the unicode emojis

fix(yaml) specifying a value takes precedence over the source input

---

go.mod
go.sum
pkg/core/text/main.go
pkg/plugins/file/condition.go
pkg/plugins/file/target.go

Fix #369 
Example of output:
```text
pdateGroovyCode
----------------
✔ File content for "/var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/jenkins-infra/pipeline-library/vars/buildDockerAndPublishImage.groovy", updated. 
--- /var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/jenkins-infra/pipeline-library/vars/buildDockerAndPublishImage.groovy
+++ /var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/jenkins-infra/pipeline-library/vars/buildDockerAndPublishImage.groovy
@@ -33,7 +33,7 @@
),
containerTemplate(
name: 'next-version',
-        image: config.nextVersionImage ?: 'ghcr.io/jenkins-x/jx-release-version:2.4.13',
+        image: config.nextVersionImage ?: 'ghcr.io/jenkins-x/jx-release-version:2.5.1',
command: 'cat',
ttyEnabled: true, …
```

enh(file) improve Diff output when a file is changed

---

pkg/plugins/git/generic/main.go

Fix #366 
The PRs #313 and #363 reworked the resources `file` and `yaml` with the side effect of switching the list of file path returned by their `TargetFromScm()` function to absolute paths, leading to error `entry not found` when git-adding the files in a target with scm case.
This PR fixes this behavior by treating the file path directly into the git generic plugin: if the file path that should be git added are absolute, then updatecli tries to convert these paths as relative to the scm's working directory (or raise an error otherwise).
```shell
git checkout https://github.com/jenkins-infra/pipeline-library -b c5c4b22
cd pipeline-library
updatecli-next --debug apply --values ./updatecli/values.yaml --config …
```

fix(git-generic) Ensure that git add works with absolute file paths

---

pkg/core/engine/target/main.go

Fix #375 
The problem was caused because the "if block"  responsible to open the pull request was not position in the correct location.
To fix this issue, we are returning early when a target does not change anything: it removes 1 layer of "if/else" and it ensures that the "if" block responsible for PR creation is NEVER called when there isn"t any change.
Also, the "if block" had been put in the most specific if branch to avoid repeated conditions (!dry run and o.push).
=> IF it causes logic trouble in the cinematic for opening PR, then it means that addition refactoring will be required to ensure that the concept of "happy path" + "early return" are met. Unit tests would greatly help in this case.
Verified against https://github.com/dduportal/charts:
```shell
$ updatecli --debug apply …
```

fix(target) do not open a PR when a target does not change a file

---

examples/updatecli.generic/file.yaml
pkg/core/text/main.go
pkg/plugins/file/condition.go
pkg/plugins/file/condition_test.go
pkg/plugins/file/target.go

Fix #290 
No need for a specific atttribute: only have to disable the source input in condition.
2 examples added in the PR to show how to use it + test units to cover additional cases.
It also add improved output for end user:
- info message for each condition to report if it passed, did not pass, or errored (easier to read when multiple conditions)
- more debug messages on the text package and file condition
```shell
go build -o ./dist/updatecli
./dist/updatecli diff --config ./examples/updateCli.generic/file.yaml
```

feat(file) allow condition to only check for file existence

---

go.mod
go.sum

Ref. https://github.com/advisories/GHSA-5j5w-g665-5m35

fix(dependencies) bump containerd to 1.5.8 and protobuf to 1.27.1 to fix GHSA-5j5w-g665-5m35 security bulletin

---

go.mod
go.sum

Ref. https://github.com/advisories/GHSA-77vh-xpmg-72qh

fix(dependencies) bump image-spec to 1.0.2 to fix GHSA-77vh-xpmg-72qh security bulletin

---

cmd/root.go
pkg/core/engine/main.go
pkg/core/engine/target/main.go
pkg/plugins/aws/ami/condition.go
pkg/plugins/aws/ami/source.go
pkg/plugins/docker/condition.go
pkg/plugins/docker/dockerfile/mobyparser/main.go
pkg/plugins/docker/dockerfile/simpletextparser/main.go
pkg/plugins/docker/dockerfile/simpletextparser/main_test.go
pkg/plugins/docker/source.go
pkg/plugins/file/condition.go
pkg/plugins/file/source.go
pkg/plugins/file/target.go
pkg/plugins/git/tag/condition.go
pkg/plugins/git/tag/source.go
pkg/plugins/git/tag/target.go
pkg/plugins/github/source.go
pkg/plugins/helm/chart/condition.go
pkg/plugins/helm/chart/source.go
pkg/plugins/jenkins/condition.go
pkg/plugins/jenkins/source.go
pkg/plugins/maven/condition.go
pkg/plugins/maven/source.go
pkg/plugins/yaml/source.go

It's a "short term" fix to ensure that the log messages have the same behavior and all use the same emoji.
It also improve code readability as it's easier to understand the constant `result.ATTENTION` than `\u26A0`.
Please note the following changes:
- As we use the package name `result`, when a variable had a conflicting name then it had been changes (3 occurends, 2 are in the AMI package)
- There was slight differences of emojis (2416/2415 for instance) that have been simplified to all use the same from the `result` package
- Sources only have `FAILURE` or `SUCCESS` states
- Same for conditions: only `FAILURE` or `SUCCESS` states
- For targets, `FAILURE` indicates a real error, while `SUCCESS` is used when nothing had been changed, and `ATTENTION` when a change is expected (diff) or …

fix(log messages) homogenize the emojis used for user output messages

---

pkg/plugins/yaml/condition.go

The previous validation error message was not clear when no `sourceID` attribute was specified but the default only source was implicitly used.
```shell
go test
```

chore(yaml) improve condition validation error message to help end users

---

pkg/core/engine/condition/main.go

This PR is a fix for a bug I found while working on #289 .
It ensures that the validation error messages are printed to the end user when a **condition** failed to be validated.
With a manifest having the following condition (missing `spec.file`)
```yaml
conditions:
checkUsername:
kind: yaml
spec:
key: github.username
```
With updatecli 0.16.0, you got:
```shell
CONDITIONS:
===========
checkUsername
-------------
✗ condition not met, skipping pipeline
```
=> result is expected but no message to help the end user.
With this PR, you got:
```shell
$ go build -o ./dist/updatecli && ./dist/updatecli diff
CONDITIONS:
===========
checkUsername
-------------
ERROR: Validation error: the provided manifest configuration had the following validation errors:
Invalid spec for yaml resource: 'file' is …
```

fix(conditions) prints validation error when found

---

.github/release-drafter.yaml

This PR ensures that release drafter determines the next upcoming version correctly, based on current labels.
Once merged, it should change to a patch version (`0.16.1` instead of `0.17.0` when writing these lines)

chore(release-drafter) use an automatic determined version with current labels

---

pkg/plugins/file/main.go
pkg/plugins/file/main_test.go
pkg/plugins/yaml/main.go
pkg/plugins/yaml/main_test.go

This PR follows up #398 and adds a validation for the resources yaml and file.
It fails the validation if the specified file does not exist: it helps end user when they have a typo...
Example of output:
```text
CONDITIONS:
===========
checkUsernameYaml
-----------------
ERROR: Validation error: the provided manifest configuration had the following validation errors:
Invalid spec for yaml resource: the file "toto;yaml" does not exist.
checkUsernameFile
-----------------
ERROR: Validation error: the provided manifest configuration had the following validation errors:
Invalid spec for yaml resource: the file "toto;yaml" does not exist.
```
- Nominal case (non regression):
```shell
go build -o dist/updatecli && ./dist/updatecli …
```

fix(yaml,file) fail validation when the file does not exist

---

pkg/core/config/main.go
pkg/core/config/main_test.go

Fix #281
fix(condition) fail validation when SourceID is missing
fix(target) fail validation when SourceID is missing
test.yaml
```
sources:
getLatestVersion:
kind: shell
spec:
command: echo ami-XXXXX
conditions:
checkIfAmiExist:
name: Test if ami1 exist
sourceID: doNotExist
kind: shell
spec:
command: echo OK
targets:
updateAmiValue:
name: update the AMI value
sourceID: doNotExist
kind: shell
spec:
command: echo OK
```
```shell
go build -o ./dist/updatecli
./dist/updatecli diff --config test.yaml
```

fix: fail validation when SourceID is missing on conditions and targets

---

pkg/core/config/main.go
pkg/core/config/main_test.go
pkg/core/pipeline/sources.go

Fix #285
When a source, referenced through a template function ``{{ source `<source id>` }}`` on another source, is failing,
then the "children" sources are now skipped with an error message.
No worry for conditions: if any source fail, then the condition are never run.
```shell
$ cat .tmp/updatecli.yaml
sources:
parentSource:
kind: shell
spec:
command: ls /titi
childSource:
kind: shell
depends_on:
- parentSource
spec:
command: echo CHILD-{{ source "parentSource" }}
target:
printResult:
kind: shell
sourceID: childSource
spec:
command: echo
$ go build -o ./dist/updatecli && ./dist/updatecli --debug diff -c .tmp/updatecli.yaml
```
example of output:
```
SOURCES
=======
parentSource
------------
The shell 🐚 command "ls /titi" …
```

fix: skip sources when their parent source failed

---

pkg/plugins/helm/chart/target.go

Fix #405 
```shell
./bin/updatecli apply --config examples/updatecli.generic/helmChart/SCM.2.yaml --values examples/values.yaml --debug --clean=false
```

Fix helm chart file path

---

.golangci.yml
pkg/plugins/file/main.go
pkg/plugins/file/main_test.go
pkg/plugins/yaml/main.go
pkg/plugins/yaml/main_test.go

This PR comes from the work in #412 .
It updates the golantci-lint configuration file to support the latest 1.43.x line.
It also applies some of its suggestions.
```shell
go build -o dist/updatecli
./dist/updatecli diff --config ./examples/updatecli.generic/file.yaml
./dist/updatecli diff --config ./examples/updatecli.generic/yaml.yaml
```

Chore: bump golangcilint to 1.43 and apply updated code suggestions

---

examples/updatecli.generic/aws_ami.yaml
pkg/core/pipeline/condition/main.go
pkg/core/pipeline/source/main.go
pkg/plugins/awsami/condition.go
pkg/plugins/awsami/condition_test.go
pkg/plugins/awsami/data_test.go
pkg/plugins/awsami/filter.go
pkg/plugins/awsami/helpers.go
pkg/plugins/awsami/helpers_test.go
pkg/plugins/awsami/main.go
pkg/plugins/awsami/sort.go
pkg/plugins/awsami/source.go
pkg/plugins/awsami/source_test.go
pkg/plugins/awsami/spec.go

This PR comes from the work in #412 .
It refactor the plugin "AWS AMI" to:
- Rename it to follow convention (no direct subdirectories)
- Introduce a method `New(Spec)` to allow initializing an object with a state
- Move the "svc" logic as part of the object state, into an "apiClient" attribute to allow mocking and avoid initializing too late
```shell
go build -o dist/updatecli
./dist/updatecli diff --config ./examples/updatecli.generic/aws_ami.yaml
```

Refactor plugin "AWS AMI"

---

pkg/plugins/github/pullrequest.go

To avoid putting the changelog as unescaped/preformated text like in this PR: https://github.com/jenkins-infra/docker-builder/pull/26
Fixes https://github.com/jenkins-infra/docker-builder/issues/27

fix: correctly escape changelog

---

pkg/plugins/github/pullrequest.go

(e.g. do not query GitHub API for closed PRs)
Co-authored with @olblak to fix #424.
Tested on https://github.com/dduportal/docker-builder/pulls?q=is%3Apr

fix(github) open a new pullrequest if the previous were closed 

---

pkg/core/pipeline/pullRequests.go

Fix #423 
Tested on my fork, it opened the following PR: https://github.com/dduportal/docker-builder/pull/3
which has the changelog content in the expandable block 
In the future, wemight consider to separate the "execution" result of a target (failed, changed, not changed) from its status (run, skipped)

fix(pullrequests) retrieve changelog from both 'successful' and 'attention' targets

---

pkg/core/pipeline/pullRequests.go
pkg/plugins/github/pullrequest.go

- Print a message by default when the dry run is used (and keep the debug detailed output)
- Do no print "Nothing left <...>" and proceed to opening/update Pull Requests when
the targets reports "succeeded" (e.g. not changed). Closes #421
- Fix a typo on GitHub Pull Request log output
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
Co-authored-by: Olblak <me@olblak.com>
Fix #421 
With https://github.com/dduportal/docker-builder/blob/main/updatecli/updatecli.d/ghcli.yml
* Result in "diff" mode:
```
PULL REQUESTS
=============
[Dry Run] A Pull Request is expected (with kind "github" and title "[updatecli] Bump ghcli version").
```
* Result in "diff" mode with debug:
```
PULL REQUESTS
=============
[Dry Run] A Pull Request is expected (with kind "github" and title "[updatecli] …
```

fix(pullrequest) show the correct report for the pull request section

---

go.mod
go.sum

Fix https://github.com/advisories/GHSA-v95c-p5hm-xq8f
Dependabot wasn't able to bump this version because it wasn't in the `required` block of the `go.mod` file (hence it was a transitive dependency).
```shell
go mod tidy
go mod download
go build -o dist/updatecli
go test ./...
```

chore(dependencies): bump and pin runc to 1.0.3

---

updatecli/scripts/updateGomodGoversion.sh
updatecli/updatecli.d/golang.yaml

fix: correct regexp to retrieve last (non beta) go version

---

.github/workflows/go.yaml
pkg/plugins/git/generic/main.go
pkg/plugins/git/generic/main_test.go
pkg/plugins/github/pullrequest.go

Fix #431 
Add a function to test if the latest commits of two branches are similar. The intend of this approach is to only try to create a pullrequest when two branch content mismatch
```shell
cp pkg/plugins/git/generic
go test
```
I am planning to also look at a way to test if two git tags are similar

Don't try to open a pullrequest when not needed

---

pkg/core/config/deprecated.go
pkg/core/config/main.go
pkg/core/config/main_test.go

Fix #442 
To test this pull request, create the following manifest:
```yml
title: Bump Golang Version
scms:
default:
kind: github
spec:
user: updatecli
email: me@olblak.com
owner: updatecli
repository: updatecli
token: 'SuperSecretToken'
branch: main
sources:
latestVersion:
name: Get Latest Version
kind: shell
spec:
command: echo 1.0.0
targets:
release-sandbox:
name: 'Update last version'
sourceID: latestVersion
kind: shell
spec:
command: echo
scmID: default
pullrequests:
default:
title: 'PR Title Here'
kind: github
scmID: default
targets:
- foo
```
you can run the following commands:
```shell
go build -o ./dist/updatecli && ./dist/updatecli diff --config manifest.yaml
```

fix(pullrequests) validate that specified targets exist in the manifest

---

pkg/core/pipeline/condition/main.go
pkg/core/pipeline/source/main.go
pkg/core/pipeline/target/main.go
pkg/plugins/file/main.go
pkg/plugins/helm/main.go
pkg/plugins/yaml/main.go

Fix #458
Sounds like I messed up the helm chart plugin in https://github.com/updatecli/updatecli/pull/437.
This PR fixes it by adding the necessary New() constructor method (otherwise it was not initialized).
Tested on https://github.com/jenkins-infra/kubernetes-management/tree/main/updatecli/updatecli.d/charts manifests with success.
```shell
go build -o ./dist/updatecli && ./dist/updatecli --debug diff --config examples/updatecli.generic/helmChart
```

fix(helm) correct error `unsupported protocol scheme ""`

---

.github/workflows/go.yaml
.gitignore
Makefile
e2e/updatecli.d/source/githubRelease.2.yaml
e2e/updatecli.d/source/githubRelease.yaml
e2e/values.yaml
e2e/venom.d/test_diff.yaml
e2e/venom.d/test_version.yaml
updatecli/updatecli.d/venom.yaml

The goal of those tests is to better test different scenarios and to be sure that updatecli pipeline configurations is still working
To test this pull request, you can run the following commands from a Linux machine:
```shell
make build
make test-e2e
```
As a first iteration, I am testing that a pipeline configuration doesn't contain ERROR or WARNING.
Considering that I would like to land this pr as soon as possible so we can add more test cases later, I am not updating obsolete examples (yet).
Move obsolete examples in the e2e  directory

Init End To End test using venom

---

pkg/core/pipeline/conditions.go

Not usre when this "misbehavior" was introduced but currently, conditions that fails because of an error does not show the error message.
It's not really convenient, particularly when it is a validation error 😅 
This PR fixes the print of error message (minor cleanups around happy path / string comparisons)
```shell
make build
make test
make test-e2e
```

hotfix(conditions) show error message when a condition errors

---

.github/release-drafter.yaml

Unless the tag "minor" is added to the PR for "big" dependency updates

chore(release-drafter) PR about dependencies should only bump patch

---

pkg/plugins/yaml/target_test.go

This is a "quick" PR that cleans up the files generated fby thet target tests for YAML resource.
It was driving me (and @lemeurherve) crazy that running `go test ./... -short` was generating a file in the source code.
Since I haven't had time on the topic for unit tests with mock for YAML, let's do it that way.
Labelled as "skip-changelog" since it does not hold anything useful for end user
```shell
$ git status
$ go test ./... -short
$ git status
```
- Could execute the tests in a temp directory
- Execute mocked tests without any interaction with the I/O file system (real unit tests)

chore(yaml) cleanup file generated during test phase

---

pkg/core/pipeline/pullRequests.go

Fix #484 
In the current state, this PR fix two bugs which by the way could be split into two Pull requests :) 
1. In Dry mode, don't mention that a PR will be open if it's not the case (#484 )
2. Pull request object correctly using the updated configuration. This avoids open pull requests with a message containing templating instruction such as `Bump app to {{ source "source" }}`
1. Run updatecli in dry mode and debug enable, with a updatecli configuration that shouldn't open a pullrequest. We shouldn't have pull request message
2. Run updatecli in dry mode and debug enable, with a updatecli configuration that should open a pull request and where the title contains templating instruction. We should have pull request message …

fix(pullrequests) Do not mention a pull request in dry run when there are no changes

---

pkg/plugins/yaml/main.go
pkg/plugins/yaml/main_test.go
pkg/plugins/yaml/test.yaml

Fix #439
This was a quick one that fixes a real bug (a case on limit).
Thanks to the amount of unit tests that @olblak did on the homemade YAML parser, it was easy to add a failing case, and then fix it.
Now, the following error is thrown when an out of bounds index is specified for YAML arrays:
```
ERROR: ✗ cannot find key "spec.containers[1].name" in the YAML file ".tmp/PodTemplates.yaml"
```
```shell
$ make test-short # Fails without the fix on `pkg/plugins/yaml/main.go`
$ go build -o ./dist/updatecli && ./dist/updatecli diff --config ./.tmp/updatecli.yaml --values ~/workspace/jenkins-infra/kubernetes-management/updatecli/values.yaml
```
- Also removed the "non cleaned" yaml file that was still commited (caught by …

fix(yaml) do not crash when the specified YAML array index does not exist

---

pkg/plugins/dockerfile/simpletextparser/keywords/env.go
pkg/plugins/dockerfile/simpletextparser/keywords/env_test.go

Fix #390
This PR add the support for `ENV` Dockerfile instruction without equal sign (which is considered "legacy" and not recommended by Docker as per https://docs.docker.com/engine/reference/builder/#env)
>  ⚠️ Alternative syntax
> The ENV instruction also allows an alternative syntax ENV <key> <value>, omitting the =. For example:
> ```Dockerfile
>    ENV MY_VAR my-value
> ```
> This syntax does not allow for multiple environment-variables to be set in a single ENV instruction, and can be confusing. For example, the following sets a single environment variable (ONE) with value "TWO= THREE=world":
> ```
>    ENV ONE TWO= THREE=world
> ```
> The alternative syntax is supported for backward compatibility, but discouraged for the reasons outlined above, and may be removed in a future …

fix(dockerfile) manage ENV legacy case without an equal sign

---

pkg/core/engine/main.go
pkg/core/pipeline/conditions.go
pkg/core/pipeline/pullRequests.go
pkg/core/pipeline/pullrequest/main.go
pkg/core/pipeline/sources.go
pkg/core/pipeline/targets.go
pkg/core/reports/main.go
pkg/core/reports/report.go
pkg/core/reports/stage.go

Fix #440 
This PR ensures that the GitHub pull requests (title + description) and command line output are correctly rendered when there is a templated value.
There are 3 commits:
- The 1st commit is cherry-picked from @olblak 's work in #496 that had been modified to have 1 PR == 1 fix + adapted (comments). It applies the same update + rendering of internal configuration behavior when processing pullrequests as when processing sources,conditions and targets.
- The 2nd commit ensures that reports are updated (e.g. rendering templates) as well as the internal configuration when processing sources, but also conditions and targets.
- The 3rd commit is a minor improvement for the reports (deleting unused code + cleaning up/adding spaces)
Example of result: …

fix(pullrequests,reports) renders templated values in title and descriptions

---

README.adoc

I guess after 3700 commits and 3558 pull request we can remove the warning

Remove warning

---

pkg/plugins/scms/github/main.go
pkg/plugins/scms/github/pullrequest.go

Fix #492 
Allow to specify a pullrequest merge method by using the key `mergemethod` set to ["","squash", "merge","rebase"]
```shell
```

Allow to specify github pullrequest merge method

---

e2e/skipped.targets.d/multiple-conditions.yaml
e2e/skipped.targets.d/one-condition.yaml
e2e/venom.d/test_skipped_targets.yaml
pkg/core/pipeline/conditions.go

Fix #526 
This PR revamps what I broke in #470:
- No more updating the pipeline configuration (as it's only required after source execution: there is no point in rendering the template after each condition as for today)
- Keep showing the error (if any) of a condition execution (that was the value of #470)
- Fix the "flow" that was broken by #470 by setting the global result to "false" if there is an error OR if the conditions failed (e.g. did not error but returned with "false").
Please note that a new e2e test suite had been added to catch this case (non regression in the future), as the "flow" tests are hard to test today (pkg/core/pipeline is not unit-tested a lot).
```shell
make test
make test-short
make test-e2e
```

fix(condition) do not execute target if a condition fails

---

go.mod
go.sum

Fix https://github.com/updatecli/updatecli/security/dependabot/4
```shell
go test
```

Bump github.com/docker/distribution to 2.8.0

---

pkg/core/config/main.go

Fixes #536
Log the config name (which default value is the manifest filename) so when updacli is running on a folder and there is an error it's easier to know which manifest has a problem.
```shell
go test
```
One additional line per manifest in the output
This log should even replace the one line 82: https://github.com/updatecli/updatecli/blob/01da81e6c25062cd9f902e173208b766fa4cbdee/pkg/core/config/main.go#L82
WDYT? In that case, this PR could be "fix: log the config name at validation instead of at loading"

fix: log the config name at validation

---

pkg/plugins/resources/yaml/condition.go
pkg/plugins/resources/yaml/condition_test.go
pkg/plugins/resources/yaml/main.go
pkg/plugins/resources/yaml/main_test.go
pkg/plugins/resources/yaml/source.go
pkg/plugins/resources/yaml/target.go

There are situations where a first step is required such as cloning a git repository before validating that a file exists.
So instead I prefer to test that a file exists at runtime for the source/condition/target.
To test this pull request, we can run updatecli command with whatever updatecli manifest as long as we don't execute updatecli from the root of the git directory containing the updatecli manifest. 
This pull request doesn't fix https://github.com/updatecli/updatecli/issues/410 but instead, it moves the `fileexist` to a function executed at runtime.

Test at runtime if a yaml file exists

---

pkg/plugins/utils/gitgeneric/main_test.go

Fix test for all open pullrequest
The two oldest tag are `v0.0.1` and `untagged-902d9ce264ba6334c5d`
The gitgeneric test check the oldest tag. For some reason it now detects `v0.0.1` instead of `untagged-902d9ce264ba6334c5d`
I would propose to just delete the tag `untagged-902d9ce264ba6334c5d` as I don't see its valuue.
```shell
make test-short
```
🤷🏿 
/

Update oldest tag in gitgeneric test

---

pkg/core/transformer/findSubMatch.go
pkg/core/transformer/main.go
pkg/core/transformer/main_test.go

Fix [#517 ](https://github.com/updatecli/updatecli/issues/517)
```shell
cd pkg/core/transformer/
go test
```
This pull request permit 2 ways of calling the FindSubMatch: 
New way : 
```
transformers:
- findSubMatch: 
pattern: '"(.*?):(.*)'
captureIndex: 1
```
or old way : 
```
transformers:
- findSubMatch: '"(.*?):(.*)'
```
which is equivalent of : 
```
transformers:
- findSubMatch: 
pattern: '"(.*?):(.*)'
captureIndex: 0
```

Feat/capture Adding a parameter for the transformer FindSubMatch

---

pkg/plugins/scms/git/scm.go
pkg/plugins/scms/github/scm.go
pkg/plugins/utils/gitgeneric/main.go

As it is right now, authentication with Private Git Repo is not working properly. It can be replicated by trying to make a `pullrequest` to a private repository.
The following PR adds `Auth` property to all the methods supporting `AuthOptions` in `Checkout` method.
```shell
plugins/utils/gitgeneric on  feature/auth-checkout via 🐹 v1.17.5 on ☁️  (us-west-2)
❯ go test
PASS
ok  	github.com/updatecli/updatecli/pkg/plugins/utils/gitgeneric	4.447s
```
n/a

Fix for Authentication Bug with Private Git Repos

---

pkg/plugins/scms/git/main.go
pkg/plugins/scms/git/scm.go
pkg/plugins/scms/git/sign/main.go
pkg/plugins/scms/git/sign/main_test.go
pkg/plugins/scms/github/main.go
pkg/plugins/scms/github/scm.go
pkg/plugins/utils/gitgeneric/main.go

Fix #274
Add ability to specify gpg key and passphrase to sign commits. No passphrase will be treated as empty passphrase.
Tested manually with this config for scm:
```yaml
scms:
default:
kind: github
spec:
user: "{{ .github.user }}"
email: "{{ .github.email }}"
owner: "{{ .github.owner }}"
repository: "{{ .github.repository }}"
token: "{{ requiredEnv .github.token }}"
username: "{{ .github.username }}"
branch: "{{ .github.branch }}"
gpg:
signingKey: |
-----BEGIN PGP PRIVATE KEY BLOCK-----
Blablabla... this is secret
-----END PGP PRIVATE KEY BLOCK-----
enabled: true
```
Also, added a new test for sign package:
```shell
cd updatecli/pkg/plugins/scms/git/sign
go test
```
Any feedback is welcome. I am not familiar with the tool project structure, so if there is a need to change anything in …

Add Signing To Commit Function

---

pkg/plugins/resources/file/source.go
pkg/plugins/resources/file/source_test.go

Fix #558 
If a relative file path is provided with a scmID, then like for condition and target, we want to use the git repository directory as the file root directory
To test this pull request, I used the following updatecli configuration:
.updatecli.yaml
```
---
title: "Test Git scm"
scms:
scenario-1:
kind: git 
spec:
username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
password: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
url: "https://github.com/updatecli/experiment.git"
branch: "main"
sources:
scenario-1:
name: "Scenario 1"
kind: file
scmID: scenario-1
spec:
file: README.md
line: 1
```
```shell
updatecli diff --config updatecli.yaml
```
/
/

Resource "File" correctly uses scmID

---

cmd/root.go
pkg/core/config/main.go
pkg/core/engine/main.go

Fix #552 
This pull request allows to better identify which pipeline is failing due to a bad configuration. 
Now It would show
```
+++++++++++
+ PREPARE +
+++++++++++
Loading Pipeline "updatecli/updatecli.d/golang.yaml"
Loading Pipeline "updatecli/updatecli.d/updatecli.yaml"
Loading Pipeline "updatecli/updatecli.d/venom.yaml"
ERROR: failed loading pipeline(s)
* "updatecli/updatecli.d/golang.yaml" - scms ID "default2" referenced by pullrequest ID "default", doesn't exist
* "updatecli/updatecli.d/updatecli.yaml" - scm id "default222" doesn't exist
```
instead of the old 
```
+++++++++++
+ PREPARE +
+++++++++++
Loading Pipeline "updatecli/updatecli.d/golang.yaml"
Validating ""
Validating "GOLANG.YAML"
ERROR: ✗ scms ID "default2" referenced by pullrequest ID "default", doesn't exist
ERROR: …
```

Improve reporting of pipeline with wrong configuration

---

pkg/plugins/utils/docker/dockerregistry/main.go

Fix #593 
This PR fixes a bug that printed a warning despite username and password being specified for docker(.*) resources.
```shell
cd pkg/plugins/utils/docker/dockerregistry/
go test -v .
```

fix(docker*) do not show a warning when username and password are specified

---

Makefile
examples/updatecli.d/dockerfile.yaml
examples/updatecli.d/jenkins-wiki-exporter.yaml
examples/updatecli.d/pluginsite-api.yaml
examples/updatecli.d/sources/dockerfile_sources.yaml
examples/updatecli.d/updatecli.yaml
pkg/core/pipeline/condition/main.go
pkg/core/pipeline/scm/main.go
pkg/core/pipeline/source/main.go
pkg/core/pipeline/target/main.go
pkg/plugins/resources/githubrelease/main.go
pkg/plugins/resources/githubrelease/main_test.go
pkg/plugins/resources/gittag/condition.go
pkg/plugins/resources/gittag/main.go
pkg/plugins/resources/gittag/source.go
pkg/plugins/resources/gittag/target.go
pkg/plugins/scms/git/scm.go
pkg/plugins/scms/github/main.go
pkg/plugins/scms/github/main_test.go
pkg/plugins/scms/github/scm.go
pkg/plugins/utils/version/main.go
pkg/plugins/utils/version/main_test.go

This PR removes the deprecated code of the field `version`.
It also introduces the following changes:
- Minor change on the `Makefile` to allow executing the end to end test with a custom binary directory (e.g. allow `make test-e2e VENOM_VAR_binpath=./custom-dist/` to use the binary `updatecli` located in `./custom-dist/updatecli`)
- Decouple the SCM handlers from the concept of source. It removes th "source" argument from the method `Init()` (interface ScmHandler) as it was only used to define versionfilters.
Associated documentation PR: https://github.com/updatecli/website/pull/264
```shell
make test
```

 cleanup(gittag, githubrelease) remove deprecated code for field `version`

---

CONTRIBUTING.adoc
examples/updatecli.d/docker-compose.yaml
examples/updatecli.d/dockerfile.yaml
examples/updatecli.d/grafana-loki.yaml
examples/updatecli.d/jenkins-chart.yaml
examples/updatecli.d/jenkins-wiki-exporter.yaml
examples/updatecli.d/jenkins.yaml
examples/updatecli.d/jenkinsio.yaml
examples/updatecli.d/nginx.yaml
examples/updatecli.d/noYamlConditionScm.yaml
examples/updatecli.d/pluginsite-api.yaml
examples/updatecli.d/prometheus.yalm
examples/updatecli.d/updatecli.yaml
examples/updatecli.generic/helmChart/SCM.deprecated.yaml
examples/updatecli.generic/helmChart/noSCM.yaml
examples/updatecli.generic/helmChart/requirement.yaml
examples/updatecli.generic/helmRelease.yaml
examples/updatecli.generic/transformers/jenkins.yaml
pkg/core/config/main.go
pkg/core/config/main_test.go

This PR removes the deprecated syntax `source:` (singular source).
Depends on #588 
Associated documentation PR: https://github.com/updatecli/website/pull/264
```shell
make test
```

cleanup(sources): remove deprecated syntax 'source:' (singular source)

---

CONTRIBUTING.adoc
examples/updatecli.d/docker-compose.yaml
examples/updatecli.d/jenkins.yaml
examples/updatecli.d/updatecli.yaml
pkg/core/pipeline/condition/main.go
pkg/core/pipeline/conditions.go
pkg/core/pipeline/resource/main.go
pkg/core/pipeline/source/main.go
pkg/core/pipeline/target/main.go
pkg/core/pipeline/targets.go

This PR removes the deprecated code for "prefix" and "postfix" (which have been replaced by transformers more than 1 year ago).
Depends on #590 (as there is a common change on the signature of a call to `ScmHandler.Init()`)
Associated documentation PR: https://github.com/updatecli/website/pull/264
```shell
make test
```

cleanup(pipeline) remove deprecated code for prefix and postfix

---

pkg/plugins/scms/github/main.go

Fix #XXX
```shell
go test
```
Saw this while working on #644, quick fix as it is.

fix: use the URL instead of the token to initialize GitHub Enterprise client

---

.github/workflows/go.yaml
Makefile
updatecli/updatecli.d/golangci-lint.yaml

Fix #651 
* Bump golangci-lint version
* Add updatecli manifest to automate version update
```shell
updatecli diff --config updatecli/updatecli.d/golangci-lint.yaml
```
/
/

Bump golanci-lint version used in Github Action

---

pkg/plugins/utils/docker/dockerregistry/main.go
pkg/plugins/utils/docker/dockerregistry/main_test.go

Fix #605 
- add the "application/vnd.oci.image.index.v1+json" content type in the Accept headers of the requests made to the registries
- process the "application/vnd.oci.image.index.v1+json" responses just like "application/vnd.docker.distribution.manifest.list.v2+json" ones
- remove support for "application/vnd.docker.distribution.manifest.v2+json"
- update the quay.io unit test case to be an OCI unit test case
```shell
go test -v ./pkg/plugins/utils/docker/dockerregistry
```
I also made sure to test a real pipeline such as: 
```yaml
title: Miniflux
sources:
miniflux:
name: Miniflux Release
kind: githubRelease
spec:
owner: miniflux
repository: v2
token: REDACTED
versionFilter:
kind: semver
pattern: ~2
conditions: …
```

Adds support for new OCI registries

---

pkg/core/config/main.go
pkg/core/pipeline/condition/main.go
pkg/core/pipeline/target/main.go

Fix #675 
Today I noticed that we don't have the ability to `disablesourceinput` for target.
Similarly to condition, they are cases where a target rely on templating instead of source input  
I tested this pullrequest with manifest containing two sources and one target

Add disablesourceinput to target

---

pkg/core/engine/main.go

Fix #669
Use git directory hash instead of scm spec hash.
Test with whatever manifest using 1 or multiple scm repository
/
/

Fix: scm concurrency issue when running git clone

---

pkg/core/pipeline/condition/main.go
pkg/core/pipeline/main.go
pkg/core/pipeline/scm/main.go
pkg/core/pipeline/source/main.go
pkg/core/pipeline/target/main.go
pkg/plugins/resources/githubrelease/main.go
pkg/plugins/scms/git/main.go
pkg/plugins/scms/git/main_test.go
pkg/plugins/scms/git/scm.go
pkg/plugins/scms/github/main.go
pkg/plugins/scms/github/main_test.go
pkg/plugins/scms/github/scm.go

Fix #699 
The code base evolved in a situation where `scm.Init` was called in different places. That led to have some variable not set in some cases. Instead I move that logic in the `New` function that create SCM spec. I also fix a configuration bug where we couldn't configure GitHub commit behavior. 
In summary:
* Fix git/github scm initialization
* Add comment on git spec and GitHub spec to generate description in Jsonschema
* Expose commit configuration for GitHub SCM resource
```shell
./bin/updatecli diff --config e2e/updatecli.d/success.d/source --values e2e/values.yaml --debug --clean=false 
ls /tmp/updatecli/github_com_updatecli_updatecli_git
```

Fix scm resource initialization

---

pkg/core/config/main.go

Fixes #668
This PR replaces [all the callsites of `strings.Title`](https://github.com/updatecli/updatecli/search?q=strings.Title) with the recommended `cases.Title` method, configured for 'English', with the `cases.NoLower` option to get as close as possible from the behavior of `strings.Title` (https://go.dev/play/p/0lQ9iHPi_Ro)
This change doesn't seem to break the test suite, so that's a first step. I'm unsure how to properly test this though.
```shell
go test ./pkg/core/config/
```
None
None

pkg/core/config: replace deprecated `strings.Title` with `cases.Title`

---

pkg/core/pipeline/main.go
pkg/core/pipeline/scm/main.go
pkg/plugins/scms/github/main.go
pkg/plugins/scms/github/main_test.go

Fix the issue introduced in #700 (ref. https://github.com/updatecli/updatecli/pull/700#issuecomment-1153273824)
```shell
make test
make test-e2e
```
Also tested on jenkins-infra/kubernetes-management
- Added unit tests to underline the error before fixing
- Fixed a typo
- Removed the pointer/references to the pipelineID string. Not sure the reason why pointer was used?

fix(github) initialize the headbranch 

---

updatecli/updatecli.d/golang.yaml

I noticed that the pipeline that update Golang version is broken 
This PR is the fix needed to get it back on track
```
- GOLANG.YAML:
Sources:
✔ [gomod] Update go.mod (kind: shell)
✔ [latestGoVersion] Get Latest Go Release (kind: githubrelease)
Condition:
✔ [dockerTag] Is docker image golang:1.18.3 published (kind: dockerimage)
✔ [workflowgo] Ensure GA step is defined in Github Action named go (kind: yaml)
✔ [workflowrelease] Ensure GA step is defined in Github Action named release (kind: yaml)
✔ [workflowrelease-sandbox] Ensure GA step is defined in Github Action named release-sandbox (kind: yaml)
✗ [workflowupdatecli] [release.yaml] Update Golang version to 1.18.3 (kind: yaml)
Target:
- [go.mod] [go.mod] Update Golang version to {{ source …
```

Fix updatecli manifest for golang update

---

pkg/core/config/template.go

Fix https://github.com/updatecli/updatecli/issues/731
```shell
cat >EOF > pipeline.yml 
---
title: Update test values
sources:
dummy:
name: "Dummy"
kind: shell
spec:
command: echo {{ .Value }}
targets:
dummy:
name: "Dummy"
kind: shell
spec:
command: echo {{ .Value }}
EOF
cat <EOF > values.yml
Value: "foo"
EOF
cp pipeline.yml pipeline.yaml
cp values.yml values.yaml 
go run main.go diff --config pipeline.yml --values values.yml
go run main.go diff --config pipeline.yaml --values values.yml
go run main.go diff --config pipeline.yml --values values.yaml
go run main.go diff --config pipeline.yaml --values values.yaml
```

fix: check if the extension is not `yaml` and not `yml`

---

go.mod
go.sum

Fix https://github.com/updatecli/updatecli/security/dependabot/10

Bump containerd dependency to 1.6.6

---

pkg/core/reports/main.go

Fix a small UI bug where we always display the word "source" and "target" in the report information.
For example running updatecli against the following manifest 
```
scms:
default:
kind: git 
spec:
url: https://github.com/updatecli/updatecli.git
```
shows
```
=============================
REPORTS:
- EXAMPLE.YAML:
Sources:
Target:
Run Summary
===========
Pipeline(s) run:
* Changed:	0
* Failed:	0
* Skipped:	1
* Succeeded:	0
* Total:	1
```
and should return
```
=============================
REPORTS:
- EXAMPLE.YAML:
Run Summary
===========
Pipeline(s) run:
* Changed:	0
* Failed:	0
* Skipped:	1
* Succeeded:	0
* Total:	1
```
To test this pull request, you can run updatecli using the manifest mentioned above

fix: Report shouldn't show source and target if none were configured

---

pkg/core/pipeline/source/main.go

Fix #XXX
Empty changelog message shouldn't display source object even in debug mode. It had little value and is a risk for leaking information
```shell
go test
```

fix: Empty changelog message shouldn't display source object even in debug mode

---

updatecli/updatecli.d/golang.yaml

Fix broken updatecli manifest
With release 0.28.0, the resource "shell" used in a source must specify environment variable(s) inherited from the updatecli process
/

Add path env to golang updatecli manifest

---

pkg/plugins/resources/jenkins/main.go

Fix #789 
Historically we fetch Jenkins changelog from GitHub but it isn't the case anymore. This PR is especially needed as we automatically mention Github settings in IDE auto completion and documentation on https://www.updatecli.io/docs/plugins/resource/jenkins/
Nothing to test as it's not used anyway

Remove github dependency from jenkins plugin

---

cmd/apply.go
cmd/diff.go
cmd/prepare.go

Fix #788 
To test this pull request, you can run the following commands `updatecli diff` or `updatecli apply` with scm configuration. At the end of the run, we should still see content in /tmp/updatecli/
Enduser will have to clean the temporary directory on themself which is handle by the system anyway as mentioned @gionn

Don't clean temporary updatecli directory by default

---

cmd/root.go
pkg/core/cmdoptions/main.go

Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
Related to #803 and #813
This pull request introduces a new flag `--experimental`, available for ALL subcommands (like `--debug`).
This flag sets a global variable `cmdoptions.Experimental` so that any package can use it.
```shell
./dist/updatecli --debug --experimental diff --config ./updatecli/updatecli.d/updatecli.yaml
```
should print `Experimental mode enabled`.

feat: add a new 'experimental' flag

---

e2e/updatecli.d/success.d/source/gitTag.yaml
e2e/updatecli.d/warning.d/dockerimage.yaml
pkg/plugins/resources/dockerimage/source.go
pkg/plugins/resources/gitea/branch/source.go
pkg/plugins/resources/gitea/release/source.go
pkg/plugins/resources/gitea/tag/source.go
pkg/plugins/resources/githubrelease/source.go
pkg/plugins/resources/gittag/condition.go
pkg/plugins/resources/gittag/source.go
pkg/plugins/resources/gittag/target.go
pkg/plugins/utils/version/main.go
pkg/plugins/utils/version/semver.go

Requires #815 
Related to #803
Reverts #802 
Closes #810 
This PR reverts the behavior of #802 by default, but allow it to be used when the new `--experimental` from #815 is used.
It also adds a warning to end user when the parsed version is different than the original, which means there is `v` prefix that was dropped. 
The warning message (see below):
- Gives instructions to end user on how to edit their manifest if they need to keep the "dropping `v` prefix" and how to test it (by adding the `--experimental` flag)
- Is not shown if the experimental flag is enabled
```shell
$ go build -o dist/updatecli
```
Then
```shell
$ ./dist/updatecli diff --config ./updatecli/updatecli.d/venom.yaml
./dist/updatecli diff --config …
```

feat: revert #802 and use experimental to control the returned filtered version

---

pkg/core/pipeline/autodiscovery/main.go

In this pullrquest https://github.com/olblak/fleet-lab/pull/1, I noticed that the groupby wasn't correctly handle.
And the pipelineID was always the same no matter what

Fix: Autodiscovery groupBy correctly applied

---

e2e/updatecli.d/success.d/githubPullrequest.yaml
pkg/core/pipeline/pullRequests.go

Fix #836 
In release 0.30.0, Updatecli automatically detects which targets are related to a pullrequest spec, for generating the pullrequest body. 
So 
```
pullrequests:
jenkins:
title: Bump Jenkins Version to {{ source "jenkins" }}
kind: github
scmid: github2
targets:
- jenkins
```
becomes 
```
pullrequests:
jenkins:
title: Bump Jenkins Version to {{ source "jenkins" }}
kind: github
scmid: github2
```
But in the code I passed the wrong id value the pullrequest scmID instead of the pullrequets ID
I didn't detect this issue because in my tests environment, it's usually the same value.
```shell
go test
```

pullrequest correctly search linked targets based on pullrequestID

---

e2e/updatecli.d/success.d/githubPullrequest.yaml
pkg/plugins/resources/yaml/source.go

Spot while testing https://github.com/updatecli/updatecli/pull/838
This appears to be a regression where the source yaml didn't use the correct scmID
```shell
./bin/updatecli diff --config e2e/updatecli.d/success.d/githubPullrequest.yaml
```
/
This part should deserve better UT, but I don't really have the time atm

Fix: yaml source workdir relying on scm

---

.github/ISSUE_TEMPLATE/1-bug-report.yml
e2e/updatecli.d/success.d/maven.yaml
e2e/updatecli.d/warning.d/maven.yaml
pkg/plugins/resources/maven/condition.go
pkg/plugins/resources/maven/condition_test.go
pkg/plugins/resources/maven/main.go
pkg/plugins/resources/maven/main_test.go
pkg/plugins/resources/maven/source.go
pkg/plugins/resources/maven/source_test.go
pkg/plugins/resources/maven/utils.go
pkg/plugins/resources/maven/utils_test.go

The purpose of this Pullrequest is to mimic how Maven decides which repository to use when retrieving the latest version of an artifact by providing a list of repositories. Similarly to Maven, we fallback to Maven Central if we can't find any valid artifact.
This pullrequest is a requirement for https://github.com/updatecli/updatecli/pull/833
An example of the new `repositories` parameter:
```
sources:
org.mockito/mockito-core:
name: 'Get latest Maven Artifact version: "org.mockito/mockito-core"'
kind: maven
spec:
repositories:
- http://repo.jenkins-ci.org/public/
groupid: org.mockito
artifactid: mockito-core
```
While the current behavior with the singe repository hasn't been modified. I am deprecating the parameter `URL` as it has no added value …

Add new parameter "repositories" to Maven resource

---

updatecli/updatecli.d/golang.yaml
updatecli/updatecli.d/golangci-lint.yaml
updatecli/updatecli.d/updatecli.yaml
updatecli/updatecli.d/venom.yaml

Apparently Updatecli manifest here were too much outdated
```shell
go test
```

Fix updatecli golangconfig

---

.github/workflows/updatecli.yaml
updatecli/updatecli.d/golang.yaml

Fix broken Updatecli pipeline when bumping Golang major version
During Golang 1.19.1 update, I noticed that the Updatecli GA workflow went into a deadlock.
When Updatecli bump the major version of a Golang, the Golang version used by the workflow would update go.mod and then fail to clean dependencies as the Golang version used in an older one.
I don't see any downside to always use the latest Golang version available
```shell
go test
```

Always use the latest Go version available when updating the go.mod from Updatecli GA

---

e2e/updatecli.d/success.d/xml.yaml
pkg/plugins/resources/xml/condition.go
pkg/plugins/resources/xml/condition_test.go
pkg/plugins/resources/xml/main.go
pkg/plugins/resources/xml/source.go
pkg/plugins/resources/xml/source_test.go
pkg/plugins/resources/xml/target.go
pkg/plugins/resources/xml/target_test.go
pkg/plugins/resources/xml/utils.go
pkg/plugins/resources/xml/utils_test.go

Fix #XXX
While looking in https://github.com/updatecli/updatecli/pull/650
I noticed that while we should be able to support different path URL such as ["https://","http://","file://","absolutePath", "relativePath"], it wasn't the case anymore.
This pullrqeuest add e2e test on the xml resource + address the source/conditoin/target.
As similar pullrequest will come for the yaml resource as well
```shell
go test
```

fix:  Support different XML path format 

---

pkg/plugins/scms/github/main.go

Fix [862](https://github.com/updatecli/updatecli/issues/862)
After investigating for a while, I found that the problem is that shurcooL/githubv4 [expects a graphql url](https://github.com/shurcooL/githubv4/blob/234843c633fadff9694210ce7ab97948c9148a14/githubv4.go#L22).
Just adding the graphql path to the URL parameter doesn't work (as that same url is used to pull the repo), but just by appending /api/graphql to [the s.URL](https://github.com/updatecli/updatecli/blob/main/pkg/plugins/scms/github/main.go#L101) when initiating the client, fixes it.
Based on official [documentation](https://docs.github.com/en/enterprise-cloud@latest/graphql/guides/managing-enterprise-accounts#3-setting-up-insomnia-to-use-the-github-graphql-api-with-enterprise-accounts), the enterprise url for GraphQL is …

Add graphql path when creating client

---

e2e/updatecli.d/warning.d/autodiscovery/helmfile/example.1.yaml
pkg/core/pipeline/autodiscovery/main.go
pkg/plugins/autodiscovery/helmfile/dependencies.go
pkg/plugins/autodiscovery/helmfile/main.go
pkg/plugins/autodiscovery/helmfile/main_test.go
pkg/plugins/autodiscovery/helmfile/matchingRule.go
pkg/plugins/autodiscovery/helmfile/releases.go
pkg/plugins/autodiscovery/helmfile/testdata/helmfile.d/cik8s.yaml
pkg/plugins/autodiscovery/helmfile/utils.go
pkg/plugins/autodiscovery/helmfile/utils_test.go

Fix #409 
This pullrquest add the helmfile autodiscovery crawler.
By default it searches for all files matching ["*.yaml", "*.yml"] if the crawler identify the following pattern in the file 
```
repositories:
- ...
releases:
- ...
```
So it assumes that the repository used by a release is defined in the same file.
```shell
cd pkg/plugins/autodiscovery/helmfile
go test
./bin/updatecli diff --config e2e/updatecli.d/warning.d/autodiscovery/helmfile --experimental --debug
```
In order to be detected by Updatecli helmfile releases requires the following rules
1. A release and its repository must be located in the same file
2. A version must be specified for a release

Add Helmfile autodiscovery crawler

---

e2e/updatecli.d/warning.d/autodiscovery/fleet/git.yaml
e2e/updatecli.d/warning.d/autodiscovery/fleet/githubPullrequest.yaml
e2e/updatecli.d/warning.d/autodiscovery/helm/example.1.yaml
e2e/updatecli.d/warning.d/autodiscovery/maven/git.yaml
pkg/core/pipeline/autodiscovery/main.go
pkg/plugins/autodiscovery/fleet/main.go
pkg/plugins/autodiscovery/helm/main.go
pkg/plugins/autodiscovery/helmfile/main.go
pkg/plugins/autodiscovery/maven/main.go

As introduced on https://github.com/updatecli/updatecli/discussions/874
I find it very annoying that I have to disable all crawler if I want an autodiscovery manifest handle only one crawler
No default crawler when autodiscovery is used from manifest
To test this pull request, you can test the two following workflow:
```shell
./bin/updatecli manifest show --config e2e/updatecli.d/warning.d/autodiscovery/fleet --experimental 
./bin/updatecli manifest show --local-autodiscovery --experimental
go test
```

No default crawler when autodiscovery is used with manifest

---

.github/workflows/go.yaml

No need to install and check version of tools before they're really used. If a previous step fails, it avoid unnecessary downloads and executions.

chore: optimize steps order in `go` GitHub Action

---

pkg/plugins/scms/github/pullrequest.go
pkg/plugins/utils/truncate/main.go
pkg/plugins/utils/truncate/main_test.go

Fix #873 
Truncate long PR message to avoid `body is too long` error. 
```shell
go test -timeout 30s -run ^TestString$ github.com/updatecli/updatecli/pkg/plugins/utils/truncate
```
_No response_
_No response_

fix: truncate pull request body

---

pkg/core/pipeline/resource/main.go

chore: don't make `sources.name` mandatory in JSON Schema

---

e2e/updatecli.d/success.d/command.yaml
pkg/core/pipeline/condition/main.go
pkg/core/pipeline/resource/main.go
pkg/core/pipeline/source/main.go
pkg/core/pipeline/target/main.go

Align depends_on syntax with the current manifest convention.
This also remove the confusion introduce by jsonschema
```shell
go test
```

Deprecate depends_on in favor of dependson

---

updatecli/updatecli.d/golang.yaml
updatecli/updatecli.d/golangci-lint.yaml
updatecli/updatecli.d/updatecli.yaml
updatecli/updatecli.d/venom.yaml

Fix the venom pipeline until https://github.com/updatecli/updatecli/issues/803 is fixed
Run `updatecli manifest upgrade` to fix deprecated syntax
```shell
updatecli diff --config updatecli/updatecli.d 
```

Cleanup Updatecli manifest

---

pkg/plugins/utils/version/main.go

Fix #803 
This pullrequest fixes a long discussed issue where semantic versioning filter drops the prefix "v"
To test this pull request, you can use whatever manifest that use semver filter with a artifact version that contains a v such as `updatecli/updatecli.d/venom.yaml`

fix: semantic version filter drop 'v' prefix

---

pkg/plugins/scms/github/pullrequest.go

Fixes https://github.com/updatecli/updatecli/issues/866
```shell
gh repo clone timja/updatecli-test
cd updatecli-test
updatecli apply
echo 'abcd=1' > my-file.properties
updatecli apply
```
None that I can think of this seems like it was unnecessary, other code handles creating a new pull request if no open ones exist
https://github.com/updatecli/updatecli/issues/866#issuecomment-1280554325
I've raised a ticket with GitHub to get clarification

Remove "state": "OPEN" to fix updating of titles

---

pkg/core/pipeline/pullRequests.go

Fix 
```shell
go test
```
I intend to improve this pull request default title by including the name of what's updated, and maybe also the type.
Something like
> [updatecli] Bump `<name>` <helm chart|docker image|...> version to <source-output>
The easiest way I found to retrieve the name would be to use sources[0].name, implying the change of (jenkins infra) manifests (they almost all have a description in the `name` field)

fix(pullrequest): default title with the source output instead of its result '✔'

---

e2e/updatecli.d/success.d/csv.yaml
pkg/plugins/resources/csv/condition.go
pkg/plugins/resources/csv/condition_test.go
pkg/plugins/resources/csv/main.go
pkg/plugins/resources/csv/source.go
pkg/plugins/resources/csv/source_test.go
pkg/plugins/resources/csv/spec.go
pkg/plugins/resources/csv/target.go
pkg/plugins/resources/csv/target_test.go

As discussed on https://github.com/updatecli/updatecli/issues/942#issuecomment-1284561424
I realized that it would be super usefull to be able to do a multiple query combined with versionfilter on the csv resource
This pullrequest allows the following manifest to work 
```
sources:
name: Test Version filter
kind: csv 
spec:
files: 
- pkg/plugins/resources/csv/testdata/data.csv
query: ".[*].firstname"
versionfilter:
kind: regex
pattern: "^Jo"
```
```
#############################
#############################
SOURCES
=======
versionfilter
-------------
Searching for version matching pattern "^Jo"
✔ Value "John", found in file "/home/olblak/Projects/Updatecli/updatecli/pkg/plugins/resources/csv/testdata/data.csv", for key ".[*].firstname"'
default …
```

Allow multiple query combined with versionfilter to csv source

---

pkg/core/engine/main.go

I propose to load default crawlers, if we no valid pipeline could  be loaded.
Either because no valid manifest were provided by `--config` argument, or because no default configuration such as `updatecli.yaml` or `updatecli.d` could be found.
So if we run `updatecli diff` then it would display following output
```
Experimental Mode Enabled
+++++++++++
+ PREPARE +
+++++++++++
SCM repository retrieved: 0
WARNING: Default Autodiscovery crawlers enabled as no Updatecli configuration have been specified nor default configuration detected
++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++
#######################
#######################
HELM
=====
Manifest detected: 0
RANCHER FLEET
==============
Manifest detected: 0
MAVEN
======
Manifest detected: 0 …
```

Enable default autodiscovery if no valid configuration have been loaded

---

e2e/updatecli.d/success.d/toml.yaml
pkg/plugins/resources/toml/condition.go
pkg/plugins/resources/toml/condition_test.go
pkg/plugins/resources/toml/main.go
pkg/plugins/resources/toml/source.go
pkg/plugins/resources/toml/source_test.go
pkg/plugins/resources/toml/spec.go
pkg/plugins/resources/toml/target.go
pkg/plugins/resources/toml/target_test.go

As discussed on https://github.com/updatecli/updatecli/issues/942#issuecomment-1284561424
I realized that it would be super usefull to be able to do a multiple query combined with versionfilter on the toml resource
This pullrequest allows the following manifest to work 
Example 
```
sources:
ports:
name: Get sorted ports
kind: toml
spec:
file: pkg/plugins/resources/toml/testdata/data.toml
query: database.ports.[*]
versionfilter:
kind: semver
```
```
++++++++++++
+ PIPELINE +
++++++++++++
######################
######################
SOURCES
=======
ports
-----
Searching for version matching pattern "*"
✔ Value "8002", found in file "/home/olblak/Projects/Updatecli/updatecli/pkg/plugins/resources/toml/testdata/data.toml", for key "database.ports.[*]"' …
```

Allow multiple query combined with versionfilter to toml source

---

pkg/core/pipeline/targets.go

Fix https://github.com/updatecli/updatecli/issues/983
N/A
N/A
N/A
Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

Fix parent target execution

---

pkg/plugins/resources/dockerimage/condition.go
pkg/plugins/resources/dockerimage/main.go
pkg/plugins/resources/dockerimage/main_test.go

Fix #962
This PR introduces a new feature for the conditions of the resource `dockerimage`.
You can now specify a list of architectures instead of a single one, to simplify the manifests.
Not valid for sources (sources are not multi-valued) and targets (same). @olblak is there a way to tune the JSON schema to avoid it to proposes `architectures` for sources and targets?
```shell
make build test
```
Example:
```
checkTemurinDebianDockerImage:
kind: dockerimage
name: Check if the container image "eclipse-temurin:<lastVersion>-jdk-focal" is available
disablesourceinput: true
spec:
architectures:
- amd64
- arm64
- arm/v7
- s390x
image: eclipse-temurin
tag: '{{source "lastVersion" }}-jdk-focal'
```
returns:
```console
CONDITIONS: …
```

feat(dockerimage condition) supports a list of architectures

---

pkg/plugins/scms/github/main.go

The Github username parameters is not required
/

Do not set github username as required

---

ADOPTERS.md

Add SUSE Rancher as an adopter.
Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

Add SUSE Rancher as an adopter

---

e2e/updatecli.d/success.d/helmchart.yaml
pkg/plugins/resources/helm/changelog.go
pkg/plugins/resources/helm/condition.go
pkg/plugins/resources/helm/main.go
pkg/plugins/resources/helm/source.go
pkg/plugins/resources/helm/utils.go

This pullrequest allows to interact with Helm chart repositories index.yaml files using a file URI
Fix #1022 
```shell
./bin/updatecli diff --config e2e/updatecli.d/success.d/helmchart.yaml 
cp pkg/plugins/resources/helm
go test
```

[source][condition] Add file URI support for Helm resource

---

pkg/plugins/resources/file/condition.go
pkg/plugins/resources/file/condition_test.go

This PR removes the limitation for multiple files in conditions, fix related tests that are failure validation to allow more than one element in 'Files' and add a passing test for such scenario.
Fix https://github.com/updatecli/updatecli/issues/1026
```shell
cd pkg/plugins/resources/file
go test
```
Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

Remove limitation for multiple files in condition and fix tests

---

pkg/core/pipeline/action/main.go
pkg/core/pipeline/action/main_test.go

Fix #1035
When writing #990 , I introduced a minor bug where the warning message telling the user about using a kind of action that is deprecated.
I forgot to update the internal config state, so the processing of template triggered the message at least a 2nd time (or more...).
This PR adds the required unit test that fails with the `0.40.0` behavior.
```shell
go build -o ./dist/updatecli
sed '/version:/d' ./updatecli/updatecli.d/golang.yaml | wc -l
./dist/updatecli diff --config ./updatecli/updatecli.d/golang.yaml
```
result:
```text
./dist/updatecli diff --config ./updatecli/updatecli.d/golang.yaml
+++++++++++
+ PREPARE +
+++++++++++
Loading Pipeline "./updatecli/updatecli.d/golang.yaml"
WARNING: The `pullrequests` keyword …
```

fix(actions) print the deprecation action's kind warning only once

---

pkg/plugins/utils/gitgeneric/main.go

Gitea e2e started failing a week or two ago. 
I first noticed it on `try.gitea.io`.
I assumed it was due to that service being an unstable one so I moved the test to codeberg but the same issue appeared yesterday.
After some quick testing, I noticed that configuring http auth with no username/password would trigger errors
This PR only set http auth if both username&password are defined
```shell
./bin/updatecli diff --config e2e/updatecli.d/success.d/gitea/scm.yaml --debug --clean=true
```
Also did some testing with private repo and it works as expected
Similarly to the Github scm, I am wondering if the username is needed

Only set git auth if both username && password are specified

---

pkg/core/transformer/findSubMatch.go
pkg/core/transformer/replacer.go
pkg/core/version/main.go
pkg/core/version/main_test.go
updatecli/updatecli.d/golang.yaml
updatecli/updatecli.d/golangci-lint.yaml
updatecli/updatecli.d/updatecli.yaml
updatecli/updatecli.d/venom.yaml

**Opening for visibility but I'll merge once the test pass**
While updating the updatecli manifest to remove the deprecation warning.
I spotted a few minor issues
* A dev version of Updatecli shouldn't fail if binary version is unset . Instead we should a warning message
* I add a jsonschema tag
* Add a yaml omitempty to a deprecated parameter in transformer
/

Upgrade updatecli manifest

---

e2e/updatecli.d/success.d/githubrelease/condition.yaml
pkg/plugins/resources/githubrelease/condition.go
pkg/plugins/resources/githubrelease/main.go

Fix the GitHub release condition. The current code wasn't convenient to use as we needed to provide the appropriate versionfilter parameter. 
This pullrequest simplifies the githubrelease condition by removing the useless versionfilter.
While I am removing the versionfilter from the condition, existing manifest will still works
Fix #1084 
```shell
go test
```

Github Release condition shouldn't rely on versionfilter

---

pkg/plugins/resources/npm/condition_test.go
pkg/plugins/resources/npm/main.go
pkg/plugins/resources/npm/main_test.go
pkg/plugins/resources/npm/source_test.go
pkg/plugins/resources/npm/test_utils.go

Fix [1012](https://github.com/updatecli/updatecli/issues/1012)
Implement support of private npm registry
```shell
cp pkg/plugins/resources/npm
go test
```
When working with a private registry, it is necessary to specify the registry URL and an authorization token. These details can be provided in the resource specification and will be used as the default registry for connecting.
The resource code also checks for the presence of an `npmrc` file. This file contains information about scoped packages and can be specified in the `spec.NpmrcPath` field or defaults to `$HOME/.npmrc`.
The code will first establish the default registry by using the provided URL and token or defaulting to the npm registry. It then parses the `npmrc` …

Support for npm private registry

---

go.mod
pkg/core/jsonschema/main.go
pkg/core/jsonschema/main_test.go
pkg/core/pipeline/action/main.go
pkg/core/pipeline/autodiscovery/config.go
pkg/core/pipeline/autodiscovery/jsonschema.go
pkg/core/pipeline/autodiscovery/main.go
pkg/core/pipeline/condition/main.go
pkg/core/pipeline/scm/config.go
pkg/core/pipeline/source/main.go
pkg/core/pipeline/target/main.go

This pullrequest fix the jsonschema generated for the autodiscovery.
```shell
cd pkg/core/jsonschema/
go test
```
As of today, Updatecli codebase, relies on the function `New` to initiate object. it uses a map of plugin to define the behavior and due to that, the invopop/jsonschema requires  to implement the interface `func (ConfigType) JSONSchema() *jschema.Schema` to generate the jsonschema corresponding to the map of plugin. Hence the current pullrequest
Another approach would be to implement a json (un)marshaller for each config that works with plugins. If we get rid of the New function in favor of the unmarshaller approach, then we would also need to implement of yaml.
Based on my initial experimentation, it makes the …

Fix autodiscovery jsonschema

---

pkg/plugins/resources/gittag/target.go

Related to https://github.com/updatecli/updatecli/issues/1126
Git tag target shouldn't fail
```shell
go test
```

Git Tag target shouldn't fail

---

ADOPTERS.md

Add `Elastic` as adopter.
We are transitioning from adhoc to this model, so there will be more repositories with the automation. 
cc @kuisathaverat , you were the pioneer to use it in some of the projects at Elastic. 🙇

adopters: add Elastic

---

pkg/plugins/resources/yaml/condition_test.go
pkg/plugins/resources/yaml/source_test.go
pkg/plugins/resources/yaml/target.go
pkg/plugins/resources/yaml/target_test.go

https://github.com/updatecli/updatecli/pull/650 introduce a regression where a yaml target wouldn't correctly parse yaml key using dots
```shell
cd pkg/plugins/resources/yaml/
go test
```

yaml target should be able to parse key containing dots

---

.github/workflows/go.yaml
pkg/core/pipeline/autodiscovery/main.go
pkg/plugins/resources/yaml/main.go

Fix https://github.com/updatecli/updatecli/pull/1131
```shell
golangci-lint run
```

Bump golangci version to 1.51

---

pkg/core/pipeline/actions.go

When we run `updatecli apply --push=false`, at the moment Updatecli still tries to apply action such as opening github pullrequest. Obviously if local changes haven't been published then that operation fails as the branch do not exist on the remote location. This is especially confusing for newcomers as they think that the pipeline failed due to the pullrequest even though the root cause is usually at the git operation level.
```updatecli apply --config updatecli/updatecli.d/golangci-lint.yaml --push=false --clean=false --debug```
I often use --push=false to test the local behavior before changing the remote repository
<details><summary>Before fix Output</summary>
```
TARGETS
========
default
-------
DEBUG: stage: git-checkout
DEBUG: checkout branch …
```

Execute action in DRY_RUN mode if apply parameter --push=false is set

---

pkg/plugins/scms/git/main.go
pkg/plugins/scms/git/scm.go
pkg/plugins/scms/gitea/scm.go
pkg/plugins/scms/github/scm.go
pkg/plugins/utils/gitgeneric/main.go

Fix #1133 
Only execute git reset operation after a git clone and not anymore after each git checkout operation
```shell
go test
```
I hesitated to totally remove the git reset operation but decided to keep at the beginning of a pipeline run as an intermediary step.
This reduce the risk of working from a "none" clean directory and we can still disable this behavior in the future once we have the local scm fully implemented

Only git reset operation after a git clone

---

e2e/updatecli.d/success.d/yaml/duplicate.yaml
e2e/updatecli.d/success.d/yaml/noscm.yaml

Fix end to end tests
In https://github.com/updatecli/updatecli/pull/1187, I refactored a bit the end to end tests to focus either on scm and none scms situation. But because the tests depended on the main branch, I merged the change without waiting for green CI and I let mistake going through
```shell
./bin/updatecli diff --config e2e/updatecli.d/success.d/yaml/
```

remove scms mention from some of the yaml e2e tests

---

pkg/core/pipeline/target/main.go

Adding a little more information so users understand the impact of not being able to retrieve a source value in the target. 
relates to #1190

add more information for disableinputsource

---

pkg/plugins/resources/xml/condition.go
pkg/plugins/resources/xml/main.go
pkg/plugins/resources/xml/source.go
pkg/plugins/resources/xml/target.go
pkg/plugins/resources/xml/target_test.go

This pullrequest correctly handle XML file path according the different scenarios, relative path, path from scm, etc.
Fix #1210 
```shell
./bin/updatecli apply --config e2e/updatecli.d/success.d/xml.yaml --clean=true --push=false
cd pkg/plugins/resources/xml
go test .
```
* The source function received a workdir set to the current directory by default. This means we need additional code for each plugin to check the value of that workdir param. This behavior is confusing and should be handled in the "core" codebase

Correctly handle XML file path

---

pkg/plugins/resources/gitea/branch/main.go
pkg/plugins/resources/gitea/pullrequest/utils.go
pkg/plugins/resources/gitea/release/main.go
pkg/plugins/resources/gitea/tag/main.go

While working on the gitlab integration, I realize that I wasn't correctly handling pagination on gitea.
The reason is that during my tests, I have a lot less data on my gitea instance.
The consequence is that Updatecli wouldn't detect older information
```shell
go test
```

Correctly handle pagination for gitea api request

---

pkg/plugins/resources/gitlab/client/main.go
pkg/plugins/scms/gitlab/scm.go

don't prefix the gitlab url with the `https://` prefix if it is already there...

fix: gitlab url with https prefix

---

pkg/core/pipeline/action/main.go
pkg/core/pipeline/scm/config.go
pkg/core/pipeline/scm/main.go
pkg/plugins/resources/stash/branch/changelog.go
pkg/plugins/resources/stash/branch/condition.go
pkg/plugins/resources/stash/branch/main.go
pkg/plugins/resources/stash/branch/source.go
pkg/plugins/resources/stash/branch/target.go
pkg/plugins/resources/stash/client/main.go
pkg/plugins/resources/stash/pullrequest/create.go
pkg/plugins/resources/stash/pullrequest/main.go
pkg/plugins/resources/stash/pullrequest/utils.go
pkg/plugins/resources/stash/release/changelog.go
pkg/plugins/resources/stash/release/condition.go
pkg/plugins/resources/stash/release/main.go
pkg/plugins/resources/stash/release/source.go
pkg/plugins/resources/stash/release/target.go
pkg/plugins/resources/stash/tag/changelog.go
pkg/plugins/resources/stash/tag/condition.go
pkg/plugins/resources/stash/tag/main.go
pkg/plugins/resources/stash/tag/source.go
pkg/plugins/resources/stash/tag/target.go
pkg/plugins/scms/stash/main.go
pkg/plugins/scms/stash/scm.go
pkg/plugins/scms/stash/util.go

follow-up of https://github.com/updatecli/updatecli/pull/1233
👍

Add Bitbucket Server (Stash)

---

pkg/plugins/resources/go/language/main.go

By default the golang source plugin returns the wrong version because it uses the wrong version filtering rule
Following manifest should return 1.20.3 instead of 1.9.4
```shell
sources:
golang:
name: Get latest Golang version
kind: golang
```

Use semver for default Golang version filtering

---

pkg/plugins/autodiscovery/golang/matchingRule.go
pkg/plugins/autodiscovery/golang/matchingRule_test.go

Correctly handle golang autodiscovery matching rule
```shell
go test
```

fix golang autodiscovery matching rule

---

pkg/plugins/resources/yaml/main.go

I recently discovered that I could use multi line comment for jsonschema description field.
This pullrequest redesign the yaml parameter comment.
This is an attempt to see how it render both from the IDE and www.updatecli.io
This pullrequest is just some comment update

Reformat yaml comment

---

pkg/plugins/resources/dockerfile/target.go

While doing some test with the dockerfile autodiscovery, I noticed a regression in the dockerfile plugin resource.
Where the result is not set if nothing change 
```
TARGETS
========
registry.access.redhat.com/ubi9/ubi
-----------------------------------
✔ The line #12, matched by the keyword "FROM" and the matcher "registry.access.redhat.com/ubi9/ubi", is correctly set to "FROM registry.access.redhat.com/ubi9/ubi:9.2-489".
- - 
```
```shell
go test
```

Fix dockerfile target result in case of success

---

pkg/plugins/autodiscovery/helm/container.go

After additional thought we should detect a tagfilter if a versionfilter is provided
```shell
go test
```

reset tagfilter when helm autodiscovery rely on versionfilter

---

e2e/updatecli.d/success.d/maven.yaml
pkg/plugins/resources/jenkins/main.go
pkg/plugins/resources/jenkins/main_test.go
pkg/plugins/resources/maven/main.go
pkg/plugins/utils/mavenmetadata/main.go
pkg/plugins/utils/mavenmetadata/main_test.go
pkg/plugins/utils/mavenmetadata/types.go

Fix #1374 
```shell
cd pkg/plugins/utils/mavenmetadata
go test
./bin/updatecli diff --config e2e/updatecli.d/success.d/maven.yaml
```
I didn't bother adding support for Jenkins considering the time spent on this versus the usage and the benefit :) 
I may revisit this decision in the futur

Add versionfilter to maven resource

---

e2e/updatecli.d/warning.d/autodiscovery/maven/git.yaml
pkg/plugins/autodiscovery/maven/dependency.go
pkg/plugins/autodiscovery/maven/dependencyManagement.go
pkg/plugins/autodiscovery/maven/main.go
pkg/plugins/autodiscovery/maven/manifestTemplate.go
pkg/plugins/autodiscovery/maven/parentPomdependency.go
pkg/plugins/autodiscovery/maven/test/main_test.go
pkg/plugins/resources/xml/condition.go

* Fix minor xml message
* Allow Maven autodiscovery to override default version filter
```shell
go test
```

Allow Maven autodiscovery to override default version filter

---

pkg/plugins/resources/toml/spec.go
pkg/plugins/resources/toml/target.go
pkg/plugins/resources/toml/target_test.go

This PR proposes the support for missing keys when _targeting_ TOML files.
Use case:
* the key containing the version is in a Toml file but does not necessarily exist
* upon an update, we want this key to be created with the new version
Today, this fails because `updatecli` requires the key to be already there.
By adding `allowMissingKey: true` to the spec, the `target` won't fail but just create the key when missing. By default, `allowMissingKey` remains `false`, keeping the initial behavior (raising an error about the missing key).
Two tests have been added:
* checking the legacy behaviour (without `allowMissingKey`)
* checking the creation of the key when `allowMissingKey` is `true`
```shell
cp pkg/plugins/resources/toml
go …
```

Allowing the support for missing keys in Toml

---

pkg/plugins/scms/gitea/scm.go
pkg/plugins/scms/gitlab/scm.go

Similar to https://github.com/updatecli/updatecli/pull/1373
More information on https://github.com/updatecli/updatecli/pull/1373#issuecomment-1599229251
```shell
go test
```

[giteal][gitlab] git checkout must use `username` instead of `user`

---

.goreleaser.yml
Makefile

Due to https://goreleaser.com/deprecations/#archivesreplacements
It's not possible to build Updatecli.
I am also fixing various deprecation warnings
```shell
go test
```

fix: goreleaser deprecation

---

e2e/updatecli.d/warning.d/autodiscovery/golang/golangOnly.yaml
e2e/updatecli.d/warning.d/autodiscovery/golang/minorOnly.yaml
e2e/updatecli.d/warning.d/autodiscovery/golang/patchOnly.yaml

Recently I updated my fork of Updatecli, which apparently was used by the Golang e2e tests.
This PR updated the e2e test to use the org updatecli-test with a pin branch
```shell
go test
```

Pin golang autodiscovery e2e tests

---

pkg/core/pipeline/conditions.go
pkg/core/pipeline/sources.go
pkg/core/pipeline/targets.go

While working on Udash, I noticed the condition report data were incomplete.
This commit also removes declared but unused variable which were probably left over from another iteration

Fix condition report by using the correct variable

---

.github/actions/spelling/allow.txt
e2e/updatecli.d/success.d/hcl/noscm.yaml
e2e/updatecli.d/success.d/hcl/scm.yaml
go.mod
go.sum
pkg/core/pipeline/resource/main.go
pkg/plugins/resources/hcl/condition.go
pkg/plugins/resources/hcl/condition_test.go
pkg/plugins/resources/hcl/main.go
pkg/plugins/resources/hcl/main_test.go
pkg/plugins/resources/hcl/source.go
pkg/plugins/resources/hcl/source_test.go
pkg/plugins/resources/hcl/spec.go
pkg/plugins/resources/hcl/spec_test.go
pkg/plugins/resources/hcl/target.go
pkg/plugins/resources/hcl/target_test.go
pkg/plugins/resources/hcl/testdata/data.hcl

Adds support for hcl updating uses [minamijoyo/hcledit](https://github.com/minamijoyo/hcledit).
```shell
cd ./pkg/plugins/resources/hcl
go test
```
```shell
go build -o bin/updatecli && ./bin/updatecli diff --config e2e/updatecli.d/success.d/hcl/noscm.yaml
```

feat: add hcl resource plugin

---

pkg/core/udash/config_spec.go
pkg/core/udash/main.go

PKCE flow doesn't work from none interactive environment such as CI
This commit allows to skip the PKCE flow if an access token is provided via parameter
```shell
go test
```

Fix Udash login flow with access_token

---

pkg/core/udash/config_spec.go

Fix a regression where Updatecli will fail login because the config do not exist yet
Tested manually

Fix udash login when config doesn' exist yet

---

cmd/apply.go
cmd/docs.go

Fix #612 
```shell
go test
```

remove duplicated default value

---

.github/actions/spelling/allow.txt
pkg/core/config/template.go
pkg/core/config/template_test.go

* fix multiple values file specified
* fix absolute values file path specified
Fix #1403  #1415 #1253
```shell
cd pkg/core/config/
go test
./bin/updatecli diff --config manifest.yaml --values --values ../tmp/1.yaml --values ./2.yaml --values /tmp/3.yaml
```

allow to merge multiple values/secret files

---

pkg/plugins/resources/cargopackage/condition_test.go
pkg/plugins/resources/cargopackage/main.go
pkg/plugins/resources/cargopackage/source_test.go

Fix #1459
Make sure we can handle the cases when a package does not exists
To test this pull request, you can run check the following pipeline file
```yaml
name: Retrieve the latest Cargo Package Version
scms:
private-registry:
kind: git
spec:
url: "https://github.com/updatecli-test/fake-cargo-registry.git"
branch: "main"
conditions:
existing-package-private-reg:
name: Test if test-crate-2 0.1.0 exists on private registry
kind: cargopackage
scmid: private-registry
spec:
package: test-crate-2
version: 0.1.0
existing-package-not-existing-version-private-reg:
name: Test if test-crate-2 0.6.0 does not exists on private registry
kind: cargopackage
scmid: private-registry
failwhen: true
spec:
package: test-crate-2
version: 0.6.0
non-existing-package-private-reg:
name: Test if …
```

fix: handle non-existing cargo packages

---

e2e/updatecli.d/success.d/multiManifest.yaml
pkg/core/config/helper.go
pkg/core/config/main.go
pkg/core/config/main_test.go
pkg/core/config/testdata/updatecli.d/badJenkins.yaml
pkg/core/config/testdata/updatecli.d/jenkins.yaml
pkg/core/config/testdata/updatecli.d/multiJenkins.yaml
pkg/core/config/testdata/updatecli.d/multiTemplatedJenkins.tpl
pkg/core/config/testdata/values.yaml
pkg/core/engine/main.go

This pullrequest adds support for multiple Updatecli manifest into one YAML file.
Combined with the templating engine, this open the door to very advanced scenario **but** this also means **complex** manifest without jsonschema validation...
ps: worth mentioning by default if no pipelineid are defined, then they all share the same one 
Fix #961 
```shell
cd pkg/core/config/
go test
```
This feature allows to leverage the Golang templating with things like `range` such as in the following example
<details><summary>Simple manifest</summary>
values.yaml
```
names:
- "Manifest 1"
- "Manifest 2"
```
updatecli.yaml
```
{{- range $name := .names }}
---
name: {{ $name }}
sources:
default:
kind: shell
spec:
command: "echo 'Executing …
```

Support multiple manifest into one single file

---

.github/actions/spelling/allow.txt
e2e/updatecli.d/success.d/dockerdigest.yaml
pkg/plugins/resources/dockerdigest/condition.go
pkg/plugins/resources/dockerdigest/condition_test.go
pkg/plugins/resources/dockerdigest/main.go
pkg/plugins/resources/dockerdigest/source.go
pkg/plugins/resources/dockerdigest/source_test.go
pkg/plugins/resources/dockerdigest/target.go
pkg/plugins/utils/docker/main.go

Fix #999 
I had the param `hidetag` to hide the tag from the final digest such as 
```
sources:
ghcr.io:
name: "Get Latest Tag from ghcr"
kind: "dockerdigest"
spec:
image: "ghcr.io/updatecli/updatecli"
architecture: "amd64"
tag: "v0.35.1"
hidetag: true
```
```shell
cd pkg/plugins/resources/dockerdigest/
go test
```

Add Docker Image Tag to Docker Image Digest

---

cmd/manifest_show.go
pkg/core/config/main.go
pkg/core/config/variables.go
pkg/core/text/main.go
pkg/plugins/resources/file/condition.go
pkg/plugins/resources/file/target.go

Fix #954 
This pullrequest shows a diff between the raw manifest and the templated manifest when running 
```
updatecli manifest show --debug
```
```shell
./bin/updatecli manifest show --debug
```
<details><summary>Successful templating</summary>
```
~/Pr/Updatecli/updatecli │ on @a20269f7 *141 !3  ./bin/updatecli manifest show --config /tmp/updatecli.yaml --values /tmp/scm.yaml --debug
+++++++++++
+ PREPARE +
+++++++++++
Loading Pipeline "/tmp/updatecli.yaml"
DEBUG: Golang templating change detected:
- - - raw manifest
+++ templated manifest
@@ -1,3 +1,8 @@
scms:
default:
-{{ .scms.default | toYaml | indent 4}}
+    kind: github
+    spec:
+        owner: updatecli
+        repository: updatecli
+ …
```

Show templating diff from `updatecli manifest show --debug`

---

pkg/core/pipeline/target/main.go

By default use target name for commit message

---

pkg/plugins/resources/file/target.go

Related to #1472 
By default show file diff without requiring --debug 
<details><summary>New Console Output</summary>
```
TARGETS
========
download-url
------------
"docs/installation/other_inst_scenarios/install_epinio_on_rancher_desktop.md" updated with content "https://github.com/cert-manager/cert-manager/releases/download/v0.16.1/"
--- docs/installation/other_inst_scenarios/install_epinio_on_rancher_desktop.md
+++ docs/installation/other_inst_scenarios/install_epinio_on_rancher_desktop.md
@@ -47,7 +47,7 @@
```shell
-kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.3/cert-manager.yaml
+kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v0.16.1/cert-manager.yaml
"docs/tutorials/single-dev-workflow.md" updated with content …

Show file plugin target diff by default

---

pkg/plugins/autodiscovery/helm/main.go
pkg/plugins/autodiscovery/helm/test/main_test.go

Related to https://github.com/updatecli/updatecli/issues/1475
I don't have an better workaround that disabling this behavior by default...
```shell
cd pkg/plugins/autodiscovery/helm/test/
go test
```

by default disable Helm autodiscovery version increment

---

pkg/plugins/resources/gitlab/client/spec.go
pkg/plugins/resources/gitlab/mergerequest/create.go
pkg/plugins/resources/gitlab/mergerequest/main.go
pkg/plugins/resources/gitlab/mergerequest/spec.go
pkg/plugins/resources/gitlab/mergerequest/utils.go

While debugging #1531 I spotted a few issues
1. Several fields were considering required in the jsonschema which is not correct
2. I was missing more error message
3. I saw several mention of pullrequest even they are mergerequest on gitlab
Changes from this pullrequest do not affect the gitlab plugin behavior
The same kind of cleanup should probably be done for gitea and stash

Clean up GitLab mergerquest plugin

---

.github/workflows/go.yaml

At the moment golangci-lint is failing on all new PR, 
I can't reproduce the typecheck error locally, so I am switching the installation method to the binary one

Update golangci-lint installation method

---

pkg/plugins/autodiscovery/helm/main.go
pkg/plugins/autodiscovery/helm/test/main_test.go

Reverts updatecli/updatecli#1526
The multiple version bump is now fixed with https://github.com/updatecli/updatecli/pull/1541 available in 0.59.0
Which seems to work as expected on my projects so I am now reverting https://github.com/updatecli/updatecli/pull/1572
To come back to the initial situation

Revert "Disable Helm autodiscovery version increment by default"

---

.github/actions/spelling/allow.txt
e2e/updatecli.d/success.d/terraform/file/noscm.yaml
e2e/updatecli.d/success.d/terraform/file/scm.yaml
e2e/updatecli.d/success.d/terraform/lock/noscm.yaml
e2e/updatecli.d/success.d/terraform/lock/scm.yaml
e2e/updatecli.d/success.d/terraform/provider/noscm.yaml
e2e/updatecli.d/success.d/terraform/registry/default.yaml
pkg/core/pipeline/resource/main.go
pkg/plugins/resources/terraform/registry/changelog.go
pkg/plugins/resources/terraform/registry/changelog_test.go
pkg/plugins/resources/terraform/registry/condition.go
pkg/plugins/resources/terraform/registry/condition_test.go
pkg/plugins/resources/terraform/registry/main.go
pkg/plugins/resources/terraform/registry/registry.go
pkg/plugins/resources/terraform/registry/registry_test.go
pkg/plugins/resources/terraform/registry/source.go
pkg/plugins/resources/terraform/registry/source_test.go
pkg/plugins/resources/terraform/registry/spec.go
pkg/plugins/resources/terraform/registry/spec_test.go
pkg/plugins/resources/terraform/registry/target.go
pkg/plugins/resources/terraform/registry/versions.go

Adds terraform registry source, also adds an alias to hcl plugin as `terraform/file` for usability.
<details><summary>Registry Provider - terraform/provider</summary>
<p>
```yaml
name: Test Terraform Lock plugin resource from SCM
scms:
default:
kind: git
spec:
url: https://github.com/updatecli-test/jenkins-infra-aws.git
sources:
kubernetes:
name: Get version from registry
kind: terraform/registry
spec:
type: provider
namespace: hashicorp
name: kubernetes
targets:
update-file-from-source:
name: Update files content from source
kind: terraform/lock
sourceid: kubernetes
scmid: default
spec:
file: .terraform.lock.hcl
provider: hashicorp/kubernetes
platforms:
- linux_amd64
``` 
</p>
</details> 
<details><summary>Registry Module - terraform/file</summary>
<p>
```yaml
name: Test Terraform File …
```

feat(ci): add terraform registry source

---

.github/actions/spelling/allow.txt
pkg/plugins/resources/dockerdigest/source_test.go
pkg/plugins/resources/dockerimage/condition.go
pkg/plugins/resources/dockerimage/condition_test.go
pkg/plugins/resources/dockerimage/main.go
pkg/plugins/resources/dockerimage/main_test.go
pkg/plugins/resources/dockerimage/source.go
pkg/plugins/resources/dockerimage/source_test.go

Fix #1582
Moved away from setting remoteOptions for single architecture, as this was causing the multi conditions case to fail.
I can remove the tests if we don't want it to look up those images.
```shell
cd pkg/plugins/resources/dockerimage
go test
```
Mock the tests

fix: ensure docker image checks architecture

---

.github/actions/spelling/allow.txt
pkg/plugins/resources/dockerimage/condition.go
pkg/plugins/resources/dockerimage/condition_test.go
pkg/plugins/resources/dockerimage/main.go
pkg/plugins/resources/dockerimage/spec.go

Fix #1606
Added support for setting OS and variant, leave default as linux:
* `architecture: amd64`
* `architecture: windows/amd64`
* `architecture: linux/arm/v7`
NOTE: It isn't possible to set variant without os
Also added and fixed some logging.
```shell
cd pkg/plugins/resources/dockerimage/
go test
```
<details><summary>Details</summary>
<p>
```yaml
sources:
lastVersion:
kind: githubrelease
name: Get the latest Adoptium JDK11 version
spec:
owner: "adoptium"
repository: "temurin11-binaries"
token: '{{ requiredEnv "GITHUB_TOKEN" }}'
versionfilter:
kind: regex
pattern: "^jdk-11.(\\d*).(\\d*).(\\d*)(.(\\d*))+(\\d*)$"
transformers:
- trimprefix: "jdk-"
- replacer:
from: +
to: _
conditions:
checkTemurinAlpineDockerImage:
kind: …
```

feat: dockerimage support for setting os and variant

---

pkg/plugins/resources/dockerimage/main.go

Fix #1613 
The authentication options weren't defined if the plugin was used without specifying the architecture in the setting which is solved with the current pullrequest.
I tested this PR using 
```
sources:
default:
kind: dockerimage
spec:
image: ghcr.io/olblak/charts/upgrade-responder
conditions:
default:
kind: dockerimage
spec:
image: ghcr.io/olblak/charts/upgrade-responder
tag: v0.1.5
```
which is a private docker image
```shell
cd pkg/plugins/resources/dockerimage/
go test
```
/
/

fix: dockerimage correctly set auth if arch unspecified

---

pkg/plugins/resources/helm/target.go
pkg/plugins/resources/helm/utils.go

Fix #1614 
We only want to update the Chart metadata if the chart has been modified during the current target execution.
To make this process more idempotent in the context of a SCM, we could also check if the helm chart
has been modified during one of the previous target execution by comparing the current chart versus the one defined
on the source branch. But the code complexity induced by this check is probably not worth the effort today.
```shell
cd pkg/plugins/resources/helm/ 
go test
```

Run helm chart metadata update only on a changed target

---

pkg/core/pipeline/target/main.go
pkg/plugins/autodiscovery/terraform/test/main_test.go
pkg/plugins/utils/test/main.go

fix: https://github.com/updatecli/updatecli/actions/runs/6335541299/job/17208054420
When the tests for the Terraform autodiscovery plugins are executed, they don't necessarily generate manifests in the same order which leads to failing tests when we compare the result with expected results.
So this PR introduce a sort function that can be used during the test to ensure the expected manifest and generate manifests are sorted the same way.
```shell
pkg/plugins/autodiscovery/terraform/test/
while true; do GOFLAGS="-count=1" go test ./... && sleep 1; done;
```
This problem can also affects the other autodiscovery plugins so we may decided to update the expected result over there as well.

fix: sort terraform autodiscovery manifest during test

---

.github/workflows/spelling.yml

Reverts updatecli/updatecli#1640
It appears that [github.com/check-spelling/check-spelling@0.0.22](https://github.com/check-spelling/check-spelling/releases) is a pretty major release which I need to look into #988

Revert "chore(deps): Bump check-spelling/check-spelling from 0.0.21 to 0.0.22"

---

.github/actions/spelling/allow.txt
pkg/plugins/resources/helm/main.go
pkg/plugins/resources/helm/target.go

On Helm chart updates, provide the option to skip the packaging phase of the update. This provides the end user with two main benefits:
1. Users will be able to leverage `updatecli` to update the metadata on their chart(s) while leveraging other mechanisms to handle the actual packaging and publishing, such as the [chart-releaser-action](https://github.com/helm/chart-releaser-action) action.
2. When using the `helmchart` target with an `scmid` defined, the compressed binary files for the chart dependencies will not be committed into the repository.
**Note:** I spent some time looking in the existing tests, but didn't see an obvious way to test if files had been created on disk within the current paradigm. I'm open to suggestions or thoughts about how to  handle this though. What I can …

feat: add `skippackaging` option to helm target

---

pkg/plugins/resources/json/target.go

Fix #XXX
The message should be and the name of the file are inverted, so when you are not in dry-run mode you see something like :
```
key "release.version", from file "", /var/folders/rd/../update_channels.jsonupdated from "8.10.0" to "8.10.2"
```
that should be 
```
key "release.version", from file /var/folders/rd/../update_channels.json, updated from "8.10.0" to "8.10.2"
```
And in dry-run you see
```
key "release.version", from file "should be", /var/folders/rd/../update_channels.jsonupdated from "8.10.0" to "8.10.2"
```
that should be 
```
key "release.version", from file /var/folders/rd/../update_channels.json, should be updated from "8.10.0" to "8.10.2"
```
```yaml
title: Test JSON file
name: Test JSON file
scms: …
```

fix: messages are not in correct order

---

.github/actions/spelling/allow.txt
cmd/apply.go
cmd/compose.go
cmd/compose_apply.go
cmd/compose_diff.go
cmd/compose_show.go
cmd/diff.go
cmd/jsonschema.go
cmd/manifest_show.go
cmd/manifest_upgrade.go
cmd/prepare.go
cmd/root.go
cmd/show.go
go.mod
go.sum
pkg/core/compose/env_files.go
pkg/core/compose/environment.go
pkg/core/compose/file.go
pkg/core/compose/main.go
pkg/core/compose/main_test.go
pkg/core/compose/spec.go
pkg/core/compose/testdata/credentials.yaml
pkg/core/compose/testdata/update-compose.yaml
pkg/core/engine/manifest/main.go
pkg/core/engine/options.go
pkg/core/engine/schema.go
pkg/core/registry/pull.go

Fix #1622 
Doc https://github.com/updatecli/website/pull/1173
Requirements:
This pullrquest add the support for a new configuration that allows to "compose" multiple policies. 
A compose file looks like 
<details><summary>update-compose.yaml</summary>
```
#
configs:
default:
config:
- updatecli.d
values: 
- values.yaml
secrets:
- secrets.yaml
policies: 
- policy: ghcr.io/olblak/policies/updatecli:latest
- policy: ghcr.io/olblak/policies/golang:v2.1.1
- policy: ghcr.io/olblak/policies/readme:v0.1.3
```
</details>
This file can be used using one of the three following commands
* `updatecli compose diff` : similar to `updatecli diff` but for multiple policies at once
* `updatecli compose apply`: similar to `updatecli apply` but for multiple policies at once
* `updatecli compose show` : …

Add update compose command

---

.github/workflows/updatecli.yaml
updatecli/updatecli.d/golang/minor.yaml
updatecli/updatecli.d/golang/patch.yaml

Change Updatecli cronjob trigger from every 15min to every Friday at 12AM.
The current situation, increase notification, and exhaust our API limit very quickly
Trigger Updatecli on release event
Group All go mod update until https://github.com/updatecli/updatecli/issues is fixed

Group all go mod update

---

.github/workflows/release.yaml
.goreleaser.yml
Makefile

- Update for the release job
some updates to have the signing part working again and update some deprecated goreleaser flags
rehearsal: https://github.com/cpanato/updatecli/actions/runs/6493608351/job/17634895938 / https://github.com/cpanato/updatecli/releases/tag/v99.99.00

Update for the release job

---

README.adoc

- update readme for the verify checksum signatures

update readme for the verify checksum signatures

---

updatecli/updatecli.d/golang/golang.yaml
updatecli/updatecli.d/golang/major.yaml
updatecli/updatecli.d/golang/minor.yaml
updatecli/updatecli.d/golang/patch.yaml
updatecli/updatecli.d/golangci-lint.yaml
updatecli/updatecli.d/updatecli.yaml
updatecli/updatecli.d/venom.yaml

This pullrequest introduces various cleanup in Updatecli manifests
* Update Updatecli target title using conventional commit scope which are used for git commit title
* Remove go mod ignore rule now that Updatecli 0.63.0 correctly handle prerelease version for go dependencies autodiscovery
* Automate documentation update for cosign instruction suggested by @cpanato in https://github.com/updatecli/updatecli/pull/1686

chore: clean up Updatecli manifest

---

cmd/docs.go

Removing the time from the man page makes it easier to automate those page update.
When running `updatecli docs -d ./content/en/docs/commands` on github.com/updatecli/website, we can't easily differentiate if the man pages changed or if it's just the time without them.

chore: remove time from generated markdown man pages

---

cmd/root.go

Fix #1706
Compare the slice of arguments with an empty slice and a slice with one empty string. (credit @olblak)
```shell
cat > test.yml << EOF
name: test
pipelineid: test
sources:
one:
name: 'Check {{ $updateChannel }} channel'
kind: shell
spec:
command: echo 1
targets:
one:
name: 'Check {{ $updateChannel }} channel'
kind: shell
spec:
command: echo 1
EOF
go run . apply "" --config test.yml
```

fix: do not exit on empty arguments

---

cmd/manifest_push.go
pkg/core/compose/main.go
pkg/core/compose/spec.go
pkg/core/engine/configuration.go
pkg/core/engine/registry.go
pkg/core/engine/utils.go
pkg/core/registry/metadata.go
pkg/core/registry/pull.go
pkg/core/registry/pullpush_test.go
pkg/core/registry/push.go
pkg/core/registry/utils.go

While working on https://github.com/olblak/updatecli-policy-docusaurus
I spotted a few issues which I am collecting and fixing in this pullrequest
* fix: compose file should work without oci policies
* fix: latest tag shouldn't return the oldest tag 
* fix: used sanitize policy version for before push to ensure that v prefix are removed
* fix: various path scenarios when publishing policies
```shell
go test
```

various updatecli compose fixes

---

.github/actions/spelling/allow.txt
pkg/core/config/main.go

As discussed on Matrix, it's annoying having to specify the pipelineid.
I propose to remove this requiremement  to be optionnal.
Now instead of using the manifest file checksum, we'll use the manifest `name` to generate the pipelineid if it's undefined
More info on https://github.com/orgs/updatecli/discussions/1692
```shell
go test
```

fix: revert pipelineid requirement

---

.github/actions/spelling/allow.txt
cmd/manifest_push.go
cmd/root.go
go.mod
pkg/core/engine/registry.go
pkg/core/registry/pullpush_test.go
pkg/core/registry/push.go

By default, I don't want the command `updatecli manifest push` to overwrite an already published policy.
```shell
go test
```

feat: add manifest push --overwrite flag

---

go.mod
pkg/plugins/resources/dockerdigest/condition_test.go
pkg/plugins/resources/dockerdigest/source.go
pkg/plugins/resources/dockerdigest/source_test.go
updatecli/updatecli.d/golang/major.yaml
updatecli/updatecli.d/golang/minor.yaml
updatecli/updatecli.d/golang/patch.yaml

Fix #1603
<details><summary>updatecli.yaml</summary>
```
sources:
noarch:
name: "Get Digest for docker image updatecli/updatecli:v0.64.1"
kind: "dockerdigest"
spec:
image: "ghcr.io/updatecli/updatecli"
tag: "v0.64.1"
amd64:
name: "Get Digest for docker image updatecli/updatecli:v0.64.1"
kind: "dockerdigest"
spec:
image: "ghcr.io/updatecli/updatecli"
tag: "v0.64.1"
architecture: amd64
arm64:
name: "Get Digest for docker image updatecli/updatecli:v0.64.1"
kind: "dockerdigest"
spec:
image: "ghcr.io/updatecli/updatecli"
tag: "v0.64.1"
architecture: arm64
```
</details>
```shell
cd pkg/plugins/resources/dockerdigest/ 
go test
```

feat: support for pinning docker digests by image config

---

pkg/core/engine/configuration.go
pkg/core/engine/configuration_test.go
pkg/core/engine/testdata/defaultManifestDirname_multiple/updatecli.d/test.yaml
pkg/core/engine/testdata/defaultManifestDirname_multiple/updatecli.d/test2.yaml
pkg/core/engine/testdata/defaultManifestDirname_multiple_failure/updatecli.d/failure.yaml
pkg/core/engine/testdata/defaultManifestDirname_multiple_failure/updatecli.d/test.yaml
pkg/core/engine/testdata/defaultManifestDirname_single/updatecli.d/test.yaml
pkg/core/engine/testdata/defaultManifestFilename/updatecli.yaml

Fix #1720
- Update LoadConfigurations to add error report
- Add LoadCongifurations tests
```shell
cd  pkg/core/engine/
go test
```
Was done slightly differently that suggested in #1720 as `e.Reports` was available appended rather than charging the return.

fix: for muliple pipelines report failure to load

---

pkg/core/engine/configuration.go

Fix #1722
Previously I was only loading the default manifest if no arguments were provided. 
Instead I want to load default manifest, only if none were specified
/

fix: correctly load default Updatecli manifest

---

e2e/updatecli.d/deprecated.d/json.yaml
e2e/updatecli.d/deprecated.d/transformers.yaml
e2e/updatecli.d/success.d/transformers.yaml
e2e/venom.d/test_skipped_targets.yaml
pkg/core/pipeline/conditions.go
pkg/core/pipeline/sources.go
pkg/core/pipeline/targets.go
pkg/core/reports/main.go
pkg/core/result/condition.go

Reverts updatecli/updatecli#1715

Revert "fix: pipeline without target always returned Skipped"

---

.github/actions/spelling/allow.txt
e2e/updatecli.d/success.d/dockerfile/Dockerfile
e2e/updatecli.d/success.d/dockerfile/Dockerfile.nanoserver
e2e/updatecli.d/success.d/dockerfile/Dockerfile.windowscore
e2e/updatecli.d/success.d/dockerfile/dockerfile.yaml
pkg/plugins/resources/dockerfile/condition.go
pkg/plugins/resources/dockerfile/condition_test.go
pkg/plugins/resources/dockerfile/main.go
pkg/plugins/resources/dockerfile/main_test.go
pkg/plugins/resources/dockerfile/target.go
pkg/plugins/resources/dockerfile/target_test.go

This PR adds the support of multiple files for the resources of kind `dockerfile` (conditions and targets).
Use cases:
- It is an additional feature to help for #1026.
- Also, on the Jenkins project, we have cases were we want to update the same instruction to multiple files: https://github.com/jenkinsci/docker-agent/blob/1182cad9d14ece000ab38433eee05daf1872a993/updatecli/updatecli.d/remoting.yaml#L37-L81
```shell
cd pkg/plugins/resources/dockerfile
go test
```
Please note that a new e2e test as added for `dockerfile` which tests the current `file` (for non regression) and the new `files`.
I've tested this E2E test locally with a `diff` and an `apply`. The only untested part is when using with an SCM.
Using autodiscovery would …

feat(dockerfile) support multiple files

---

.github/actions/spelling/allow.txt
pkg/core/pipeline/action/main.go
pkg/core/pipeline/actions.go
pkg/core/reports/action.go

Fix #1717 
Well I don't see how to test this feature without taking the risk of conflicting with the GitHub Action environment used to test Updatecli so I am just doing manual testing at this stage.
We must use an Updatecli that need to change something
```shell
export GITHUB_ACTION="true" 
export GITHUB_SERVER_URL="https://github.com" 
export GITHUB_REPOSITORY="foo/bar" 
export GITHUB_RUN_ID="1658821493" 
./bin/updatecli diff --config updatecli/updatecli.d/venom.yaml --debug
```
Please note ` <a href="https://github.com/foo/bar/actions/runs/1658821493">GitHub Action pipeline link</a>` in the console output
<details><summary>Console Output</summary>
```
DEBUG: The expected action would have the following information:
|	
|	##Title:
|	ci: bump Venom version to v1.0.1
|	
|	
|	##Report:
|	
| …
```

feat(action): show CI url in pullrequest body

---

pkg/core/engine/autodiscovery.go

Well minor fix, when autodiscovery groupby is not defined.

fix(autodiscovery): fix default autodiscovery action title

---

.github/actions/spelling/allow.txt
e2e/updatecli.d/warning.d/autodiscovery/updatecli/git.yaml
pkg/core/pipeline/autodiscovery/main.go
pkg/plugins/autodiscovery/updatecli/main.go
pkg/plugins/autodiscovery/updatecli/manifestTemplate.go
pkg/plugins/autodiscovery/updatecli/matchingRule.go
pkg/plugins/autodiscovery/updatecli/matchingRule_test.go
pkg/plugins/autodiscovery/updatecli/policies.go
pkg/plugins/autodiscovery/updatecli/test/main_test.go
pkg/plugins/autodiscovery/updatecli/test/testdata/website/update-compose.yaml
pkg/plugins/autodiscovery/updatecli/utils.go
pkg/plugins/autodiscovery/updatecli/utils_test.go

This pullrequest add a new autodiscovery plugin for Updatecli compose file
```shell
cd pkg/plugins/autodiscovery/updatecli/
go test ./...
./bin/updatecli diff --config e2e/updatecli.d/warning.d/autodiscovery/updatecli --experimental
```
As already explained in https://github.com/updatecli/updatecli/issues/1709, because Updatecli are OCI artifacts we can use the dockerimage and dockerdigest plugin but console output feels a bit wrong because it keeps mentioning "docker" and Updatecli policies are not docker images

feat(autodiscovery/updatecli): Add updatecli compose autodiscovery

---

.github/actions/spelling/allow.txt
e2e/updatecli.d/warning.d/autodiscovery/helm/example.1.yaml
pkg/plugins/autodiscovery/helm/container.go
pkg/plugins/autodiscovery/helm/dependencies.go
pkg/plugins/autodiscovery/helm/matchingRule.go
pkg/plugins/autodiscovery/helm/matchingRule_test.go

Fix #1743 
This pullrequest allows more advance ignore/only rules.
It's now possible to use `helm dependency` and `container` in the matching rule
For example 
<details><summary>Only Update dependency `s3gw` in chart `chart/epinio` using version constraint</summary>
```
autodiscovery:
scmid: epinio
crawlers:
helm:
only:
- path: chart/epinio
dependencies:
"s3gw": ">1.0.0"
``` 
</details>
<details><summary>Only Update dependency `s3gw` in chart `chart/epinio` without version constraint</summary>
```
autodiscovery:
scmid: epinio
crawlers:
helm:
only:
- path: chart/epinio
dependencies:
"s3gw": ""
``` 
</details>
<details><summary>Only Update both dependency `s3gw` in chart `chart/epinio` using version constraint and container "longhorn/upgrade-responder"</summary>
```
autodiscovery:
scmid: …
```

feat(autodiscovery/helm) allow advanced ignore/only rule

---

e2e/updatecli.d/warning.d/autodiscovery/npm/npm.yaml
pkg/plugins/autodiscovery/npm/dependency.go
pkg/plugins/autodiscovery/npm/matchingRule.go
pkg/plugins/autodiscovery/npm/matchingRule_test.go

Fix #1663 
Similar to #1752 
```shell
cd pkg/plugins/autodiscovery/helm/ 
go test ./...
/bin/updatecli diff --config e2e/updatecli.d/warning.d/autodiscovery/npm/npm.yaml  --experimental --debug
```

feat(autodiscovery/npm): allow advanced ignore/only rule

---

.github/actions/spelling/allow.txt
e2e/updatecli.d/warning.d/autodiscovery/maven/git.yaml
pkg/plugins/autodiscovery/maven/dependency.go
pkg/plugins/autodiscovery/maven/dependencyManagement.go
pkg/plugins/autodiscovery/maven/matchingRule.go
pkg/plugins/autodiscovery/maven/matchingRule_test.go
pkg/plugins/autodiscovery/maven/parentPomdependency.go

Related #1753 
```shell
cd pkg/plugins/autodiscovery/maven/
go test ./...
./bin/updatecli diff --config e2e/updatecli.d/warning.d/autodiscovery/maven/git.yaml --experimental
```

feat(autodiscovery/maven): allow advanced ignore/only rule

---

pkg/plugins/scms/git/main.go
pkg/plugins/scms/git/main_test.go
pkg/plugins/scms/git/scm.go
pkg/plugins/scms/gitea/main.go
pkg/plugins/scms/gitea/scm.go
pkg/plugins/scms/github/main.go
pkg/plugins/scms/github/scm.go
pkg/plugins/scms/gitlab/main.go
pkg/plugins/scms/gitlab/scm.go
pkg/plugins/scms/stash/main.go
pkg/plugins/scms/stash/scm.go
pkg/plugins/utils/gitgeneric/branch_test.go
pkg/plugins/utils/gitgeneric/main.go
pkg/plugins/utils/gitgeneric/main_test.go

Fix #[1732](https://github.com/updatecli/updatecli/issues/1732)
If will allow to define if the submodule need to be fetched or not when a repository is initialised.
```shell
pushd pkg/plugins/scms
go test
popd
pushd pkg/plugins/utils/gitgeneric
go test
popd
```

feat(git): allow to decide if we want to fetch submodules or not

---

pkg/plugins/resources/file/condition.go
pkg/plugins/resources/file/main.go
pkg/plugins/resources/file/source.go
pkg/plugins/resources/file/target.go

Fix #1765 
```shell
go test
```

fix(file): ignore searchpattern not found when used with matchpattern

---

.github/actions/spelling/allow.txt
e2e/updatecli.d/success.d/http.yaml
pkg/core/pipeline/resource/main.go
pkg/plugins/resources/cargopackage/spec.go
pkg/plugins/resources/file/condition.go
pkg/plugins/resources/updateclihttp/condition.go
pkg/plugins/resources/updateclihttp/condition_test.go
pkg/plugins/resources/updateclihttp/errors.go
pkg/plugins/resources/updateclihttp/main.go
pkg/plugins/resources/updateclihttp/main_test.go
pkg/plugins/resources/updateclihttp/source.go
pkg/plugins/resources/updateclihttp/source_test.go
pkg/plugins/resources/updateclihttp/spec.go
pkg/plugins/resources/updateclihttp/target.go

Implements #268
This PR introduces a new resource of type `http` with source and condition capability.
The initial UX proposal has been updated to ensure separation between source and condition are easier (see the E2E test).
Here is a "complete reference example":
```
sources:
getWithCustomRequest:
kind: http
spec:
url: https://repo.jenkins-ci.org/releases/org/jenkins-ci/main/jenkins-war/maven-metadata.xml
request:
headers:
Authorization: 'Bearer Token'
Accept: 'application/xml'
verb: GET
conditions:
checkWithCustomRequest:
kind: http
sourceid: getJenkinsWarArtifactMetadatas
spec:
url: https://repo.jenkins-ci.org/releases/org/jenkins-ci/main/jenkins-war/maven-metadata.xml
request:
headers:
Authorization: 'Bearer Token'
Accept: 'application/xml'
verb: HEAD
responseasserts:
statuscode: 302 …
```

feat: introduces a new resource "http" (source only)

---

e2e/updatecli.d/warning.d/autodiscovery/fleet/git.yaml
e2e/updatecli.d/warning.d/autodiscovery/fleet/githubPullrequest.yaml

I decided to move https://github.com/olblak/fleet-lab.git private so I created a small copy on https://github.com/updatecli-test/fleet-lab.git

fix: update fleet git repository used for e2e test

---

.github/actions/spelling/allow.txt
Makefile
pkg/core/compose/main_test.go
pkg/core/pipeline/resource/main.go
pkg/core/pipeline/target/main.go
pkg/core/registry/pullpush_test.go
pkg/plugins/resources/gitbranch/main.go
pkg/plugins/resources/updateclihttp/target.go

While working on #1775 , caught a few minor things which I've put in this PR.
I tried to split each one on distinct commit in case we need to NOT add all (or if you want me to split in distinct PRs as well : I don't mind).
Tl;DR;
- Unit ("short") tests should not be requiring Docker Engine
- Some integration tests require Docker Engine: we should fail fast when Docker is not present and running
- Tests doing assertions with `/tmp` must us the `os.TmpDir()` to ensure all contributors can have these tests executed with success on their operating system
- Old validation error message referencing `scmID` instead of `scmid`
- A fix on target commits which are trying to access an undefined field (fixup of #412 )
```shell
make tests …
```

chore(tests) test and lint fixes

---

pkg/core/pipeline/condition/main.go
pkg/core/pipeline/conditions.go
pkg/core/pipeline/source/main.go
pkg/core/pipeline/sources.go
pkg/core/pipeline/target/main.go
pkg/core/pipeline/targets.go

While reviewing https://github.com/updatecli/updatecli/pull/1782 I noticed that if a target is skipped or in a fail state, then the report name is not correctly show up.
There were situation where the function that update the report wasn't reach
To test this pull request, you can run the following commands to the correct output:
```shell
./bin/updatecli diff --config e2e/updatecli.d/success.d/command.yaml 
```
<details><summary>Console output - Before</summary>
```
REPORTS:
⚠ Test Various target scenario:
Source:
✔ [1] Should be succeeding
Condition:
✔ [1] Should be succeeding
Target:
✔ [1] Should be succeeding
⚠ [5] Should be succeeding and report change
- [6] 
✔ [7] Should be run
```
</details>
<details><summary>Console output - After</summary>
```
REPORTS: …
```

fix: always set report name

---

.github/workflows/add_issue_to_project.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/go.yaml
.github/workflows/release-drafter.yml
.github/workflows/release.yaml
.github/workflows/spelling.yml
.github/workflows/typos.yaml
.github/workflows/updatecli.yaml

Was looking at the [scorecard](https://api.securityscorecards.dev/projects/github.com/updatecli/updatecli) and saw simple enough fix. 
Update token permissions to be [least privilege](https://github.com/ossf/scorecard/blob/0276a7cd7284e077f22b50208345201485029fbd/docs/checks.md#token-permissions).
<details><summary>Scorecard Details</summary>
<p>
```json
{
"name": "Token-Permissions",
"score": 0,
"reason": "detected GitHub workflow tokens with excessive permissions",
"details": [
"Warn: no topLevel permission defined: .github/workflows/add_issue_to_project.yaml:1",
"Warn: no topLevel permission defined: .github/workflows/codeql-analysis.yml:1",
"Warn: no topLevel permission defined: .github/workflows/go.yaml:1",
"Warn: no topLevel permission defined: …
```

chore(ci): update workflow permissions to be least privilege

---

updatecli/updatecli.d/golang/minor.yaml

Well I am giving another attempt at open minor version update individually as the current approach doesn't work 
https://github.com/updatecli/updatecli/pulls

deps: don't group go module minor update

---

.github/workflows/updatecli.yaml

It doesn't make sense to run updatecli for push and pullrequest targeting another branch than the main one

chore: only run updatecli on targeted branch main

---

pkg/plugins/resources/file/main.go

Fix a comment that break the generated doc
See [doc](https://www.updatecli.io/docs/plugins/resource/file/#_parameters) for `forcecreate`

Fix comment that break the generated doc

---

pkg/plugins/autodiscovery/helm/dependencies.go
pkg/plugins/autodiscovery/helm/test/testdata-3/chart/sample/Chart.yaml

While testing Updatecli on https://github.com/rancher/partner-charts 
I noticed a lot of failure due to chart relying on local dependencies such as https://github.com/rancher/partner-charts/blob/e1e19c33fc319281e60f74e36103979d120bdac4/charts/trilio/k8s-triliovault-operator/Chart.yaml#L11
I think it's better to ignore them until figure out the goal of specifying a dependency version...
```shell
cd pkg/plugins/autodiscovery/helm/test/ 
go test
```

feat(helm): Helm Autodiscovery ignore local dependencies

---

pkg/plugins/resources/stash/client/main.go

PR plugins doesn't support BasicAuth even though Username is provided.
I have no idea to test this module. I have tested manually over a bitbucket server.
add BasicAuth support to the other plugins

feat(scm): add BasicAuth to stash

---

e2e/updatecli.d/success.d/autodiscovery/maven/git.yaml

Apparently the maven dependency used in e2e has been removed
```shell
updatecli diff --config e2e/updatecli.d/success.d/autodiscovery/maven 
```

fix: maven autodiscovery e2e test

---

pkg/core/pipeline/condition/main.go
pkg/core/pipeline/condition/main_test.go

Fix #1849 
```shell
cd pkg/core/pipeline/condition/
go test
```

fix: successful condition combined with failwhen

---

pkg/core/registry/pull.go

This pullrequest add some basic caching by checking a policy directory already exist before pulling it from the registry.
Because the policy path contains the policy checksum which correspond to a version such as:
```/tmp/updatecli/store/41c2af6a10da1f4b4b91717ebaa4659332dd3d7107919c494c71f1f618aeaad8/updatecli.d```
We shouldn't have collision between the same policy with different version.
I tested this pullrequest manually on [github/website](https://github.com/updatecli/website) by running 
`../updatecli/bin/updatecli compose diff -f update-compose.yaml --experimental --debug`
We could also have some caching based on the time such pull the policy if the local directory is older than one day but considering that policy path contains a checksum, I don't think it's really necessary

feat: cache updatecli policies

---

pkg/plugins/resources/terraform/lock/main.go

This enables support for opentofu for lock files.
The provider already supported providing full provider names ex: `registry.opentofu.org/hashicorp/hcp`, but the hostname wasn't parsed onto the lock client (Which defaults to `registry.terraform.io`). By passing this on it adds support for opentofu with very little changes.
Part of: https://github.com/updatecli/updatecli/issues/1861
```shell
go test ./pkg/plugins/resources/terraform/lock/
```
Also tested with existing terraform project.
```shell
go build -o ./bin/updatecli
cd ../../terraform-project
tofu init  # which updates lock file with registry.opentofu.org
../../bin/updatecli diff
```
Then adding the hostname to the provider:
```yaml
targets:
provider:
name: 'Bump …
```

feat(terraform/lock): parse provider hostname onto lock download client

---

pkg/plugins/autodiscovery/helm/dependencies.go
pkg/plugins/autodiscovery/helm/test/testdata-3/chart/sample/Chart.yaml

Fix #1876 
```shell
cd pkg/plugins/autodiscovery/helm/test/ 
go test
```

fix: helm autodiscovery should ignore subcharts

---

cmd/manifest_init.go
cmd/root.go
pkg/core/engine/scaffold.go
pkg/core/scaffold/changelog.go
pkg/core/scaffold/config.go
pkg/core/scaffold/main.go
pkg/core/scaffold/main_test.go
pkg/core/scaffold/policy.go
pkg/core/scaffold/readme.go
pkg/core/scaffold/values.go

This pullrequest adds a new command `updatecli manifest init .` to scaffold a new policy.
In the current state, it comes with zero customization and creates the following files:
* `README.md` which contains the policy documentation
* `Policy.yaml` that contains the policy metadata
* `values.d/default.yaml` which contains basic scm setting
* `updatecli.d/default.yaml` which is a placeholder for the first manifest
* `CHANGELOG.md` which contains a template to provide policy changelog information
```shell
bin/updatecli manifest init /tmp/test
ls /tmp/test
```
I would like to provide some form of input

feat: add a command to scaffold a new Policy

---

pkg/plugins/resources/dockerimage/source_test.go
pkg/plugins/utils/version/filter.go

Fix #1888 
```shell
cd pkg/plugins/resources/dockerimage/
go test
```

fix: panic error in dockerimage resource

---

pkg/core/scaffold/config.go
pkg/core/scaffold/main.go
pkg/core/scaffold/main_test.go
pkg/core/scaffold/policy.go
pkg/core/scaffold/values.go

This pullrequest replaces generate the default values file using `values.yaml` instead of `values.d/default.yaml`.
In the process I also renamed a few variable to be more consistent with other similar variables.
A scaffolded policy looks like 
```
.
├── CHANGELOG.md
├── Policy.yaml
├── README.md
├── updatecli.d
│   └── default.yaml
└── values.yaml
```
```shell
cd pkg/core/scaffold/
go test .
./bin/updatecli manifest init /tmp/test2/
```

fix(scaffold): use default values.yaml

---

pkg/plugins/resources/helm/source.go

Fix #1892
reverse the order of listing the helm chart versions from the index file
1- build the code
2- run the following source
```
sources:
jenkins:
kind: helmchart
spec:
url: https://charts.jenkins.io
name: jenkins
versionfilter:
kind: "regex"
```
OR
```
sources:
jenkins:
kind: helmchart
spec:
url: https://charts.jenkins.io
name: jenkins
versionfilter:
kind: "latest"
```
you should see that source has fetched the latest version

Fix listing helm chart versions

---

pkg/plugins/resources/json/target.go

While investigating https://github.com/updatecli/updatecli/issues/1590#issuecomment-1908283071
I discovered that the json target plugin combined with a scm was broken.
It's scenario difficult to test so I missed when for some reason the plugin stops returning the list of files to commit. 
I also took the opportunity to apply the following improvement
* When updating files, we now show each description, one per line
* When used with a scm, the log output see the original file and 
To test this pull request, I used the following manifest
```
scms:
default:
kind: github
spec:
owner: updatecli-test
repository: kwctl
branch: main
token: '{{ requiredEnv "GITHUB_TOKEN"}}'
username: "olblak"
user: '{{ requiredEnv "GITHUB_ACTOR"}}'
email: "me@olblak.com"
sources:
default:
kind: jenkins
targets: …
```

fix: json target when combined with scm

---

pkg/core/text/main.go

This ensures that when a line is replaced if the value is shorter than the existing line the remaining values are not left in the buffer.
Fix #1915
```shell
cd pkg/plugins/resources/file
go test
```
```yaml
targets:
updateSyncServiceVersion:
name: Bump Sync Service version
kind: file
disablesourceinput: true
spec:
file: file.txt
line: 1
content: org.alfresco.services.sync:service-sync:${ARTIFACT_VERSION:-5.0.0-A13}:jar
updateDeviceSyncRepoVersion:
name: Bump Device Sync Repo version
kind: file
disablesourceinput: true
spec:
file: file.txt
line: 2
content: org.alfresco.services.sync:alfresco-device-sync-repo:${ARTIFACT_VERSION:-5.0.0-A13}:amp
```
```text
org.alfresco.services.sync:service-sync:${ARTIFACT_VERSION:-5.0.1-SNAPSHOT} …
```

fix: WriteLineToFile truncates file when opening

---

pkg/plugins/autodiscovery/updatecli/main.go
pkg/plugins/autodiscovery/updatecli/policies.go
pkg/plugins/autodiscovery/updatecli/test/main_test.go
pkg/plugins/autodiscovery/updatecli/utils_test.go

Allows to override the default file "update-compose.yaml" used by the updatecli autodiscovery 
```shell
pkg/plugins/autodiscovery/updatecli/
go test
pkg/plugins/autodiscovery/updatecli/test
go test
```

feat: Allow to override updatecli autodiscovery files

---

.github/actions/spelling/allow.txt
e2e/updatecli.d/success.d/conditionalTarget.yaml
pkg/core/config/main.go
pkg/core/pipeline/conditions.go
pkg/core/pipeline/main.go
pkg/core/pipeline/target/main.go
pkg/core/pipeline/targets.go

Fix #1385 
Allow to conditionally execute target.
if `disablecondition` is true then we ignore condition result for that target if `conditionids` has at least one valid `conditionid` then we only monitor that condition result
```shell
./bin/updatecli diff --config e2e/updatecli.d/success.d/conditionalTarget.yaml
```
<details><summary>Command Output</summary>
```
/bin/updatecli diff --config e2e/updatecli.d/success.d/conditionalTarget.yaml
+++++++++++
+ PREPARE +
+++++++++++
Loading Pipeline "e2e/updatecli.d/success.d/conditionalTarget.yaml"
WARNING: Updatecli binary version is unset. This means you are using a development version that ignores manifest version constraint.
SCM repository retrieved: 0 …
```

feat: Add conditional Target

---

pkg/plugins/scms/git/scm.go
pkg/plugins/scms/gitea/scm.go
pkg/plugins/scms/github/scm.go
pkg/plugins/scms/gitlab/scm.go
pkg/plugins/scms/stash/scm.go

While working on https://github.com/updatecli/updatecli/pull/1964
I released that we always run git checkout the default branch(main) after a git clone operation.
even though a git checkout is done before each source/condition/targets
This initial git checkout seems useless and generate error in some situation 
We can easily reproduce the problem with the following manifests
<details><summary>updatecli.yaml</summary>
```
scms:
default:
kind: git 
spec:
url: https://github.com/crate-ci/typos.git
```
</details>
triggers 
<details><summary>Console Output</summary>
```
+++++++++++
+ PREPARE +
+++++++++++
Loading Pipeline "test.2.yaml"
SCM repository retrieved: 1
ERROR: initial git checkout failed for repository https://github.com/crate-ci/typos.git - reference not found
ERROR: err - reference …
```

refactor: remove useless git checkout after a git clone

---

pkg/plugins/resources/dockerdigest/main.go
pkg/plugins/resources/dockerdigest/source.go

This pullrequest fixes the dockerdigest plugin by allowing to set different os than linux
<details><summary>updatecli.yaml</summary>
```
name: Get digest
sources:
tag/windows/amd64:
kind: dockerimage
spec:
architecture: windows/amd64
image: eclipse-temurin
digest/windows/amd64:
kind: dockerdigest
spec:
architecture: windows/amd64
image: eclipse-temurin
tag: 8u402-b06-jre
conditions:
digest/windows/amd64:
kind: dockerimage
disablesourceinput: true
spec:
architecture: windows/amd64
image: eclipse-temurin
tag: latest
```
</details>
<details><summary>Before fix</summary>
```
##############
##############
SOURCES
=======
tag/windows/amd64
-----------------
Searching for version matching pattern "latest"
✔ Docker Image Tag "latest" …
```

fix(dockerdigest): Allow to specify none linux os

---

.github/actions/spelling/allow.txt
_typos.toml
pkg/core/pipeline/action/main.go
pkg/core/pipeline/actions.go
pkg/core/pipeline/sort.go
pkg/core/pipeline/target/main.go
pkg/core/reports/actions.go
pkg/plugins/resources/gitea/pullrequest/clean.go
pkg/plugins/resources/gitlab/mergerequest/clean.go
pkg/plugins/resources/stash/pullrequest/clean.go
pkg/plugins/scms/github/comment.go
pkg/plugins/scms/github/pullrequest.go

This pullrequest allows the action `github/pullrequest` to automatically close pullrequest that have no file changed.
The situation will happens more frequently because of https://github.com/updatecli/updatecli/pull/2018
Still missing some test case (automated or manual)
* It would be great to add such behavior to other SCM as well
*  I am wondering if it would make sense for Updatecli to also close old pullrequest with a message like `this pullrequest appears to be created by Updatecli more than 90 days ago, now closing`

feat: close GitHub pullrequest when no file changed

---

pkg/plugins/scms/git/main.go

This pullrequest introduces an error message if an Updatecli manifest using the git scm provider relies on force set to true and the default behavior for the workingBranch which is set to false.
As explained in the error message, it can lead to unexpected behavior 
```
Better safe than sorry.
The scm force option set to true means that Updatecli is going to run "git push --force"
Some target plugin, like the shell one, run "git commit -A" to catch all changes done by that target.
Because the Git scm plugin has by default the workingBranch option set to false,
Updatecli may be pushing unwanted changes to the branch %q.
If you know what you are doing, please set the workingBranch option to false in your configuration file to ignore this error message
```
I am not adding this message to the …

chore: show extra warning for git scm

---

pkg/plugins/scms/git/main.go
pkg/plugins/scms/gitea/main.go
pkg/plugins/scms/gitea/scm.go
pkg/plugins/scms/github/main.go
pkg/plugins/scms/github/main_test.go
pkg/plugins/scms/github/scm.go
pkg/plugins/scms/gitlab/main.go
pkg/plugins/scms/gitlab/scm.go
pkg/plugins/scms/stash/main.go
pkg/plugins/scms/stash/scm.go

I started using 0.75.0-rc.1 and I am really annoyed that I now have to go over all my manifest for a behavior that I feel should be the default.
I would expected for any pipeline relying on a working branch created by Updatecli to be automatically recreated when the based branch is modified.
I already put in place a safeguard for the scm git plugin, because by default it doesn't create a working branch so if only force is set to true there is a risk to accidentally force push changes.
so the following pipeline would trigger an error
```
scms:
default:
kind: git 
spec:
url: git@github.com:updatecli/updatecli.git
force: true
```
will trigger an error asking to set `workingbranch` to either true or false to show that the user understand the behavior
```
scms:
default:
kind: git 
spec:
url: …
```

feat: By default scm github/gitlab/stash/gitea uses force push

---

pkg/plugins/autodiscovery/updatecli/policies.go

updatecli autodiscovery only matching rule
Test manually

fix: updatecli autodiscovery only matching rule

---

pkg/core/engine/run.go
pkg/core/reports/main.go
pkg/core/reports/main_test.go

UX improvement, this pull request sorts reports results so we first see failed pipelines at the bottom.
This should allows to better identify failed pipelines after an Updatecli execution
<details><summary>Example</summary>
```
⚠ deps(go): bump module go.mozilla.org/sops/v3:
Source:
✔ [module] Get latest golang module go.mozilla.org/sops/v3 version
Target:
⚠ [module] deps(go): bump module go.mozilla.org/sops/v3 to v3.8.1
⚠ deps(golang): bump Go version:
Source:
✔ [go] Get latest Go version
Target:
⚠ [go] deps(golang): bump Go version to 1.22.2
✗ deps(go): bump module github.com/nirasan/go-oauth-pkce-code-verifier:
Source:
✗ [module] Get latest golang module github.com/nirasan/go-oauth-pkce-code-verifier version
Target:
- [module] 
- [tidy] 
✗ deps(go): bump module golang.org/x/exp: …
```

chore: sort reports by results

---

.github/workflows/updatecli.yaml

Bump Updatecli version used in GitHub action to  v0.76.0-rc.1
```shell
go test
```

deps: bump updatecli to v0.76.0-rc.1

---

updatecli/values.d/update-compose.yaml

The purpose of this pullrequest is to not update all update-compose.yaml located on this repository like on https://github.com/updatecli/updatecli/pull/2024

fix: Restrict update-compose.yaml to automate update

---

.github/actions/spelling/allow.txt
.github/actions/spelling/patterns.txt
pkg/plugins/scms/github/main.go
pkg/plugins/scms/github/mocks.go
pkg/plugins/scms/github/pullrequest.go
pkg/plugins/scms/github/scm.go
pkg/plugins/scms/github/scm_test.go
pkg/plugins/utils/fileoperations.go
pkg/plugins/utils/fileoperations_test.go
pkg/plugins/utils/filepath_test.go
pkg/plugins/utils/gitgeneric/main.go
pkg/plugins/utils/gitgeneric/main_test.go

Fix #1914 
This pull request adds support for GitHub API commit. It allows Github SCM to commit a file in a GitHub repository using the GitHub API instead of using native Git.
The GitHub commit API is useful when a user is using the [automated token from Github Actions](https://docs.github.com/en/enterprise-cloud@latest/actions/security-guides/automatic-token-authentication) as it creates a signed commit automatically, removing the requirement of using a bot account with a GPG key configured.
For now I've hidden this feature behind the `commitUsingApi` (not loving the parameter name, happy for suggestions).
In addition I changed the Github pull request action to check if working branch is ahead using the API instead of relying on the native Git handler as I kept running in to issues where …

feat: Add support for GitHub API commit

---

pkg/core/engine/actions.go
pkg/core/pipeline/actions.go
pkg/core/pipeline/target/main.go

Fix #2039 
```shell
go test
```

fix: execute actions once all pipelines have been executed (part 2)

---

pkg/core/pipeline/actions.go
pkg/plugins/scms/github/pullrequest.go

Fix a regression introduced in https://github.com/updatecli/updatecli/pull/2046 when pipeline wouldn't update existing pullrequest.
This pullrequest also better identify action state to avoid running multiple time the same action
```shell
/
```

fix: always try to update existing pullrequest description

---

pkg/plugins/scms/github/main.go
pkg/plugins/scms/github/scm.go

Related to #1914 and issues described in [this comment](https://github.com/updatecli/updatecli/issues/1914#issuecomment-2080851598).
Note: I will probably not have time to add any tests this week, so feel free to take over @olblak or if approve if you feel it's good enough since most are API actions that can't be properly tested without integration tests.
The previous implementation used native Git to both create the working branch and fetching latest commit hash used when committing using API. This caused issues when using multiple targets with the same SCM due to the local cloned repository not having pulled the latest changes from the remote branch, which meant that `PushBranch` reverted changes done in the first target that ran.
To fix this, I've added the following: 
- Latest commit …

fix: use API for creating branch and fetching hashes when committing using Github API

---

.github/workflows/updatecli.yaml

chore: removing version pinning in updatecli workflow

---

.github/actions/spelling/allow.txt
pkg/plugins/utils/mavenmetadata/main.go
pkg/plugins/utils/mavenmetadata/main_test.go

Fix #2146
Add support for Maven repositories that contain XML encoding other than UTF-8.
Create decoder based on charset configured in XML reader
```shell
cd pkg/plugins/utils/mavenmetadata
go test
```
```yaml
sources:
latest:
kind: maven
spec:
repository: "https://plugins.gradle.org/m2/"
groupid: "io.freefair.gradle"
artifactid: "lombok-plugin"
```

feat(maven): support unmarshalling maven responses in other XML charsets

---

pkg/plugins/scms/github/main.go

Fix #XXX
Update docs about the `username` in GitHub
Given
```yaml
scms:
default:
kind: github
spec:
user: '{{ requiredEnv "GITHUB_ACTOR" }}'
owner: your-org
repository: your-private-repo
token: '{{ requiredEnv "GITHUB_TOKEN" }}'
branch: main
```
When running
```bash
$ GITHUB_TOKEN=$(gh auth token) \
GITHUB_ACTOR=my-actor \
updatecli diff --config  updatecli.d/bump.yml --debug
```
Then it fails with:
```bash
TARGETS
========
bump
-----------
DEBUG: checkout git branch "updatecli_main_updatecli-bump", based on "main"
DEBUG: authentication required
ERROR: something went wrong in target "bump" : "authentication required"
Pipeline "Bump snapshot version" failed
Skipping due to:
targets stage:	"something went wrong during target execution"
```
If I use a public repository, …

github: note username is needed when using github private repositories

---

pkg/plugins/autodiscovery/argocd/application.go
pkg/plugins/autodiscovery/argocd/main_test.go
pkg/plugins/autodiscovery/argocd/manifestTemplate.go
pkg/plugins/autodiscovery/argocd/testdata/empty/manifest.yaml
pkg/plugins/autodiscovery/argocd/testdata/sealed-secrets_sources/manifest.yaml
pkg/plugins/autodiscovery/argocd/utils.go
pkg/plugins/autodiscovery/argocd/utils_test.go

Fix #1911 
```shell
cd pkg/plugins/autodiscovery/argocd/
go test
```
Tested using manifest
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
name: guestbook
namespace: argocd
spec:
project: default
destination:
server: https://kubernetes.default.svc
namespace: default
sources:
- chart: elasticsearch
repoURL: https://helm.elastic.co
targetRevision: 8.5.0
- repoURL: https://github.com/argoproj/argocd-example-apps.git
path: guestbook
targetRevision: HEAD
```

feat: support sources for argocd autodiscovery

---

pkg/plugins/autodiscovery/golang/dependency.go
pkg/plugins/autodiscovery/golang/matchingRule.go
pkg/plugins/autodiscovery/golang/matchingRule_test.go

https://github.com/updatecli/updatecli/pull/2236 introduced a regression where only go version are updated and go modules are ignored
```shell
./bin/updatecli diff --config e2e/updatecli.d/success.d/autodiscovery/golang/golangOnly.yaml # should only update go version
./bin/updatecli diff --config e2e/updatecli.d/success.d/autodiscovery/golang/patchOnly.yaml  # should only update go modules
cd pkg/plugins/autodiscovery/golang/
go test
```

fix: golang autodiscovery module update

---

pkg/plugins/resources/npm/main.go

updatecli diff returns an error when the deprecated field is a bool.
```
json: cannot unmarshal bool into Go struct field versions.Versions.Deprecated of type string
```
I was testing it on a `package.json` with `react` and `react-dom`. The exact output below:
```
################################
################################
SOURCES
=======
npm
---
ERROR: error unmarshalling json: "json: cannot unmarshal bool into Go struct field versions.Versions.Deprecated of type string"
ERROR: ✗ json: cannot unmarshal bool into Go struct field versions.Versions.Deprecated of type string
ERROR: ✗ json: cannot unmarshal bool into Go struct field versions.Versions.Deprecated of type string
Pipeline "Bump \"react\" package version" failed
Skipping due to:
sources stage:  "json: cannot unmarshal bool …
```

fix(npm-source): Deprecated field can be bool

---

.github/workflows/go.yaml
.github/workflows/release.yaml
.goreleaser.yml

update goreleaser config to be v2 compliant
cfr https://goreleaser.com/deprecations/#removed-in-v2
```shell
make build.all
```

fix: update goreleaser config to be v2 compliant

---

pkg/core/engine/udash.go
pkg/core/pipeline/main.go
pkg/core/reports/main.go
pkg/core/reports/report.go
pkg/core/udash/helpers.go
pkg/core/udash/publish.go

This pullrequest is related to some ongoing experimentation with [github.com/updatecli/udash](https://github.com/updatecli/udash) and introduce the following changes
* Allow to publish reports to a Udash service without being authenticated
* Don't show error message if udash configuration file doesn't exist Fix #2181
* Refactor console output to better align with Action output now that they are executed after each pipeline  
To test this pull request, you'll need a local udash service as briefly explained on [github.com/updatecli/udash](https://github.com/updatecli/udash)
<details><summary>Console Output</summary>
```
ACTIONS
========
UDASH - EXPERIMENTAL
=====================
docs: bump updatecli version:
=> "http://localhost:3030/pipeline/reports/01ab976f-c443-4502-bd37-78c63db9d357" …
```

feat: Remove authentication requirement to publish reports to Udash

---

pkg/core/compose/file.go
pkg/core/compose/main.go

Fix #2285 
```shell
./bin/updatecli compose show
```
<details><summary>Console Output</summary>
```
Loading Updatecli compose file: "update-compose.yaml"
7 policies detected:
* Policy 0: "Local Updatecli Website Policies"
* Policy 1: "Update Updatecli policies"
* Policy 2: "Golang Version"
* Policy 3: "Major Golang Module update"
* Policy 4: "Minor Golang Module update"
* Policy 5: "Patch Golang Module update"
* Policy 6: "Update golangci-lint"
Initializing policy: "Local Updatecli Website Policies"
manifest: updatecli/updatecli.d
value: updatecli/values.d/scm.yaml
Initializing policy: "Update Updatecli policies"
manifest: /tmp/updatecli/store/46e599fb7e874ee3f1c9cf5e4dd64b328a15d61d03e106176b19a0768 …
```

chore: show updatecli compose information on console output

---

updatecli-compose.yaml
updatecli/values.d/update-compose.yaml
updatecli/values.d/updatecli-compose.yaml

* rename `deprecated update-compose.yaml` to `updatecli-compose.yaml`
* fix updatecli only rule

chore: rename update-compose.yaml to updatecli-compose.yaml

---

pkg/plugins/scms/github/main.go

After testing, I didn't identify any issues with the `usingcommitapi` behavior so I think it's safe to move it out of experimental to get more user exposure to the feature as I think it should be the default behavior in the future for the scm GitHub plugin

feat: moving github parameter `usingcommitapi` out of experimental

---

pkg/plugins/scms/github/scm.go

Fix #2362
Switch the username to commit via the api from `user` to `username`
As discussed with @olblak, it's not the first time this mismatch happens, the options are confusing. We should:
- deprecate "username" for "githubusername"
- deprecate "user" for "gituser"

fix: committing with `commitusingapi` should use github username

---

pkg/core/transformer/main.go

Fix #730
This PR introduces a log message (info level) when transformer are set up.
Example of output:
```
add
---
The shell 🐚 command "/bin/sh /var/folders/96/_x2r301n2d3_n_1s9hw4tg240000gp/T/updatecli/bin/58715a42e445bcda6902cec8477df16a3c91d4ae520e1df1c741bb5faa923f9d.sh" ran successfully with the following output:
----
1.0.0
----
✔ shell command executed successfully
[transformers]
✔ Result correctly transformed from "1.0.0" to "1.0.0-alpha"
✔ Result correctly transformed from "1.0.0-alpha" to "v1.0.0-alpha"
```
Also tested without transformer: no `[transformers]` log line.
```shell
go test
```
N.A.
N.A.

feat(transformers) show transformation as info messages

---

pkg/plugins/scms/github/scm.go

Fix #2362 
Correctly fix the commitusingapi as #2363 changed the wrong if branch
```shell
go test
```

fix: use GitHub username to commit via GitHub instead of git user

---

pkg/plugins/autodiscovery/golang/dependency.go
pkg/plugins/autodiscovery/golang/matchingRule.go

Before this pullrequest, a manifest like:
```
autodiscovery:
scmid: default
actionid:  default
groupby: all 
crawlers:
golang/gomod:
rootdir: pkg/plugins/resources/go/gomod/testdata
versionfilter:
kind: semver
pattern: patch
only:
- modules:
github.com/beevik/etree: ""
```
Would try to both update the module "github.com/beevik/etree" and the go version specified in the go.mod
With this pullrequest, Updatecli only update the Golang module
```shell
go test
```

fix: golang autodiscovery with module only

---

pkg/plugins/autodiscovery/terragrunt/utils.go

Instead of failing the whole file, just skip the locals

fix: ignore functions and variable set in terragrunt

---

pkg/core/pipeline/actions.go

For git scm action, the handler property on the action is nil. The [`RunCleanActions()` method](https://github.com/updatecli/updatecli/blob/main/pkg/core/pipeline/actions.go#L174) fails with a null pointer for these git scm actions on `updatecli apply`.
Stacktrace (updatecli version 0.82.2):
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2bec58a]
goroutine 1 [running]:
github.com/updatecli/updatecli/pkg/core/pipeline.(*Pipeline).RunCleanActions(0xc00127b3f8)
/home/runner/work/updatecli/updatecli/pkg/core/pipeline/actions.go:174 +0x14a
github.com/updatecli/updatecli/pkg/core/engine.(*Engine).runActions(0x5c924a0)
/home/runner/work/updatecli/updatecli/pkg/core/engine/actions.go:34 +0x459 …
```

Git SCM: Ignore missing action handler

---

.github/actions/spelling/expect.txt
pkg/core/text/main.go
pkg/core/text/main_test.go
pkg/plugins/utils/http/client.go

Add exponiental retry mechanism for fetching http resource
```shell
cd pkg/core/check
go test
```
Use a library like https://github.com/cenkalti/backoff instead of the implemented RetryClient

feat(core): implement retry client for http fetching

---

e2e/updatecli.d/success.d/dockerfile/Dockerfile.source
e2e/updatecli.d/success.d/dockerfile/dockerfile_source.yaml
pkg/plugins/resources/dockerfile/condition.go
pkg/plugins/resources/dockerfile/condition_test.go
pkg/plugins/resources/dockerfile/main.go
pkg/plugins/resources/dockerfile/main_test.go
pkg/plugins/resources/dockerfile/mobyparser/main.go
pkg/plugins/resources/dockerfile/mobyparser/main_test.go
pkg/plugins/resources/dockerfile/simpletextparser/keywords/arg.go
pkg/plugins/resources/dockerfile/simpletextparser/keywords/arg_test.go
pkg/plugins/resources/dockerfile/simpletextparser/keywords/env.go
pkg/plugins/resources/dockerfile/simpletextparser/keywords/env_test.go
pkg/plugins/resources/dockerfile/simpletextparser/keywords/from.go
pkg/plugins/resources/dockerfile/simpletextparser/keywords/from_test.go
pkg/plugins/resources/dockerfile/simpletextparser/keywords/label.go
pkg/plugins/resources/dockerfile/simpletextparser/keywords/label_test.go
pkg/plugins/resources/dockerfile/simpletextparser/keywords/main.go
pkg/plugins/resources/dockerfile/simpletextparser/main.go
pkg/plugins/resources/dockerfile/simpletextparser/main_test.go
pkg/plugins/resources/dockerfile/simpletextparser/test_fixtures/ARG.Dockerfile
pkg/plugins/resources/dockerfile/simpletextparser/test_fixtures/LABEL.Dockerfile
pkg/plugins/resources/dockerfile/source.go
pkg/plugins/resources/dockerfile/source_test.go
pkg/plugins/resources/dockerfile/target.go
pkg/plugins/resources/dockerfile/target_test.go
pkg/plugins/resources/dockerfile/types/main.go

Fix #2022
Fix #2275 
`dockerfile` improvements
```shell
cd pkgs/plugins/dockerfile
go test
```
This PR brings 4 changes to the dockerfile resources:
- Addition of the `stage` param for the Spec:
The default value (omit/empty) does not change the behaviour of the `condition` and `target`, all stages are considered for condition/targetting. But if a stage is specified, only that stage will be taken into account
- #2275 Creation of the `source`: `dockerfile now support a source attribute. Here the `stage` works a bit differently, if none is specified, then only the last stage of the dockerfile will be taken into account, otherwise we use the provided stage name. In the vast mojority of cases (non multi-stage dockerfile) this …

feat(dockerfile): source implementation

---

e2e/updatecli.d/success.d/autodiscovery/prow/prow.yaml

This pullrequest fixes the prow e2e tests by switching to a fork of knative/infra https://github.com/updatecli-test/knative-infra and then ignore failing  docker image
```shell
./bin/updatecli diff --config e2e/updatecli.d/success.d/autodiscovery/prow/prow.yaml
```

fix(prow/e2e): ignore broken image and use updatecli-test

---

.github/workflows/spelling.yml

Let's see if updating the GHA will resolve it failing on `-latest` (it wrongly detects it as `atest` cf #2758)
Changelog: https://github.com/check-spelling/check-spelling/releases/tag/v0.0.22
```shell
go test
```

chore(gha): update check-spelling to 0.0.22

---

pkg/plugins/resources/gitea/pullrequest/utils.go

fix #2802 
Trying to print out the http status codes
results in a deferencing null when they are not
set. Thus crashing the cmd in case of an error.
As we don't know the error, it's best to just
print the error here.
There may be cases in which the body is helpful to have, however that would need to be checked.
I think further down other cases handle HTTP codes so I don't think information is lost

Fix bug when gitea request fails

---

e2e/updatecli.d/success.d/temurin/sources.yaml

I am disabling this test until we find a solution. The root cause could be related to https://github.com/updatecli/updatecli/issues/2839

fix: disabling temurin s390x test

---

pkg/plugins/autodiscovery/terragrunt/test/testdata/terraform_without_source.hcl
pkg/plugins/autodiscovery/terragrunt/utils.go
pkg/plugins/autodiscovery/terragrunt/utils_test.go

Fix #2976 
```shell
cd pkg/plugins/autodiscovery/terragrunt
go test
```

fix(terragrunt): source block can be nil

---

e2e/updatecli.d/success.d/temurin/conditions.yaml
e2e/updatecli.d/success.d/temurin/sources.yaml
pkg/plugins/resources/temurin/api.go
pkg/plugins/resources/temurin/condition.go
pkg/plugins/resources/temurin/condition_test.go
pkg/plugins/resources/temurin/main.go
pkg/plugins/resources/temurin/main_test.go
pkg/plugins/resources/temurin/source.go
pkg/plugins/resources/temurin/source_test.go
pkg/plugins/resources/temurin/spec.go

Fix #2915
This PR introduces a new condition for the resource type `temurin`
- Supports specific version through source input or `spec`
- Introduces a condition-only keyword: `platforms` to check for multiple combinations of CPU Architecture and Operating Systems.
Associated documentation PR: https://github.com/updatecli/website/pull/1874
```shell
cd pkg/plugins/resources/temurin/
go test
```

feat(temurin): introduces condition to check for Adoptium releases existence

---

pkg/plugins/autodiscovery/helm/container.go
pkg/plugins/autodiscovery/helm/containerManifest.go
pkg/plugins/autodiscovery/helm/dependencies.go
pkg/plugins/autodiscovery/helm/dependencyManifest.go
pkg/plugins/autodiscovery/helm/main.go

SkipPackaging option allows users to bypass `helm dependency update` command during the helmchart target execution. 
For umbrella charts with many dependencies, the helm dependency update command is run repeatedly during dependency checks. This process is not always required and adds unnecessary overhead, especially in large projects.

Add SkipPackaging option for helm autodiscovery

---

go.mod
go.sum

This pullrequest replace my local fork of go-scm with the upstream one, now that my fix about GitLab merge request is released upstream in [drone/go-scm/v1.39.0](https://github.com/drone/go-scm/releases/tag/v1.39.0) and used in Updatecli since https://github.com/updatecli/updatecli/pull/3137
/

deps: use go-scm upstream project

---

CONTRIBUTING.adoc
Makefile
updatecli/updatecli.d/venom.yaml

In https://github.com/updatecli/updatecli/pull/650, @hervelemeur had been slowed down (and blocked) by the end to end testing.
This PR is a first step to help contributor: which add a minimalist doc of the constraints required to run the e2e locally
```shell
go test
```
The updatecli check will fail as the file `CONTRIBUTING.adoc` introduces a tracked line (in the new target for `venom.yaml` manifest).
Tested locally without the `scmid` looks good:
```
✔ ci: bump Venom version:
Source:
✔ [latestVersion] Get latest Venom release
Target:
✔ [contributing-doc] CONTRIBUTING documentation: update Venom version to v1.2.0
✔ [goWorkflow] ci: update Venom version to v1.2.0
```

doc(e2e tests) add a minimalistic documentation

---

.github/ISSUE_TEMPLATE/1-bug-report.yml
cmd/manifest_show.go
pkg/core/engine/manifest_show.go
pkg/core/engine/options.go
pkg/core/pipeline/utils.go

Fix #3161 
Add a new flavour to graph output
Given a pipeline we can now get a graph that can be easily added in a github comment
```bash
updatecli manifest show --graph --graph-flavour mermaid --experimental --config <your-pipeline.yaml>
```
```mermaid
graph TD
condition#1{"Should be succeeding (shell)"}
condition#1 --> target#3
target#3("Should be skipped (shell)")
condition#1 --> target#1
target#1("Should be succeeding (shell)")
target#1 --> target#3
condition#1 --> target#2
target#2("Should be succeeding (shell)")
target#2 --> target#3
source#1(["Should be succeeding (shell)"])
source#1 --> target#3
```

feat: add mermaid graph flavour

---

cmd/root.go
cmd/udash_login.go
pkg/core/udash/config_spec.go
pkg/core/udash/login.go
pkg/core/udash/logout.go
pkg/core/udash/main.go
pkg/core/udash/publish.go
pkg/core/udash/token.go

There are situations where using Udash and Updatecli without authentication makes sense. This commit introduces the following changes
* `udash login` can be used without authentication, just to configure the Updatecli configfile
* `udash login` accepts a new parameter `--api-url` to specify an api url
* Allow to use environment variable if no Updatecli configuration file detect at report publishing time
* `UPDATECLI_UDASH_API_URL`: defines the api where to publish Updatecli reports.
* `UPDATECLI_UDASH_ACCESS_TOKEN`: defines the bearer token to use if authentication is required
* `UPDATECLI_UDASH_URL`: defines the Udash service
* Prettify the updatecli configuration `$HOME/.config/updatecli/udash.json` file by adding indentation.
Worth mentioning, the udash.jon configuration file has …

feat: allow to login on Udash without auth enabled

---

pkg/plugins/utils/version/filter.go
pkg/plugins/utils/version/filter_test.go

I've had a couple of cases where i wanted to get latest semantic version, but the versions returned by the resource do not follow the convention.
The idea behind this to extract the version numbers using a regex then pass them on to the semver search.
[yarnpkg/berry](https://github.com/yarnpkg/berry) is a good example, as they do backport releases. Therefore latest of both `regex` and `latest` currently returns a `3.x`.
```shell
cd pkg/plugins/utils/version
go test
```
```shell
./bin/updatecli diff --config test.yaml
```
```yaml
sources:
default:
name: Get latest version
kind: githubrelease
spec:
owner: yarnpkg
repository: berry
token: '{{ requiredEnv "GITHUB_TOKEN" }}'
versionfilter:
kind: …
```

feat: add version filter regex/semver

---

pkg/plugins/autodiscovery/helm/container.go
pkg/plugins/autodiscovery/helm/main_test.go
pkg/plugins/autodiscovery/helm/testdata-6/chart/test-tag-01/Chart.yaml
pkg/plugins/autodiscovery/helm/testdata-6/chart/test-tag-01/values.yaml
pkg/plugins/autodiscovery/helm/testdata-7/chart/test-tag-02/Chart.yaml
pkg/plugins/autodiscovery/helm/testdata-7/chart/test-tag-02/values.yaml
pkg/plugins/autodiscovery/helm/testdata-8/chart/test-tag-03/Chart.yaml
pkg/plugins/autodiscovery/helm/testdata-8/chart/test-tag-03/values.yaml

Fix #3368
When the Helm Chart manifest does not have `tag` set, updatecli will use `latest` as tag. If the digest option is set to true this will update the tags to the latest digest of the image.
```shell
gh repo clone https://github.com/updatecli/updatecli.git
cd updatecli
gh co https://github.com/updatecli/updatecli/pull/3369
go test -run ^TestDiscoverManifests/Test_latest_tag*$ github.com/updatecli/updatecli/pkg/plugins/autodiscovery/helm
```
The following configuration will throw an error because the update `kind: helmfile` will not create new fields.
```yaml
ERROR: something went wrong in "target#nginx" : something went wrong in target "nginx" : "unable to update chart new-helm-template/helm-charts/test-tag-03: updating …
```

fix: use latest when tag is not set in autodiscover

---

pkg/plugins/utils/version/filter.go
pkg/plugins/utils/version/filter_test.go

`regex/semver` was added in #3347, I've had a chance to use it, and it probably isn't quite right compared to other version filters.
This could be considered a feature but it feels more like a bug, but when I've been using this. I didn't get changelogs back from the github release because it was using the regex output version not the original.
```text
16:25:54  ########
16:25:54  # YARN #
16:25:54  ########
16:25:54  
16:25:54  source: source#latestRelease
16:25:54  --------------------
16:25:55  Searching for version matching pattern ""
16:25:55  ✔ GitHub release version "4.6.0" found matching pattern "" of kind "regex/semver"
16:25:55  
16:25:55  
16:25:55  CHANGELOG:
16:25:55  ----------
16:25:55  no GitHub Release found for 4.6.0 on "https://github.com/yarnpkg/berry"
```
To test this …

fix!: preserve original version for regex/semver

---

pkg/plugins/resources/json/main.go
pkg/plugins/resources/json/target.go
pkg/plugins/resources/yaml/main_test.go
pkg/plugins/utils/dasel/read.go

Refactor json error message to remove misleading message, and provide additional context to others.
Core functionality of the json plugin shouldn't be affected
/

refactor: improving json error message

---

pkg/plugins/utils/gitgeneric/branch.go
pkg/plugins/utils/gitgeneric/file.go
pkg/plugins/utils/gitgeneric/main.go

Refactor git error messages, this pull request shouldn't affect core functionalities 
Fix #3396 
Before
```
SCM repository retrieved: 1
ERROR: failed cloning GitHub repository "https://github.com/olblak/fleet-lab.git"
ERROR: err - authentication required
```
After
```
SCM repository retrieved: 1
ERROR: failed cloning GitHub repository "https://github.com/olblak/fleet-lab.git"
ERROR: err - cloning: authentication required: Repository not found.
It appears that a password has been specified without a username, could it be related?
```
Fix #1014 
Before
```
ERROR: something went wrong in "target#contributing-doc" : something went wrong in target "contributing-doc" : "reference not found"
```
After
```
ERROR: something went wrong in "target#contributing-doc" : something went wrong in target …
```

refactor: git error messages

---

pkg/plugins/autodiscovery/argocd/application.go
pkg/plugins/autodiscovery/argocd/main_test.go
pkg/plugins/autodiscovery/argocd/manifestTemplate.go
pkg/plugins/autodiscovery/argocd/testdata/oci-helm-source/manifest.yaml
pkg/plugins/autodiscovery/argocd/utils_test.go

Fix #3459
Added `oci://` prefix for `sources.spec.url` to UpdateCLI manifest if the scheme is not set in ArgoCD Application manifest
```shell
cd pkg/plugins/autodiscovery/argocd/
go test
```

fix: ArgoCD autodiscovery for OCI registry

---

pkg/plugins/utils/version/filter.go
pkg/plugins/utils/version/filter_test.go

This change implements a `gosort` filter mode. This is intended to start a conversation around picking the "latest" version of a resource that uses the "calendar version" versioning method.
This seems really simple in the implementation (it just uses `slices.Sort()`), but should actually work for many of the calver use cases out there.
Thoughts?
```shell
go test
```

feat: add versionfilter of kind lexicographical

---

pkg/plugins/resources/helm/changelog.go

Fix #2975 
Use the version from the source output instead of the latest one
No spending more time on testing this change as I am planning to refactor soon this area

fix: retrieve correct helm chart changelog based on a version

---

pkg/plugins/autodiscovery/dockercompose/compose.go
pkg/plugins/autodiscovery/dockercompose/main_test.go
pkg/plugins/autodiscovery/dockercompose/manifestTemplate.go

Correctly handle platform parameter from docker compose file
```shell
cd pkg/plugins/autodiscovery/dockercompose
go test .
```

fix(autodiscovery/dockercompose): correctly set arch

---

pkg/plugins/autodiscovery/helm/container.go
pkg/plugins/autodiscovery/helm/main_test.go

Fix #3367 
Correctly handle ignore/only rules in helm autodiscovery plugin.
Also for some reason tests were broken as we were missing a few skippackaging setting
```shell
cd pkg/plugins/autodiscovery/helm
go test .
```

fix(autodiscovery/helm): correctly handle ignore/only rule

---

pkg/core/httpclient/retry.go
pkg/core/udash/publish.go
pkg/plugins/resources/bitbucket/client/main.go
pkg/plugins/resources/gitea/client/main.go
pkg/plugins/resources/gitlab/client/main.go
pkg/plugins/resources/stash/client/main.go
pkg/plugins/resources/temurin/main.go
pkg/plugins/scms/github/main.go

The custom retry http client does not current support http proxies. This PR adds support for using proxies variables if set.
Issue: GH-3219
Fix GH-3219

improvement(httpclient): add support for http proxy in retry client

---

e2e/updatecli.d/success.d/gitBranch.yaml
e2e/updatecli.d/success.d/githubRelease.yaml
pkg/plugins/autodiscovery/githubaction/main.go
pkg/plugins/autodiscovery/githubaction/main_test.go
pkg/plugins/autodiscovery/githubaction/testdata/digest/.github/workflows/updatecli.yaml
pkg/plugins/autodiscovery/githubaction/utils.go
pkg/plugins/autodiscovery/githubaction/utils_test.go
pkg/plugins/autodiscovery/githubaction/workflow.go
pkg/plugins/autodiscovery/githubaction/workflowManifestGitHubTemplate.go
pkg/plugins/autodiscovery/githubaction/workflowManifestGiteaTemplate.go
pkg/plugins/autodiscovery/githubaction/workflowManifests.go
pkg/plugins/autodiscovery/githubaction/workflow_test.go
pkg/plugins/resources/gitbranch/main.go
pkg/plugins/resources/gitbranch/source.go
pkg/plugins/resources/githubrelease/condition.go
pkg/plugins/resources/githubrelease/main.go
pkg/plugins/resources/githubrelease/main_test.go
pkg/plugins/resources/githubrelease/source.go
pkg/plugins/resources/githubrelease/source_test.go
pkg/plugins/resources/yaml/main.go
pkg/plugins/resources/yaml/target.go
pkg/plugins/resources/yaml/target_test.go
pkg/plugins/scms/github/client.go
pkg/plugins/scms/github/release.go
pkg/plugins/scms/github/release_test.go
pkg/plugins/utils/gitgeneric/branch.go
pkg/plugins/utils/gitgeneric/main.go

Fix #3507 
Introduce a `key` argument for github release to get the tag hash instead of the tag name.
```shell
go test
```
This pr introduces the following changes:
- `githubrelease` now supports an `key` argument like `gittag` that can either be `name` (default) or `hash`.
- `gitbranch` now supports an `key` argument like `gittag` that can either be `name` (default) or `hash`.
- `yaml` now accept a `comment` arg, when used in a `target` and with the `yamlpath` engine, it can be used to add a comment to a line.
<details>
<summary>Yaml comment</summary>
```yaml
---
owner: anakin
```
```yaml
---
sources:
default:
kind: shell
spec:
command: echo "obiwan"
comment:
kind: shell
spec:
command: echo "is the …
```

githubaction autodiscovery should allow for pinning version to commit hash 

---

pkg/core/text/main.go
pkg/plugins/resources/maven/condition.go
pkg/plugins/resources/maven/source.go
pkg/plugins/resources/maven/utils.go
pkg/plugins/utils/mavenmetadata/main.go

Spotted a few places where a URL containing username/password could leak
Tested manually

fix: objuscate username/password from URL in the console output

---

.golangci.yml

Fix 
```
Error: Failed to run: Error: Command failed: /home/runner/golangci-lint-1.64.5-linux-amd64/golangci-lint config verify
jsonschema: "linters-settings" does not validate with "/properties/linters-settings/additionalProperties": additional properties 'gomnd' not allowed
Failed executing command with error: the configuration contains invalid elements
```

ci: remove gomnd additional properties from golangci.yaml

---

pkg/plugins/scms/github/main.go
pkg/plugins/scms/github/main_test.go

Fix #3800 
Sets a default `oauth2` username for GitHub scm plugin in case no username is provided.
Added a test spec

feat: set oauth2 as default github username when username is not provided.

---

pkg/core/engine/autodiscovery.go

Fix #3955 
Tested manually with the following command from this repository 
```
updatecli manifest show --values updatecli/values.d/scm.yaml --values updatecli/values.d/golang_major.yaml ghcr.io/updatecli/policies/autodiscovery/golang:0.10.0@sha256:3b1a2b03b3cd8e33305ca165a8be2ca126a06be4cbdf388bf98e48a568855cdc
```

fix: use the right action configuration in autodiscovery

---

pkg/plugins/changelog/github/v3/api.go
pkg/plugins/resources/helm/changelog.go
pkg/plugins/resources/helm/changelog_test.go

Partially resolves #1836
Resolves #4041
This pull request introduces enhancement in changelog generation for helm charts:
- If there are `artifacthub.io/changes` in repository index, then use them to generate changelog
- Else if there is `Chart Source` link to GitHub repo in `artifacthub.io/links` annotation, then get changelog from github releases
- Otherwise use unchanged fallback
Additionally, I've updated pagination options for `getReleasesFromAPI` method. Otherwise, in repositories with tons of releases it takes too long to filter them.
```shell
cd pkg/plugins/resources/helm
export GITHUB_TOKEN="set your token" # needed for gathering github releases info
go test
```
There [were other …

feat: get helm changelog from annotations and github release

---

pkg/core/engine/autodiscovery.go

Fix #4169 
I mistakenly used the scmid instead of the real actionID in the newly generated pipeline.
I used the following manifest to test
```
scms:
github:
kind: github
spec:
owner: epinio
repository: helm-charts
branch: main
token: '{{ requiredEnv "GITHUB_TOKEN" }}'
autodiscovery:
scmid: github
actionid: pr
crawlers:
helm:
ignorecontainer: true
actions:
pr: 
kind: github/pullrequest
title: "feat: update helm chart dependencies with updatecli"
spec:
labels:
- updatecli
scmid: github
```

fix: generated autodiscovery pipeline uses original action id

---

pkg/plugins/resources/helm/changelog.go
pkg/plugins/resources/helm/changelog_test.go

Fix the helm changelog tests.
The root cause of the problem is that the changelog uses information retrieved from source execution, but in the context of the test we don't execute Helm Source function.
This is an issue for the test named "Chart without changes annotation" as it tries to generate a generic changelog instead of the version specified in the test.
While looking at the code, I also noticed that a else statement could be removed
```shell
cd pkg/plugins/resources/helm/
go test
```

fix: helm changelog tests

---

.github/workflows/release.yaml

This pull request is an attempt to fix the release pipelines when it comes to update the homebrew information
```
⨯ release failed after 18m57s             
error=
│ 1 error occurred:
│ 	* homebrew tap formula: could not update "Formula/updatecli.rb": PUT https://api.github.com/repos/updatecli/homebrew-updatecli/contents/Formula/updatecli.rb: 403 Resource not accessible by integration []
make: *** [Makefile:29: release] Error 1
```
from https://github.com/updatecli/updatecli/actions/runs/13793233484/job/38578302498

ci(release): Create a token for multiple repositories in the current owner's installation

---

e2e/updatecli.d/success.d/autodiscovery/golang/golangOnly.2.yaml
e2e/updatecli.d/success.d/autodiscovery/golang/golangOnly.yaml
e2e/updatecli.d/success.d/autodiscovery/golang/minorOnly.yaml
e2e/updatecli.d/success.d/autodiscovery/golang/moduleonly.yaml
e2e/updatecli.d/success.d/autodiscovery/golang/patchOnly.yaml
pkg/plugins/autodiscovery/golang/dependency.go
pkg/plugins/autodiscovery/golang/main.go

This pull request simplify the configuration of the Golang autodiscovery plugin to restrict version update to Go modules or go version by providing two new parameters
`onlygoversion` and `onlygomodule`
```shell
./bin/updatecli diff --config e2e/updatecli.d/success.d/autodiscovery/golang/moduleonly.yaml
./bin/updatecli diff --config e2e/updatecli.d/success.d/autodiscovery/golang/golangOnly.2.yaml
```

feat(golang/autodiscovery): make it easier to restrict to go module orr go version update

---

pkg/plugins/resources/shell/condition.go
pkg/plugins/resources/shell/environment.go
pkg/plugins/resources/shell/environments.go
pkg/plugins/resources/shell/main.go
pkg/plugins/resources/shell/main_test.go
pkg/plugins/resources/shell/source.go
pkg/plugins/resources/shell/target.go

Fix #1768 
Share a set of default environment variable with the shell plugin.
Improve the shell plugin parameter documentation.
```shell
updatecli diff --config /tmp/updatecli.yaml
```
where updatecli.yaml contains
```
targets:
default:
kind: shell
spec:
command: updatecli version
```

feat(shell): set default shell environments variable

---

pkg/plugins/resources/helm/utils.go

This PR adds support of basic authorization for non-oci private helm repos

feat: support basic authorization for non-oci private helm repos

---

updatecli/values.d/golang_major.yaml
updatecli/values.d/golang_minor.yaml
updatecli/values.d/golang_patch.yaml

Fix Updatecli pipelines 
```shell
go test
```

fix(updatecli): ignore some Go module version update for github.com/hashicorp/hcl/v2

---

pkg/plugins/autodiscovery/flux/helmreleaseManifestTemplate.go
pkg/plugins/autodiscovery/flux/main_test.go
pkg/plugins/autodiscovery/flux/ociRepositoryManifestTemplate.go
pkg/plugins/autodiscovery/flux/ociRepositoryManifests.go

Fix #4012 
Due to a regression introduced in #3797 
Flux helmrelease update would be ignored if actionID was set as it would result in a wrong manifest.
While looking into this package, I also noticed that ocirepository didn't support actionID correctly.
Some tests have been added to avoid this situation in the future.
```shell
cd pkg/plugins/autodiscovery/flux/
go test
```
I also tested this on the repository https://github.com/Bealvio/bealv@main
using 
```
updatecli diff --config updatecli/updatecli.d/flux-discovery.yaml
```

fix(autodiscovery/flux): don't ignore flux helmrelease update if using an actionID

---

pkg/plugins/autodiscovery/precommit/dependency.go
pkg/plugins/autodiscovery/precommit/main.go
pkg/plugins/autodiscovery/precommit/main_test.go
pkg/plugins/autodiscovery/precommit/manifestTemplate.go

Similar to https://github.com/updatecli/updatecli/pull/3508 but for precommit
This is something supported by the [pre-commit tool](https://pre-commit.com/#pre-commit-autoupdate)
```shell
cd pkg/plugions/autodiscovery/precommit
go test
```

feat: add support for digest in precommit autodiscovery

---

e2e/updatecli.d/success.d/autodiscovery/github/action/digest.yaml
pkg/plugins/autodiscovery/githubaction/main_test.go
pkg/plugins/autodiscovery/githubaction/templateGHAGitHub.go
pkg/plugins/autodiscovery/githubaction/testdata/digest/.github/workflows/updatecli.yaml
pkg/plugins/autodiscovery/githubaction/testdata/updatecli/.github/workflows/updatecli.yaml
pkg/plugins/autodiscovery/githubaction/workflowGHAManifest.go

Fix #4958 
I've updated the discoverManifest command to allow `main` and `master` when digest is set
```shell
go test
```

feat: digest should allow handling of main

---

pkg/plugins/autodiscovery/githubaction/main_test.go
pkg/plugins/autodiscovery/githubaction/templateGHAGitHub.go

Fix e2e tests to remove warning message from the githubaction autodiscovery plugin
```shell
cd pkg/plugins/autodiscovery/githubaction/
go test .
```

fix(autodiscovery/githubaction): replace deprecated key hash by hashtag

---

.github/workflows/release.yaml

For a few releases now, I get issues like 
| /opt/hostedtoolcache/go/1.24.3/x64/pkg/tool/linux_amd64/link: mapping output file failed: no space left on device 
Runner comes with a lot of things by default which I probably don't need

chore: cleanup space in release workflow

---

pkg/plugins/resources/dockerfile/main.go

Fix #5136 
The yaml specification had duplicate key, which where breaking the export.
This issue was introduced in https://github.com/updatecli/updatecli/pull/2591 and is in fact a typo.
```shell
go test
```

fix(dockerfile): typo in yaml specification

---

pkg/core/reports/action_test.go
pkg/core/reports/actions_test.go

When working on #5189 I found it difficult to update the tests as it relied on the correct string indentation.
Using https://github.com/sanity-io/litter to get the objects out of the existing tests, I've converted all the `FromString` tests to `.Merge` tests. This made it easier to update tests.
Also checked coverage and added a new Changelog scenarios where the new and old report have more items respectively. 
Also added a test for `ToActionsString` as a part of existing test ensuring the object round trips.
```shell
cd pkg/core/reports
go test
```

test(report): switch to testing report Merge instead of FromString

---

pkg/core/reports/action.go
pkg/core/reports/action_test.go

Again in my battle with markdown reports for bitbucket i noticed a bug in the descriptions.
We use `...\n\t* ...` throughout the code ([here](https://github.com/updatecli/updatecli/blob/79f248bedcbbbceb7a28e888ca4e359b949b7792/pkg/plugins/resources/yaml/target.go#L100), [here](https://github.com/updatecli/updatecli/blob/79f248bedcbbbceb7a28e888ca4e359b949b7792/pkg/plugins/resources/json/target.go#L151) and [here](https://github.com/updatecli/updatecli/blob/79f248bedcbbbceb7a28e888ca4e359b949b7792/pkg/plugins/resources/file/target.go#L188)), this doesn't output correctly in GitHub or Bitbucket (and probably GitLab) but haven't checked.
This can be replicated in common mark tester [here](https://spec.commonmark.org/dingus/?text=Something%20change%0A%09*%20value) 
<details><summary>GitHub …

fix(reports): update target description to output correctly in markdown

---

updatecli/updatecli.d/devcontainer.yaml

Recently discovered that the update pipeline wouldn't update devcontainers 
```shell
go test
```

fix: devcontainer update pipeline

---

pkg/core/reports/action.go
pkg/core/reports/action_markdown_template.go
pkg/core/reports/action_test.go
pkg/core/reports/actions.go
pkg/core/reports/actions_test.go
pkg/plugins/resources/bitbucket/pullrequest/create.go

Fix #5174
Merges markdown pipeline and targets output together.
Uses [goldmark](https://github.com/yuin/goldmark) ast to parse the markdown. 
It makes assumptions about the format, and possibly has edge cases missed. That might come out in the wild.
Also fix a bug with #5309 that doesn't support more than one item in the list.
```shell
cd pkg/core/reports
go test
```
```shell
export BITBUCKET_TOKEN="xxx"
bin/updatecli --config e2e/updatecli.d/success.d/bitbucket/scm.yaml --debug apply
bin/updatecli --config e2e/updatecli.d/success.d/bitbucket/scm.yaml --debug apply
```

feat(bitbucket): add support for pull request description merging

---

pkg/core/engine/utils.go

Fix #5541 
```shell
./bin/updatecli diff --config xxxxx
```

fix: panic when Updatecli manifests doesn't exist

---

e2e/updatecli.d/success.d/temurin/conditions.yaml

It seems that e2e are failing due to this line
```shell
updatecli diff --config e2e/updatecli.d/success.d/temurin/conditions.yaml
```

fix: remove linux/aarch64 from temurin e2e test

---

pkg/plugins/utils/action/main.go

This PR is a quick fix to avoid, when an action updates an existing change request, the error below:
```
Existing GitHub pull request found: <url redacted>
Pull Request available at:
<url redacted>
ERROR: failed parsing old report: XML syntax error on line 26: element <img> closed by </td>
Existing GitHub pull request found: <url redacted>
```

fix(actions) ensure HTML of change requests is valid (missing closingtag for `img`)

---

pkg/plugins/autodiscovery/cargo/dependencies.go
pkg/plugins/autodiscovery/cargo/main_test.go
pkg/plugins/autodiscovery/cargo/testdata/simple_crate/Cargo.toml
pkg/plugins/autodiscovery/cargo/testdata/workspace/Cargo.toml
pkg/plugins/autodiscovery/cargo/utils.go
pkg/plugins/autodiscovery/cargo/utils_test.go

Right now it handles regular and dev dependencies, but not build dependencies, which just get skipped.

feat: Add build-dependencies support to cargo autodiscovery
