README.md
cmd/root.go
pkg/maven/main.go
pkg/maven/main_test.go

Add a new maven source and maven condition.
Source:
We retrieve the latest version published
Condition:
We analyse the maven-metadata.xml to check if a version is published

Add new maven source and maven condition

---

pkg/github/main.go

Add some basic parameter checks

Add basic Github checks

---

README.md

Add links to a production scenario

Add example link to README

---

cmd/diff.go
pkg/engine/target/main.go

Always clean working directory when needed

---

README.md
pkg/yaml/main.go
pkg/yaml/main_test.go

This pull request allows updating YAML values specified with an array position
resolve #51

Add support for array in Target yaml key

---

pkg/github/main.go

* Checkout locally to remoteBranch value
* Add missing err output
* Fix json data type when reading github response
* Git branch shouldn't have empty space
resolve #52

Checkout locally to remoteBranch value

---

Makefile
utils/build.sh

Build binary for Windows/Mac/Linux

---

pkg/git/generic/main.go
pkg/git/generic/main_test.go
pkg/git/main.go
pkg/github/main.go

Sanitize git branch name

---

cmd/apply.go
cmd/diff.go
cmd/root.go
pkg/engine/main.go
pkg/engine/target/main.go
pkg/engine/target/options.go
pkg/yaml/main.go

This fix a bad behavior where using diff also applied changes to local files

Diff don't change target files

---

pkg/docker/main.go

This PR add docker registry v2 support, this required several changes as default behaviors and  API are not the same.
Tested and validated with 
```
source:
name: "Docker Image Published on Registry"
kind: dockerDigest
spec:
url: "mcr.microsoft.com"
image: "azure-cli"
tag: 2.9.0
```
and 
```
conditions:
docker:
name: "Docker Image Published on Registry"
kind: dockerImage
spec:
url: "mcr.microsoft.com"
image: "azure-cli"
```

Add docker registry v2 support

---

pkg/github/main.go

Github release source don't consider pre-release

---

pkg/engine/target/main.go

Fix commit message with appropriated value

---

doc/README.adoc

Add yaml condition doc

---

doc/README.adoc
pkg/core/engine/main.go
pkg/plugins/yaml/condition.go
pkg/plugins/yaml/target.go

* Print error message when source/condition/target failed
* Correctly return yaml condition and target result

Fix regressions

---

examples/updateCli.generic/githubRelease.tpl
examples/updateCli.generic/helmRelease.tpl
examples/updateCli.generic/maven.yaml
examples/values.yaml
pkg/core/engine/condition/main.go
pkg/core/engine/target/main.go
pkg/core/scm/main.go
pkg/plugins/git/main.go
pkg/plugins/git/scm.go

* Add maven example with explanation
* Escape confusing characters in git directory name fix https://github.com/olblak/updatecli/issues/112
* Correctly checkout scm repository before each condition/target definition
* Add helmRelease example with explanation

Add maven example with explanation

---

README.adoc

Update shield links in README.adoc

---

pkg/plugins/yaml/condition.go

Don't return condition ok when a yaml condition is wrong

Return false when wrong yaml condition

---

.github/workflows/go.yaml
Dockerfile
go.mod

Update to golang 1.15

---

.github/workflows/go.yaml
doc/README.adoc
pkg/plugins/docker/condition.go
pkg/plugins/docker/main.go
pkg/plugins/docker/main_test.go
pkg/plugins/docker/quayio.go
pkg/plugins/docker/registry/dockerhub/main.go
pkg/plugins/docker/registry/dockerhub/main_test.go
pkg/plugins/docker/registry/dockerregistry/main.go
pkg/plugins/docker/registry/dockerregistry/main_test.go
pkg/plugins/docker/registry/ghcr/main.go
pkg/plugins/docker/registry/ghcr/main_test.go
pkg/plugins/docker/registry/quay/main.go
pkg/plugins/docker/registry/quay/main_test.go
pkg/plugins/docker/source.go

Improve support for non dockerhub registries

---

doc/README.adoc

Update docker registry documentation

---

examples/updateCli.d/prometheus.tpl
pkg/plugins/helm/chart/changelog.go
pkg/plugins/helm/chart/main.go

fix #127 
An example is available [here](https://github.com/olblak/charts/pull/40)

include sources from helm chart

---

examples/updateCli.d/docker-compose.yaml
examples/updateCli.d/grafana-loki.tpl
examples/updateCli.d/jenkins-chart.tpl
examples/updateCli.d/jenkins-wiki-exporter.tpl
examples/updateCli.d/jenkins.tpl
examples/updateCli.d/jenkins.yaml
examples/updateCli.d/jenkinsio.tpl
examples/updateCli.d/nginx.yaml
examples/updateCli.d/pluginsite-api.tpl
examples/updateCli.d/prometheus.tpl
examples/values.yaml

Update configuration examples by removing hard coded values or just using up to date source of information

Update config examples

---

cmd/root.go

Don't systematically run the prepare stage

---

pkg/plugins/docker/registry/dockerhub/main_test.go
pkg/plugins/docker/registry/dockerregistry/main.go
pkg/plugins/docker/registry/ghcr/main.go
pkg/plugins/docker/registry/quay/main.go
pkg/plugins/github/main.go
pkg/plugins/github/pullrequest.go
pkg/plugins/yaml/target.go

Fix
```
✗ json: cannot unmarshal number into Go struct field response.SchemaVersion of type string
```

Fix various regression

---

pkg/core/engine/condition/main.go
pkg/core/engine/main.go

Add to modife source value using prefix and postfix as in the source and target stage so the following snippet test 
that the image jenkins/jenkins:<prefix><source output><postfix> exist on dockerhub registry
```
conditions:
docker:
name: "Docker Image Published on Registry"
prefix: <prefix>
postfix: <postfix>
kind: "dockerImage"
spec:
image: "jenkins/jenkins"
```

Add prefix/postfix to condition stage 

---

pkg/plugins/git/generic/main.go
pkg/plugins/github/scm.go

This PR is an attempt to no try create a local branch even the local branch already exist.

Checkout workflow

---

pkg/plugins/git/generic/main.go

In the current state if for some reason, one of the job modify an old branch, then the next job will reuse that old branch as the base for the new branch.

Checkout base branch before creating a new branch

---

.github/workflows/publish-assets.yaml

fix go version to 1.15 during publish assets

---

.github/release-drafter.yaml

Start using Sementatic Versioning with release-drafter
-> https://semver.org/spec/v2.0.0.html

Start using Sementatic Versioning

---

.github/workflows/publish-assets.yaml
.goreleaser.yml

Don't build the image for Darwin-i386 

**Deprecation**  Don't build artifact for darwin-i386

---

pkg/core/engine/target/main.go

Improve pull request manipulation scenarios

---

examples/updateCli.generic/helmChart/SCM.tpl
examples/updateCli.generic/helmChart/noSCM.yaml
examples/updateCli.generic/helmChart/requirement.tpl
pkg/plugins/helm/chart/main.go
pkg/plugins/helm/chart/target.go

I got a feedback to use one variable to configuration the helm chart version increment instead of the three bools

Simplify helmchart incremental chart version configuration

---

.github/workflows/publish-assets.yaml

Stop publishing i386 assets

---

.github/workflows/codeql-analysis.yml
.github/workflows/go.yaml
.github/workflows/publish-assets.yaml

Enable workfow dispatch on every github action

---

.github/workflows/release-sandbox.yaml
.github/workflows/release.yaml

* Trigger gorelease on published release
* Split goreleaser action into two different

Trigger gorelease on published release

---

.github/workflows/go.yaml
.github/workflows/release-sandbox.yaml
.github/workflows/release.yaml
.github/workflows/updatecli.yaml
Dockerfile
updatecli/updatecli.d/golang.yaml
updatecli/updatecli.d/gorelease.yaml

Fix -
Test updatecli configuration
```
export UPDATECLI_GITHUB_TOKEN=xxx
export UPDATECLI_GITHUB_ACTOR=xxx
updatecli diff --config updatecli/updatecli.d
```
Test Github Action job
```
act workflow_dispatch -j updatecli
```

Automate Golang and Goreleaser using updatecli

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/pull_request_template.md

- `s/Additionnal/Additional/`
- markdown lint
- minor clarifications

chore(github pull requests) typo + markdownlint on GitHub templates for issues and PRs

---

CONTRIBUTING.adoc

Added goreleaser requirement and removed outdated output, plus minor corrections.

chore(doc): minor corrections in CONTRIBUTING

---

go.mod
go.sum

Fix GHSA-mvff-h3cj-wj9c
```shell
go test
```

fix(go.mod) GHSA-mvff-h3cj-wj9c vulnerability

---

pkg/plugins/git/commit/main.go
pkg/plugins/git/commit/main_test.go

fix double space

---

CODE_OF_CONDUCT.md

I configured the updatecli.io domain so I can stop using my personnal domain for updatecli.

Update contact email address

---

README.adoc

* Fix deprecated example in README
* Minor README improvement

Fix deprecated example in README

---

pkg/core/pipeline/resource/main.go

Fix working

---

.github/release-drafter.yaml

This PR is a quick minor imporvement to improve release notes generated by release drafter to include documentation section

chore(release-drafter) add documentation labels

---

README.adoc

Add another vanity metric to show how many time updatecli was downloaded
/

Add another vanity metric

---

pkg/core/transformer/main.go

Followup of https://github.com/updatecli/updatecli/pull/551 and https://github.com/updatecli/website/pull/250
cc @smerle33

chore: add comment about the capturedIndex of findSubMatch

---

.github/release-drafter.yaml

chore(release-drafter) support labels `cleanup` and `deprecate` for patch version

---

pkg/core/pipeline/resource/main.go

chore: replace hardcoded ⚠

---

pkg/plugins/resources/awsami/condition.go
pkg/plugins/resources/awsami/filter.go
pkg/plugins/resources/awsami/helpers.go
pkg/plugins/resources/awsami/main.go
pkg/plugins/resources/awsami/source.go
pkg/plugins/resources/awsami/spec.go
pkg/plugins/resources/dockerdigest/main.go
pkg/plugins/resources/dockerdigest/source.go
pkg/plugins/resources/dockerfile/condition.go
pkg/plugins/resources/dockerfile/condition_test.go
pkg/plugins/resources/dockerfile/main.go
pkg/plugins/resources/dockerfile/main_test.go
pkg/plugins/resources/dockerimage/condition.go
pkg/plugins/resources/dockerimage/main.go

This pullrequest is adding some comment for spec structure so it can be used by https://github.com/updatecli/updatecli/pull/587
While I am in the plugin, I also take the opportunity to fix small linting issues
/
I am only focusing on spec as it's need for generating jsonschema with description
Still some plugin left

Add various spec comment and fix small linting issues

---

pkg/plugins/resources/helm/target.go

```
TARGETS
========
chart
-----
⚠ Key 'dependencies[0].version', from file '/tmp/updatecli/epinio/helm-charts/chart/epinio/Chart.yaml', was updated from '3.6.3' to '4.0.1'
Chart Version updated from "0.9.1" to "0.10.0"
```

Move helm chart (app)version message from debug to info

---

pkg/plugins/scms/github/pullrequest.go

Fixes #724
```shell
go test
```

chore: link to issues list instead of blank form

---

pkg/plugins/scms/github/pullrequest.go

Automerge by default assumes commit message, and since some of the sources are not able to customize their commit messages this is the most obvious way to get the desired merge message with automerge.
Fix #776
🤷‍♂️ Could not find a test for this area of the code, feel free to point me to it 😅 
Allow it to behave like user would make pull request with auto merge for squash and rebase commit messages.

Add use title for auto merge

---

.github/workflows/go.yaml
.gitignore
Makefile

Well I am interested if I get better at writting test

Configure Codecov

---

pkg/plugins/resources/xml/main.go

Remove obsolete constant from another xml implementation

Remove obsolete constant

---

.github/workflows/go.yaml
.golangci.yml
e2e/updatecli.d/success.d/githubPullrequest.yaml
pkg/core/pipeline/autodiscovery/main.go
pkg/core/reports/report.go
pkg/core/transformer/main.go
pkg/plugins/resources/helm/validate.go
pkg/plugins/resources/shell/target.go

Supersede https://github.com/updatecli/updatecli/pull/848
And fix new errors

Bump to Golangci 1.49 and fix linter issues

---

pkg/plugins/resources/json/spec.go

Add missing comment used by Jsonschema
```shell
go test
```

Add missing spec comment to json spec

---

pkg/plugins/resources/json/condition.go
pkg/plugins/resources/json/condition_test.go
pkg/plugins/resources/json/spec.go
pkg/plugins/resources/json/target.go
pkg/plugins/resources/json/target_test.go
pkg/plugins/resources/json/testdata/data.json

Align with Toml resource so we can do a single or multiple query
```shell
cp pkg/plugins/resources/json
go test
```

Add multiple query support to json resource

---

e2e/updatecli.d/success.d/csv.yaml

Add a basic e2e test for csv file

Add e2e test for csv

---

LICENSE

Fix #513 
Well there is no much say.
This topic bother me for a while :)
Unless you have some objection, I am gonna merge this PR in several days

Switch from MIT to Apache2

---

pkg/plugins/scms/git/commit/main.go
pkg/plugins/scms/git/commit/main_test.go

Fixes https://github.com/updatecli/updatecli/issues/1004 and https://github.com/updatecli/updatecli/issues/1005
See the steps to reproduce described in each issue.
Perhaps the variable `placeholders` can have a better name.
Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

Fix commit message when there is 2 or more commits for the same PR

---

e2e/updatecli.d/success.d/gitea/tag.yaml
pkg/core/pipeline/condition/main.go
pkg/plugins/resources/gitea/tag/condition.go

Fix #1053 
```shell
./bin/updatecli diff --config e2e/updatecli.d/success.d/gitea/tag.yaml
```

Allows to reverse expected condition result

---

e2e/updatecli.d/success.d/json.yaml

Comment some e2e tests that rely on GitHub api which is rate limited
/

chore(e2e tests) Comment e2e `json` test to avoid GitHub api rate limit

---

pkg/core/httpclient/throttler.go
pkg/plugins/resources/cargopackage/main.go

Throtlle request to default cargo index, in order to satisfy cargo crawl policy https://crates.io/data-access 
```shell
make test
```

[source][condition] Add throttler and throttle cargo requests

---

pkg/plugins/resources/xml/condition.go
pkg/plugins/resources/xml/target.go

Extract from https://github.com/updatecli/updatecli/pull/650

chore: add debug logs for XML resource (condition and target)

---

pkg/plugins/resources/shell/changeIf.go
pkg/plugins/resources/shell/condition.go
pkg/plugins/resources/shell/source.go
pkg/plugins/resources/shell/success/checksum/main.go
pkg/plugins/resources/shell/success/console/main.go
pkg/plugins/resources/shell/success/console/main_test.go
pkg/plugins/resources/shell/success/exitcode/main.go
pkg/plugins/resources/shell/success/exitcode/main_test.go
pkg/plugins/resources/shell/target.go

Provided current workingDir process to the changedIf resource
```shell
go test
```

Provide current workingDir information to shell resource changedif

---

pkg/plugins/autodiscovery/cargo/dependencyManifest.go
pkg/plugins/autodiscovery/cargo/test/main_test.go
pkg/plugins/autodiscovery/cargo/test/testdata/Cargo.toml

For some reason, I missed those tests in the cargo autodiscovery new behavior.
It shouldn't update 
/

Fix cargo autodiscovery test

---

pkg/plugins/resources/shell/condition.go
pkg/plugins/resources/shell/source.go
pkg/plugins/resources/shell/target.go

Fix a bug where precommand and postcommand do not use the same workingDir than the main command 
/

fix: shell changedif workdir

---

pkg/plugins/resources/gitlab/mergerequest/create.go

fix: Check gitlab pullrequest err before resp status

---

pkg/plugins/scms/github/pullrequest.go

Reverts updatecli/updatecli#1254

Revert "Disable GitHub auto merge flag"

---

.github/workflows/typos.yaml
_typos.toml
e2e/updatecli.d/success.d/csv.yaml
pkg/plugins/resources/dockerfile/mobyparser/main_test.go
pkg/plugins/resources/dockerfile/target.go
pkg/plugins/resources/dockerfile/types/main.go
pkg/plugins/resources/dockerimage/spec.go
pkg/plugins/resources/gitea/release/main.go
pkg/plugins/resources/gitea/release/target.go
pkg/plugins/resources/gitlab/release/main.go
pkg/plugins/resources/gitlab/release/target.go
pkg/plugins/resources/gitlab/tag/source_test.go
pkg/plugins/resources/npm/main.go
pkg/plugins/resources/stash/release/main.go
pkg/plugins/resources/stash/release/target.go
pkg/plugins/resources/toml/main.go
pkg/plugins/resources/xml/source.go
pkg/plugins/resources/yaml/source.go
pkg/plugins/scms/git/commit/main.go
pkg/plugins/scms/github/label.go
pkg/plugins/utils/version/filter.go

Enable typos github workflow to detect typos
This pullrequest also fix existing typos
```shell
typos
```

Add worfklow to test typos

---

updatecli/updatecli.d/golang/minor.yaml

Reverts updatecli/updatecli#1288

Revert "Removing temporarly the minor manifest"

---

CONTRIBUTING.adoc

This pullrequest formalize https://github.com/updatecli/updatecli/pull/1307
The goal is to use it as guideline for all the other plugins
There is nothing to test as this is just documentation enhancement

Add comment guideline for spec

---

pkg/plugins/resources/gitea/client/main.go
pkg/plugins/resources/gitea/client/spec.go
pkg/plugins/resources/gitea/pullrequest/main.go
pkg/plugins/resources/gitea/pullrequest/spec.go

Redesign gitea pullrequest comments to improve generated jsonschema
/

Refactor gitea action comment

---

pkg/plugins/resources/gitlab/client/main.go
pkg/plugins/resources/gitlab/client/spec.go
pkg/plugins/resources/gitlab/mergerequest/main.go
pkg/plugins/resources/gitlab/mergerequest/spec.go

Documentation pullrequest 
```shell
go test
```

Update gitlab mergerequest comment

---

pkg/core/pipeline/condition/main.go
pkg/core/pipeline/source/main.go
pkg/core/pipeline/target/main.go

Fix linter error which appears on https://github.com/updatecli/updatecli/pull/1301
this pullrequest doesn't affect Updatecli behavior

reference embedded field directly

---

pkg/plugins/resources/awsami/data_test.go
pkg/plugins/resources/awsami/source.go

Fix current broken CI 
```shell
go test
```

awsami source correctly handles if not filter

---

.github/ISSUE_TEMPLATE/1-bug-report.yml
pkg/core/pipeline/target/main.go

0.50.0 introduced a regression where target execution result is not using the correct result
To test this pull request, you need to executed an Updatecli pipeline.

Correctly handled target execution result

---

pkg/plugins/resources/yaml/target.go

* Fix yaml plugin message if executed in dryrun set to false
* Fix yaml plugin execution result
`
```shell
/
```

Fix yaml plugin regression

---

e2e/updatecli.d/warning.d/autodiscovery/cargo/kubewarden.versionfilter.yaml
pkg/plugins/autodiscovery/cargo/dependencies.go
pkg/plugins/autodiscovery/cargo/main.go
pkg/plugins/autodiscovery/npm/dependency.go

Similar to https://github.com/updatecli/updatecli/pull/1358
```shell
go test
```

Add cargo autodiscovery versionfilter

---

e2e/updatecli.d/warning.d/autodiscovery/dockerfile/versionfilter.yaml
pkg/plugins/autodiscovery/dockerfile/dockerfile.go
pkg/plugins/autodiscovery/dockerfile/main.go

Allow to override dockerfile autodiscovery versionfilter

---

updatecli/updatecli.d/golang/major.yaml
updatecli/updatecli.d/golang/minor.yaml
updatecli/updatecli.d/golang/patch.yaml

Add a manifest to automate major version update of Golang module
Reword pullrequest title for minor and patch update
```shell
updatecli diff --config updatecli/updatecli.d/golang/major.yaml --experimental
```

Automate major version update of golang module 

---

e2e/updatecli.d/success.d/gitTag.yaml
pkg/plugins/utils/gitgeneric/main.go

Fix #1392 
```shell
go test
```
* https://github.com/updatecli/updatecli/issues/1394

fix: reference must be defined once at the beginning

---

README.adoc

Update cosign verify instruction for container
```shell
go test
```

Update cosigin verify instruction for container

---

updatecli/updatecli.d/updatecli.yaml

Automate Updatecli version update in README.adoc
```shell
go test
```

Automate cosign instruction update

---

go.mod
updatecli/updatecli.d/golang/major.yaml
updatecli/updatecli.d/golang/minor.yaml
updatecli/updatecli.d/golang/patch.yaml

Tidy Up go.mod

---

pkg/plugins/autodiscovery/helm/test/main_test.go

Fix helm autodiscovery test

---

.github/workflows/go.yaml
.github/workflows/release.yaml
.github/workflows/updatecli.yaml

This pullrequest is an attempt to fix the now common `no space left issue`

disable go mod caching

---

.github/actions/spelling/allow.txt
pkg/plugins/resources/xml/main.go
pkg/plugins/resources/xml/source.go
pkg/plugins/resources/xml/spec.go

Provide additional documentation using multiline comment for the xml plugin
/

Re-word xml comment used for jsonschema

---

pkg/plugins/resources/helm/main.go
pkg/plugins/utils/docker/main.go

Refactor helm documentation

---

pkg/plugins/scms/git/commit/main.go
pkg/plugins/scms/git/main.go
pkg/plugins/scms/git/sign/main.go
pkg/plugins/scms/gitea/main.go
pkg/plugins/scms/github/main.go
pkg/plugins/scms/gitlab/main.go
pkg/plugins/scms/gitlab/scm.go
pkg/plugins/scms/gitlab/util.go
pkg/plugins/scms/stash/main.go

This pullrequest improves several scm comments that are used to generate the documentation for www.updatecli.io and IDE documentation

Improve scm comments

---

.github/workflows/go.yaml

Due to https://github.com/golangci/golangci-lint/issues/4037 We have many false positive

Downgrade golangci linter to 1.54.1

---

go.mod
go.sum
pkg/core/jsonschema/main_test.go

Fix [#XXX](https://github.com/updatecli/updatecli/pull/1569)
```shell
go test
```

Move jsonschema test from patternProperties to additionalProperties

---

pkg/plugins/autodiscovery/golang/dependency.go
pkg/plugins/autodiscovery/golang/manifestTemplate.go
pkg/plugins/autodiscovery/golang/test/main_test.go

```shell
cd pkg/plugins/autodiscovery/golang/testdata
go test
```

Show version in Golang autodiscovery target name

---

updatecli/updatecli.d/golang/major.yaml

updatecli.d: golang/major.yaml

---

pkg/core/config/main.go

This commit also reword jsonschema description with additional example
/
Remove both Title and Pullrequest in a futur pullrequest

chore: tag pipelineid as required in jsonschema

---

updatecli/updatecli.d/golang/golang.yaml
updatecli/updatecli.d/golang/major.yaml
updatecli/updatecli.d/golang/minor.yaml
updatecli/updatecli.d/golang/patch.yaml
updatecli/updatecli.d/golangci-lint.yaml
updatecli/updatecli.d/updatecli.yaml
updatecli/updatecli.d/venom.yaml

* define a pipelineid value
* update target name to be conventional commit compliant
* remove useless commit title parameter

chore: cleanup updatecli configuration

---

README.adoc

Update README.adoc example

---

.github/actions/spelling/allow.txt
pkg/core/reports/action.go
pkg/plugins/utils/ci/githubactions.go
pkg/plugins/utils/ci/gitlabci.go
pkg/plugins/utils/ci/jenkins.go
pkg/plugins/utils/ci/main.go
pkg/plugins/utils/ci/main_test.go

Follow up of #1737 (see https://github.com/updatecli/updatecli/pull/1737#discussion_r1382388606)
This PR only refactor the code to avoid duplication, by introducing a new `ci` package.
Allows extensibility with custom  behaviors in the future.
Please note the validation of each CI has been decreased: we can add more validation but it looks like a lot of code for something not really probable. 
```shell
cd pkg/plugins/utils/ci
go test
```

chore(actions) avoid code duplication for report's PipelineURL generation

---

pkg/plugins/autodiscovery/dockerfile/matchingRule.go
pkg/plugins/autodiscovery/dockerfile/matchingRule_test.go

Fix #1716 
```shell
cd pkg/plugins/autodiscovery/dockerfile/
go test
```

fix(autodiscovery/dockerfile): allow multiple ignore rule

---

pkg/plugins/autodiscovery/dockercompose/matchingRule.go
pkg/plugins/autodiscovery/dockercompose/matchingRule_test.go

Similar to #1750  
```shell
cd pkg/plugins/autodiscovery/dockercompose/
go test
```

fix(autodiscovery/dockercompose): allow multiple ignore rule

---

.github/actions/spelling/allow.txt
e2e/updatecli.d/warning.d/autodiscovery/helmfile/example.1.yaml
pkg/plugins/autodiscovery/helmfile/matchingRule.go
pkg/plugins/autodiscovery/helmfile/matchingRule_test.go
pkg/plugins/autodiscovery/helmfile/releases.go

Similar to #1752 
```shell
go test
```

feat(autodiscovery/helmfile): allow advanced ignore/only rule

---

README.adoc

Add a link to a talk I delivered at the CIVO Navigate in London back in September

Add a link to a Civo cloud video

---

pkg/plugins/autodiscovery/helmfile/releases.go

Spotted a useless error message

chore(helmfile): remove useless error message

---

pkg/core/scaffold/readme.go

Minor improvement to the scaffolded policy readme

chore: improve contributing section scaffolded readme

---

pkg/plugins/scms/gitea/scm.go
pkg/plugins/scms/github/scm.go
pkg/plugins/scms/gitlab/scm.go
pkg/plugins/scms/stash/scm.go

Fix #1897 
I test this pullrequest by running the following commands:
```shell
./bin/updatecli apply --config updatecli/updatecli.d/venom.yaml --push=false 
cd /tmp/updatecli/github/updatecli/updatecli/ 
git branch 
```
I should be in the branch named `updatecli_main_venom`

feat: add base branch to temporary working branch

---

pkg/plugins/autodiscovery/fleet/main_test.go

always run fleet autodiscovery test
```shell
go test
```

clean: always run fleet autodiscovery test

---

pkg/plugins/autodiscovery/golang/dependency.go
pkg/plugins/autodiscovery/helm/container.go

fix: remove useless printf
```shell
go test
```

fix: remove useless printf

---

go.mod

Add suggested in https://github.com/github/codeql/issues/15647
This is an attempt to fix the codeql issue

Update go.mod with golang patch version

---

pkg/plugins/resources/dockerimage/spec.go

Fix #1977 
This pullrequest improves documentation for the dockerimage plugin
/

chore: update dockerimage doc

---

.github/workflows/updatecli.yaml

deps: bump updatecli workflow to 0.76.0-rc.4

deps: bump updatecli workflow to 0.76.0-rc.4

---

pkg/plugins/resources/go/gomod/condition_test.go
pkg/plugins/resources/go/gomod/main.go
pkg/plugins/resources/go/gomod/source.go
pkg/plugins/resources/go/gomod/source_test.go
pkg/plugins/resources/go/gomod/spec.go
pkg/plugins/resources/go/gomod/version.go

gomod plugin allow http,https,file scheme
```shell
pkg/plugins/resources/go/gomod/
go test
```

feat: gomod plugin allow http,https,file scheme

---

pkg/plugins/resources/go/gomod/condition.go
pkg/plugins/resources/go/gomod/condition_test.go

* feat: gomod allow to check module existence only
* fix condition scm directory
```shell
cd pkg/plugins/resources/go/gomod/
go test
```

feat: gomod allow to check module existence only

---

.github/actions/spelling/allow.txt
pkg/plugins/scms/github/main.go

Follow up of https://github.com/updatecli/updatecli/issues/1914
Tested manually

chore: gate GitHub API commit behind experimental flag

---

pkg/core/engine/actions.go
pkg/core/pipeline/actions.go
pkg/plugins/scms/github/pullrequest.go

Fix #2068 
```shell
go test
```

fix: GitHub pullrequest description updated to a wrong content 

---

ADOPTERS.md

chore: Add Bloomberg to Adopters

---

pkg/plugins/scms/github/scm.go
pkg/plugins/utils/gitgeneric/main.go

Fix #2195 
To test this pull request, you used the this [Updatecli manifest](https://github.com/olblak/kubernetes-marketplace/blob/updatecli_test-2039_kubewarden/.github/updatecli/updatecli.d/kubewarden.yaml) to open pullrequest like [olblak/kubernetes-marketplace#134](https://github.com/olblak/kubernetes-marketplace/pull/134) where I needed to be sure that each commit would be atomic.
Then I run the same manifest manifest to tests the following scenario:
1. The working branch doesn't exist so we create it and open a pullrequest
2. The working branch exist locally but not remotely so we correctly push the local changes without opening a pullrequest
3. The working branch exist remotely and already up to date so we do nothing
/
/

fix: correctly pull remote branches when using GitHub api

---

pkg/core/transformer/main_test.go

fix: transformer test error message

---

pkg/core/transformer/main.go
pkg/core/transformer/main_test.go

fix: misleading transformer error message

---

pkg/plugins/autodiscovery/argocd/main.go

Add additional semver patterns to comments based off https://github.com/updatecli/updatecli/issues/2467
```shell
go test
```

Update: Add additional semver patterns to comments

---

.github/actions/spelling/allow.txt
CONTRIBUTING.adoc
README.adoc

doc: Improve README and Contributing

---

.github/actions/spelling/allow.txt
pkg/plugins/autodiscovery/terragrunt/test/testdata/simple_localized.hcl
pkg/plugins/autodiscovery/terragrunt/utils.go

Fix #2491 
Terragrunt locals may contains non string value

fix: terragrunt locals might be sthg else than string

---

pkg/core/pipeline/action/main.go

Improve https://github.com/updatecli/updatecli/pull/2529 debugging
/

fix: action log message when using invalid action kind

---

go.mod
go.sum
pkg/plugins/resources/gitlab/client/main.go

Fix #2429 
While investigating this issue, I noticed that I wasn't using the recommended way of authenticating on GitLab according
this [documentation](https://github.com/drone/go-scm?tab=readme-ov-file#authentication)
This pull request uses a fork of the go-scm library until my fix is merged upstream
Test manually

fix:  gitlab merge requests error

---

e2e/updatecli.d/success.d/githubRelease.yaml
pkg/plugins/resources/gitlab/branch/source_test.go

Gitlab source test may fail if the example repo has an updatecli worker branch in it
```shell
go test
```

chore(gitlab tests) more restrictive main regex

---

.github/actions/spelling/excludes.txt
.github/actions/spelling/patterns.txt

Fix:
* https://github.com/updatecli/updatecli/security/code-scanning/2412
* https://github.com/updatecli/updatecli/security/code-scanning/2479
```shell
go test
```

chore: fix spelling workflow security warning

---

updatecli/values.d/golang_patch.yaml

Switching to one patch update at a time, as we have a few dependencies update that I need to fix
/

chore: update golang patch one at a time

---

pkg/plugins/utils/version/filter.go
pkg/plugins/utils/version/filter_test.go

Fix prerelease semver filtering when current version is stable

---

.github/workflows/spelling.yml

Let disable spellcheck until we figure out what's wrong
I tried using act but it failed for obscure reason
` act pull_request_target -W .github/workflows/spelling.yml `

Disable spellcheck

---

e2e/updatecli.d/success.d/autodiscovery/precommit/example.1.yaml
e2e/updatecli.d/success.d/precommit/precommit.yaml
pkg/core/pipeline/autodiscovery/main.go
pkg/plugins/autodiscovery/precommit/dependency.go
pkg/plugins/autodiscovery/precommit/main.go
pkg/plugins/autodiscovery/precommit/manifestTemplate.go
pkg/plugins/autodiscovery/precommit/matchingRule.go
pkg/plugins/autodiscovery/precommit/matchingRule_test.go
pkg/plugins/autodiscovery/precommit/precommit.go
pkg/plugins/autodiscovery/precommit/test/main_test.go
pkg/plugins/autodiscovery/precommit/test/testdata/precommit/.pre-commit-config.yaml
pkg/plugins/autodiscovery/precommit/test/testdata/simple/.pre-commit-config.yaml
pkg/plugins/autodiscovery/precommit/utils.go
pkg/plugins/autodiscovery/precommit/utils_test.go
pkg/plugins/utils/test/main.go

Fix #2431 
Implement autodiscovery for precommit
```shell
cd pkg/plugins/autodiscovery/precommit
go test
```

feat(autodiscovery/precommit): initial implementation

---

CONTRIBUTING.adoc

While working on resolving an issue, I noticed what appeared to be some typographical errors. 
These proposed modifications aim to improve the clarity and accuracy of the text. I welcome any feedback or discussion regarding these suggestions.

fix(doc): Typos

---

_typos.toml
e2e/updatecli.d/success.d/dependsonchangeor.yaml
e2e/updatecli.d/success.d/inverted_deps.yaml
pkg/core/pipeline/main_test.go
pkg/core/pipeline/utils.go

Fix #3159 
```shell
go test
```

fix: only look at target when target has dependsonchange: true

---

pkg/plugins/resources/stash/pullrequest/create.go

Fix Bitbucket Server/Stash does not support HTML, use the Markdown renderer instead.
```shell
./updatecli compose diff
./updatecli compose apply 
```
```yaml
name: golangci-lint
scms:
go-repo:
kind: stash
spec:
url: '{{ .bitbucket.url }}'
owner: '{{ .oci_repos.project }}'
branch: '{{ .bitbucket.branch }}'
username: '{{ requiredEnv "BITBUCKET_USER" }}'
token: '{{ requiredEnv "BITBUCKET_TOKEN" }}'
email: '{{ requiredEnv "SVC_CLOUD_GO_BOT_2_EMAIL" }}'
user: '{{ requiredEnv "SVC_CLOUD_GO_BOT_2_FULLNAME" }}'
repository: go
build-go-repo:
kind: stash
spec:
url: '{{ .bitbucket.url }}'
owner: '{{ .bitbucket.oci_project }}' 
branch: '{{ .bitbucket.branch }}'
username: '{{ requiredEnv "BITBUCKET_USER" }}'
token: '{{ requiredEnv …
```

fix(stash): use markdown body instead of html

---

go.mod
pkg/core/config/template.go
pkg/core/config/template_test.go

Fix #3284 
Replace the custom merging logic with mergo library
A quick test against https://github.com/gionn/updatecli-bug-3284 worked succesfully
More tests to come?

feat: allow to deepmerge multiple values file

---

.github/pull_request_template.md

Add a checklist item to the pull request template for documentation updates.

chore: update pr template with documentation check list

---

.github/workflows/go.yaml
.golangci.yml
pkg/core/config/helper.go

`Fix` https://github.com/updatecli/updatecli/pull/3410
I also took the opportunity to remove deprecated or archived linters
```shell
golangci-lint run
```

fix: update golangci-lint to 1.63.4

---

updatecli/updatecli.d/devcontainer.yaml

This pullrequest add a new Updatecli to automate devcontainer image update
```shell
updatecli diff --config updatecli/updatecli.d/devcontainer.yaml --values updatecli/values.d/scm.yaml
go test
```

feat: add updatecli pipeline for devcontainer

---

pkg/plugins/utils/gitgeneric/main.go

While working on the github action autodiscovery, we realize that the gittag plugin returns the hash of the annotated tag if it finds one otherwise it returns the hash of the commit associated with that tag.
In the context of Updatecli, we always want to hash of the associated commit
To test this pull request, I used the following manifest:
```
name: Run {{ source "default" }}
sources:
default:
kind: gittag
spec:
url: git@github.com:aws-actions/amazon-ecr-login.git
key: hash
versionfilter:
kind: regex
pattern: "v2.0.1"
```
While the git tag may change after this commit, I don't see a place where it could be an issue
We could add in the futur a specific option to only return annotated git tag hash

fix(gittag): always return lightweight git tag

---

README.adoc

Adding two talks to the list of conferences where Updatecli is present

chore: update conferences in README

---

pkg/plugins/autodiscovery/dockercompose/main.go

chore: rewrite autodiscovery dockercompose plugin comment

---

.github/workflows/release.yaml
.github/workflows/updatecli.yaml
updatecli-compose.yaml
updatecli/values.d/githubaction.yaml

https://github.com/tibdex/github-app-token/issues/99
Fix #XXX
```shell
go test
```

feat: switch to official github action to obtain app token

---

pkg/plugins/resources/maven/source.go
pkg/plugins/resources/maven/source_test.go

Fix #3889
```shell
go test
```

fix(maven): check all configured repositories before returning an error

---

pkg/plugins/resources/helm/changelog.go
pkg/plugins/resources/helm/changelog_test.go

Related to PR #4164
- fix github release tests
- add 1 more test for github releases
- fix changelog generation from github releases

fix: helm changelogs from github releases

---

updatecli/values.d/githubaction.yaml

Opening pullrequest for visibility

fix: only update github action version in .github/workflows

---

go.mod
pkg/plugins/resources/file/condition.go
pkg/plugins/resources/file/target.go
pkg/plugins/resources/maven/main.go
pkg/plugins/resources/xml/main.go
pkg/plugins/resources/yaml/source.go
pkg/plugins/scms/git/commit/main.go

Supersede #4403 
```shell
make test-short
```

deps: Bump Golang version to 1.24.1

---

updatecli-compose.yaml

Minor configuration fix to automate github action update

fix: Add missing values file in updatecli-compose.yaml

---

go.mod
go.sum
pkg/plugins/resources/hcl/main.go

Bump github.com/minamijoyo/hcledit to v0.2.17 which required a minor code change
```shell
cd pkg/plugins/resources/hcl/
go test
```

deps: bump github.com/minamijoyo/hcledit to v0.2.17

---

updatecli/values.d/golang_major.yaml

To improve visibility, open one pullrequest for golang major update

deps: use one PR per golang major update

---

.github/workflows/codeql-analysis.yml

deps: Update ubuntu runner for codeql-analysis.yml

---

ADOPTERS.md

Add company where I work to the list of adopters

chore: Update ADOPTERS.md

---

pkg/core/transformer/main.go
pkg/core/transformer/main_test.go

Fix #4869 
```shell
go test
```

feat: add quote/unquote transformers

---

e2e/updatecli.d/success.d/autodiscovery/github/action/digest.yaml

fix: bad owner reference

---

e2e/updatecli.d/success.d/autodiscovery/github/action/digest.yaml
e2e/updatecli.d/success.d/autodiscovery/github/action/updatecli-test__github-actions.yaml
e2e/updatecli.d/success.d/autodiscovery/github/action/updatecli.yaml

Following #4968  and #4959 
```shell
./bin/updatecli diff --config e2e/updatecli.d/success.d/autodiscovery/github/action/
```

fix: github action e2e test branch

---

pkg/plugins/autodiscovery/githubaction/main_test.go
pkg/plugins/autodiscovery/githubaction/templateGHAGitHub.go

Follow up of https://github.com/updatecli/updatecli/pull/4975
Apparently I updated the wrong configuration
```shell
go test
```

fix(autodiscovery/githubaction: revert manifest template

---

e2e/updatecli.d/warning.d/json.yaml
go.mod
go.sum
pkg/plugins/resources/json/condition.go
pkg/plugins/resources/json/condition_test.go
pkg/plugins/resources/json/main.go
pkg/plugins/resources/json/source.go
pkg/plugins/resources/json/source_test.go
pkg/plugins/resources/json/spec.go
pkg/plugins/resources/json/target.go
pkg/plugins/resources/json/target_test.go
pkg/plugins/utils/dasel/main.go
pkg/plugins/utils/dasel/put.go
pkg/plugins/utils/dasel/query.go
pkg/plugins/utils/dasel/read.go

Fix #5750 
```shell
cd pkg/plugins/resources/json/
go test
```
I made some comment refactoring to improve documentation based on the jsonschema
Probably worth to improve the toml plugin as well in a separated PR

feat: add Dasel v2 support for the JSON plugin

---

cmd/manifest_show.go
pkg/core/engine/manifest_show.go
pkg/core/pipeline/main.go
pkg/core/pipeline/utils.go
pkg/core/reports/report.go

Add mermaidjs graph to the report so it can be used by Udash
```shell
go test
```

feat: add mermaidjs graph to report

---

README.adoc

I am curious about the project scarf.sh, so I am adding a pixel to see that kind of metrics it can detect.
The pixel will only monitor the README file on this repository.
I may also add another pixel on the website and docker images

chore: test project telemetry using Scarf.io
